### ISSUE TITLE
Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server. version `GLIBC_2.38' not found

### ISSUE THREAD

**Issue by olatoft** [dotnet/vscode-csharp#7031] opened 2024-04-09 10:04 UTC
## Environment data

<details>
    <summary>`dotnet --info` output:</summary>

.NET SDK:
 Version:           8.0.103
 Commit:            6a90b4b4bc
 Workload version:  8.0.100-manifests.e99a2be4

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.10
 OS Platform: Linux
 RID:         ubuntu.23.10-x64
 Base Path:   /usr/lib/dotnet/sdk/8.0.103/

.NET workloads installed:
 Workload version: 8.0.100-manifests.e99a2be4
There are no installed workloads to display.

Host:
  Version:      8.0.3
  Architecture: x64
  Commit:       9f4b1f5d66

.NET SDKs installed:
  6.0.128 [/usr/lib/dotnet/sdk]
  8.0.103 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.28 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.3 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.28 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>

VS Code version: 1.88
C# Extension version: 2.23.15
OS: Ubuntu 23.10

## Steps to reproduce

1. `$ dotnet new console -o test-languageserver`
2. `$ code test-languageserver`
3. The following notification toast appears: `Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server. Source: C#`
4. If I click on `Go to output` in the toast, the output lists the following error:

```
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 10:55:47] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
```

<details>
    <summary>Full error message</summary>
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
[Error - 10:55:47] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
	at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
	at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
	at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/binding.js:9:1)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/backend.js:18:19)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/index.js:21:17)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at 884 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1301229)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 7974 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290437)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 5175 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290103)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 3843 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:323341)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 4054 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:335524)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8746 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:312316)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 9972 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1194711)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8902 (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1196784)
	at __webpack_require__ (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at /home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1450511
	at /home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451450
	at Object.<anonymous> (/home/n645862/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451489)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:119:18)
	at Function.i [as __$__nodeRequire] (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:5:98)
	at m.xb (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:30898)
	at async Promise.all (index 0)

</details>

## Expected  behavior
No error message, and language server works. For instance, I expect suggestions when I start to type things like `Console.WriteLine("");`, and I expect a method signature toast when I hover over a method call.

## Actual behavior
I get the error message described above, and language server does not seem to work. For instance, the only suggestions I get when I start to type, are those that just suggest other words in the file (those suggestions with the "abc" type), and when I hover over a method call, I get no method signature toast.

## Additional context
This worked until just recently for me.

Thanks for the good product, I hope to be able to use these features again soon :)

**Comment by jordan-day** [comment] 2024-04-09 19:46
Also seeing this issue. 
Would appreciate a fix or workaround! Thanks!

**Comment by rauljosepalma** [comment] 2024-04-09 20:55
Same problem here, but with version "`GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)"

**Comment by BitencourtJr** [comment] 2024-04-10 16:55
I have the same problem. I do not know what to do

**Comment by dibarbet** [comment] 2024-04-10 18:34
When did this issue start?  We haven't uploaded a new extension version this week - was there by a chance a system update recently?

**Comment by sethwenzel** [comment] 2024-04-10 19:04
I am also experiencing this.  I'm working with dotnet Aspire right now, which updated to preview 5 yesterday... could this be related?

**Comment by danshryock** [comment] 2024-04-10 19:10
I noticed the issue after a combination of Ubuntu patching and updating my VSCode version using the Ubuntu App Store snap package.

I noticed that the issue seemed similar to this one:
https://github.com/microsoft/vscode/issues/168427

Since the recommendation there was to uninstall the snap package, and install the package (code-tunnel in that case) directly, I decided to try the same with the VSCode.  I uninstalled the snap package, manually downloaded the .deb file from https://code.visualstudio.com/Download and manually installed it with 
`sudo apt install ./code_1.88.0-1712152114_amd64.deb`.

This seems to have resolved this issue for me.

**Comment by BitencourtJr** [comment] 2024-04-10 19:16
I also update yesterday. 

> Eu também estou vivenciando isso. Estou trabalhando com o dotnet Aspire agora, que foi atualizado para a visualização 5 ontem... isso pode estar relacionado?

I also update yesterday.

**Comment by dibarbet** [comment] 2024-04-10 19:22
> I noticed the issue after a combination of Ubuntu patching and updating my VSCode version using the Ubuntu App Store snap package.
> 
> I noticed that the issue seemed similar to this one: [microsoft/vscode#168427](https://github.com/microsoft/vscode/issues/168427)
> 
> Since the recommendation there was to uninstall the snap package, and install the package (code-tunnel in that case) directly, I decided to try the same with the VSCode. I uninstalled the snap package, manually downloaded the .deb file from https://code.visualstudio.com/Download and manually installed it with `sudo apt install ./code_1.88.0-1712152114_amd64.deb`.
> 
> This seems to have resolved this issue for me.

Thanks for the info - I can confirm this.  Using the non-snap version of VSCode should work.  This doesn't appear to be directly related to the extension

**Comment by dibarbet** [comment] 2024-04-10 19:23
Full stack of the error
```
[Error - 12:20:18 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
	at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
	at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
	at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/binding.js:9:1)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/backend.js:18:19)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/index.js:21:17)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
	at 884 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1301229)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 7974 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290437)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 5175 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290103)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 3843 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:323341)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 4054 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:335524)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8746 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:312316)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 9972 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1194711)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at 8902 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1196784)
	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1450511
	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451450
	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451489)
	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
	at Module.load (node:internal/modules/cjs/loader:1126:32)
	at Module._load (node:internal/modules/cjs/loader:967:12)
	at c._load (node:electron/js2c/node_init:2:13672)
	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
	at Module.require (node:internal/modules/cjs/loader:1150:19)
	at require (node:internal/modules/cjs/helpers:119:18)
	at Function.i [as __$__nodeRequire] (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:5:98)
	at m.xb (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:30898)
	at async Promise.all (index 0)
```

**Comment by BitencourtJr** [comment] 2024-04-10 19:25
> Pilha completa do erro
> 
> ```
> [Error - 12:20:18 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
> Error: /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libstdc++.so.6)
> 	at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
> 	at Module._extensions..node (node:internal/modules/cjs/loader:1356:18)
> 	at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
> 	at Module.load (node:internal/modules/cjs/loader:1126:32)
> 	at Module._load (node:internal/modules/cjs/loader:967:12)
> 	at c._load (node:electron/js2c/node_init:2:13672)
> 	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
> 	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
> 	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
> 	at Module.require (node:internal/modules/cjs/loader:1150:19)
> 	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
> 	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/binding.js:9:1)
> 	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
> 	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> 	at Module.load (node:internal/modules/cjs/loader:1126:32)
> 	at Module._load (node:internal/modules/cjs/loader:967:12)
> 	at c._load (node:electron/js2c/node_init:2:13672)
> 	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
> 	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
> 	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
> 	at Module.require (node:internal/modules/cjs/loader:1150:19)
> 	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
> 	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/backend.js:18:19)
> 	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
> 	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> 	at Module.load (node:internal/modules/cjs/loader:1126:32)
> 	at Module._load (node:internal/modules/cjs/loader:967:12)
> 	at c._load (node:electron/js2c/node_init:2:13672)
> 	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
> 	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
> 	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
> 	at Module.require (node:internal/modules/cjs/loader:1150:19)
> 	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
> 	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/node_modules/onnxruntime-node/dist/index.js:21:17)
> 	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
> 	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> 	at Module.load (node:internal/modules/cjs/loader:1126:32)
> 	at Module._load (node:internal/modules/cjs/loader:967:12)
> 	at c._load (node:electron/js2c/node_init:2:13672)
> 	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
> 	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
> 	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
> 	at Module.require (node:internal/modules/cjs/loader:1150:19)
> 	at h (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:647)
> 	at 884 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1301229)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 7974 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290437)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 5175 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:290103)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 3843 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:323341)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 4054 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:335524)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 8746 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:312316)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 9972 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1194711)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at 8902 (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1196784)
> 	at __webpack_require__ (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1449676)
> 	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1450511
> 	at /home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451450
> 	at Object.<anonymous> (/home/dibarbet/.vscode/extensions/ms-dotnettools.vscodeintellicode-csharp-2.0.25-linux-x64/dist/extension.js:2:1451489)
> 	at o._compile (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:4:1271)
> 	at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
> 	at Module.load (node:internal/modules/cjs/loader:1126:32)
> 	at Module._load (node:internal/modules/cjs/loader:967:12)
> 	at c._load (node:electron/js2c/node_init:2:13672)
> 	at l._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
> 	at i._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
> 	at t._load (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
> 	at Module.require (node:internal/modules/cjs/loader:1150:19)
> 	at require (node:internal/modules/cjs/helpers:119:18)
> 	at Function.i [as __$__nodeRequire] (/snap/code/156/usr/share/code/resources/app/out/vs/loader.js:5:98)
> 	at m.xb (/snap/code/156/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:30898)
> 	at async Promise.all (index 0)
> ```

So do you suggest installing visual studio code again?

**Comment by 333fred** [comment] 2024-04-10 19:30
> So do you suggest installing visual studio code again?

The workaround right now seems to be installing vscode as a `.deb` package, not from the snap store, yes.

**Comment by dibarbet** [comment] 2024-04-10 19:42
Another workaround appears to be to disable the 'IntelliCode for C# Dev Kit' extension.

**Comment by dibarbet** [comment] 2024-04-10 23:32
Closing this issue as external, the failure is happening while activating the IntelliCode extension (and can be tracked here - https://github.com/MicrosoftDocs/intellicode/issues/552).

Either of the following workarounds should work
1.  Use a manually installed `.deb` package version of VSCode instead of one installed by snap as described above.
2.  Disable the 'IntelliCode for C# Dev Kit' extension (id: `ms-dotnettools.vscodeintellicode-csharp`)

Additionally, in the next C# extension prerelease update we'll be adding functionality to gracefully handle IntelliCode activation failures so the C# extension can continue to function without it, see https://github.com/dotnet/vscode-csharp/pull/7037

**Closed by dibarbet** 2024-04-10 23:32 UTC
Labels: Needs Investigation
