### ISSUE TITLE
Cannot "Go to definition" inside a definition

### ISSUE THREAD

**Issue by Kiechlus** [dotnet/vscode-csharp#6021] opened 2023-08-03 21:44 UTC
## Steps to reproduce

1. Disable Omnisharp and use the new LSP Server
2. Go to definition (CTRL+Click) of any class/interface that is not from the same codebase
3. Try to go to definition of something in this definition
<img src="https://github.com/dotnet/vscode-csharp/assets/9875731/1584a813-ea4f-4388-b47e-1e36a5631e31" width=60% height=60%>

## Expected  behavior
Should be able to go arbitrary deep into definitions. This works as soon as Omnisharp is enabled again.

## Actual behavior
Doesn't do anything.

## Additional context
Tried both with and withoug C# Dev Kit installed.

**Comment by eduardoscheffer** [comment] 2023-08-03 22:53
Use v1.26.0. There is a bug on version 2

**Comment by eduardoscheffer** [comment] 2023-08-03 22:55
![csharp-extension-bug](https://github.com/dotnet/vscode-csharp/assets/107814795/eeb89e3e-e5de-4d1c-abae-c342aa7c05e2)
 try that

**Comment by dibarbet** [comment] 2023-08-04 01:23
Likely related to https://github.com/dotnet/vscode-csharp/issues/5787

**Comment by dafeng** [comment] 2023-08-04 01:30
Please try to disable the C# dev kit

**Comment by zion** [comment] 2023-08-11 15:57
Had the same issue, reverting to 1.26.0 worked for me. 

For anyone that isnt aware... you can set a specific version of an extension by clicking the gear icon in the extension list and clicking "install another version..."

**Comment by dibarbet** [comment] 2023-09-13 19:01
Closing as duplicate of https://github.com/dotnet/vscode-csharp/issues/5787 - once that issue is resolved various language features (incl go to definition) should work better in decompiled / metadata files.

**Closed by dibarbet** 2023-09-13 19:01 UTC
Labels: Bug, Triaged

**Comment by abdulazeez761** [comment] 2024-09-08 21:10
It's late, but I'm sure someone out there is struggling with this. Anyway, what worked for me and could work for you as well was installing an older version of the C# Dev Kit. Both the C# extension and the C# Dev Kit support 'Go to Definition,' and when you try to use the C# OmniSharp server, it won’t use the C# Dev Kit by default. The solution is to install a version of the C# Dev Kit that doesn’t conflict with other extensions. I guess they’ve been working on it, so it should be fixed soon.

the version that worked as expected for me was 1.9.55v
![image](https://github.com/user-attachments/assets/299c8fc3-6bcb-457c-8df5-b389292d45f0)
![image](https://github.com/user-attachments/assets/1dd813d6-490f-4660-97e1-b7beb2ae27d3)
![image](https://github.com/user-attachments/assets/41b2853a-b8df-43e5-b34d-bd27b275c13c)
![image](https://github.com/user-attachments/assets/e4cf86f5-6711-44da-94db-02b3a7e63d98)
