### ISSUE TITLE
C# request textdocument/inlayhint failed. 

### ISSUE THREAD

**Issue by Branislav84** [dotnet/vscode-csharp#7303] opened 2024-07-02 18:45 UTC
Error message appears when I go to File/New Text File and when I change Plain Text to C#

C# Dev Kit was installed via WSL (Ubuntu) also Net. SDK was installed both on Windows and Ubuntu (WSL)

Output shows:

Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/442ee311.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 8:43:26 PM] [Program] Language server initialized
[Error - 8:43:26 PM] Request textDocument/codeAction failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/inlayHint failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/diagnostic failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Document pull failed for text document untitled:Untitled-1
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]
[Error - 8:43:26 PM] Request textDocument/codeAction failed.
  Message: Unsupported extension '' and LSP language id ''
  Code: -32000 
[object Object]

**Comment by dibarbet** [comment] 2024-07-09 07:00
duplicate of https://github.com/dotnet/vscode-csharp/issues/6973

**Closed by dibarbet** 2024-07-09 07:00 UTC
Labels: Resolved-Duplicate, Triaged
