### ISSUE TITLE
Add feature for collapsing to definitions withing a C# file

### ISSUE THREAD

**Issue by tugberkugurlu** [dotnet/vscode-csharp#533] opened 2016-07-07 10:29 UTC
I am not sure whether this exists but I am basically looking for doing `CTRL+M, CTRL+O` withing the editor and collapse all to definitions within a C# file.

**Comment by JoeRobich** [comment] 2024-09-13 02:58
This would need to be implemented by VS Code itself. Is a duplicate of https://github.com/microsoft/vscode/issues/158000

**Closed by JoeRobich** 2024-09-13 02:58 UTC
Labels: Feature Request, OmniSharp, Editor-Code Folding
