### ISSUE TITLE
Make new VS code Extension based on this one

### ISSUE THREAD

**Issue by arunchndr** [dotnet/vscode-csharp#6952] opened 2024-03-06 18:07 UTC
From vscode-dotnettools created by [pieroflacco](https://github.com/pieroflacco): microsoft/vscode-dotnettools#973  

### Describe the feature you'd like

Hi,

I'm building my own VsCode Extension and I would like to know if it is possible to programmatically use language server features provided by the c# Devkit.
In particular I need to parse a c# file and get informations about classes and methods contained in it. I also need to write some code (practically a simple method) at a given position in the file in respect to other methods.

Is there anyting in c#DevKit I can usa? Is there any documentation in regard?

Thanks for considering my request.
cheers

**Comment by arkalyanms** [comment] 2024-03-06 18:08
This ties to our extensibility plans. We are current atleast a few sprints out before we get resourcing to come back to it. We will kepe this issue posted when we know more specific timelines and have a working sample.

**Comment by dibarbet** [comment] 2024-12-05 01:45
closing as dupe of https://github.com/dotnet/roslyn/issues/68696

**Closed by dibarbet** 2024-12-05 01:45 UTC
Labels: Extensibility
