### ISSUE TITLE
the built in tool doesn't work -- too much data to post to github

### ISSUE THREAD

**Issue by cicorias** [dotnet/vscode-csharp#6240] opened 2023-08-28 15:13 UTC
the "report an issue tool" fails and is not very useful. This is before putting in any extra content.

![image](https://github.com/dotnet/vscode-csharp/assets/1080406/e435f179-d174-4af8-8116-b773f0d6533d)

**Comment by dibarbet** [comment] 2023-08-30 22:34
Hmm.  That is unexpected since we usually don't include logs automatically.  @cicorias, can you share what gets added to your clipboard when you hit this error?  Need to figure out what is producing it.

**Comment by dibarbet** [comment] 2023-10-19 00:15
Closing, we do not have enough info to reproduce this.

**Closed by dibarbet** 2023-10-19 00:15 UTC
Labels: Bug, Needs More Info, Triaged
