### ISSUE TITLE
Issue with syntax highlighting and navigation on update.

### ISSUE THREAD

**Issue by Jenni-Vibert** [dotnet/vscode-csharp#6802] opened 2024-01-11 14:02 UTC
Type: <b>Bug</b>

### C# log ###
<details>Post the output from Output-->C# Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
Dotnet path: /home/jenni/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.15~x64/dotnet
Activating C# standalone...
Starting server at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer
Server arguments --logLevel Trace --telemetryLevel all --extensionLogDirectory /home/jenni/.config/Code/logs/20240111T135041/window1/exthost/ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] trce: Program[0]
      .NET Runtime Version: .NET 7.0.15
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version1_X.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Language.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/jenni/.vscode/extensions/ms-dotnettools.csharp-2.15.30-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version2_X.dll added to workspace.
[stdout] {"pipeName":"/tmp/326f5e84.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 1:56:47 PM] [Program] Language server initialized
[LanguageServerHost] [01:56:47.565][Start]initialize
[LanguageServerHost] [01:56:47.846][End]initialize
[LanguageServerHost] [01:56:47.869][Start]initialized
[LanguageServerHost] [01:56:48.049][End]initialized
[LanguageServerHost] [01:56:48.092][Start]workspace/diagnostic
[LanguageServerHost] [01:56:48.093][Start]solution/open
[Info  - 1:56:48 PM] [LanguageServerProjectSystem] Loading /home/jenni/Documents/Portal/je.code.tuesday/je.code.tuesday.sln...
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[BuildHost PID 7638] Message from Process: Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
[BuildHost PID 7638] Message from Process: File name: 'System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
[BuildHost PID 7638] Message from Process:    at Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program.Main(String[] args)
[BuildHost PID 7638] Message from Process:    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
[BuildHost PID 7638] Message from Process:    at Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program.Main(String[] args)
[BuildHost PID 7638] Message from Process:    at Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.Program.<Main>(String[] args)
[BuildHost PID 7638] Process shut down.
[Error - 1:56:49 PM] [LanguageServerHost] System.Exception: The server disconnected unexpectedly.
   at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.InvokeCoreAsync(Int32 targetObject, String methodName, List`1 parameters, Type expectedReturnType, CancellationToken cancellationToken) in /_/src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:line 148
   at Microsoft.CodeAnalysis.MSBuild.Rpc.RpcClient.InvokeAsync[T](Int32 targetObject, String methodName, List`1 parameters, CancellationToken cancellationToken) in /_/src/Workspaces/Core/MSBuild/Rpc/RpcClient.cs:line 114
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 103
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 116
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 146
[LanguageServerHost] [01:56:49.540][End]solution/open</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.15.30
**Using OmniSharp**: false

Issue with syntax highlighting and navigation started today when updating to 2.15.30.
Rolling back to 2.14.8 only partially solved the issue.
Issue remains after updating back to 2.15.30, restarting VSCode, restarting laptop etc.

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.15
  Architecture: x64
  Commit:       8f4568cdaa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.15 [/home/jenni/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.15~x64/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|aspnet-helper|schneiderpat|0.6.4|schneiderpat.aspnet-helper-0.6.4|
|atlascode|atlassian|3.0.9|atlassian.atlascode-3.0.9|
|auto-save|mcright|1.0.3|mcright.auto-save-1.0.3|
|better-cpp-syntax|jeff-hykin|1.17.2|jeff-hykin.better-cpp-syntax-1.17.2|
|cloudcode|googlecloudtools|2.2.1|googlecloudtools.cloudcode-2.2.1|
|code-settings-sync|Shan|3.4.3|shan.code-settings-sync-3.4.3|
|csharp|ms-dotnettools|2.15.30|ms-dotnettools.csharp-2.15.30-linux-x64|
|csharp-auto-formatter|bilal-arikan|0.1.0|bilal-arikan.csharp-auto-formatter-0.1.0|
|csharpsortusings|jongrant|0.0.6|jongrant.csharpsortusings-0.0.6|
|gitlens|eamodio|14.6.1|eamodio.gitlens-14.6.1|
|indented-block-highlighting|byi8220|1.0.7|byi8220.indented-block-highlighting-1.0.7|
|razor-plus|austincummings|0.1.4|austincummings.razor-plus-0.1.4|
|remote-containers|ms-vscode-remote|0.327.0|ms-vscode-remote.remote-containers-0.327.0|
|trailing-spaces|shardulm94|0.4.1|shardulm94.trailing-spaces-0.4.1|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vsliveshare|ms-vsliveshare|1.0.5900|ms-vsliveshare.vsliveshare-1.0.5900|
|vsliveshare-audio|ms-vsliveshare|0.1.93|ms-vsliveshare.vsliveshare-audio-0.1.93|;

</details>

Extension version: 2.15.30
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:47:11.635Z)
OS version: Linux x64 6.5.0-14-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.36GB (10.45GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9a0329fd-e0f5-45d3-8cab-e5544267f7e0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30933248
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2cf:30928864
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019a:30933241

```

</details>

**Comment by dibarbet** [comment] 2024-01-11 21:12
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6801

See https://github.com/dotnet/vscode-csharp/issues/6801#issuecomment-1887954275 for a workaround for 2.15.

**Closed** 2024-01-11 21:12 UTC
