### ISSUE TITLE
auto format cannot auto-indent dynamic object

### ISSUE THREAD

**Issue by duongphuhiep** [dotnet/vscode-csharp#2588] opened 2018-10-07 08:33 UTC
Issue Type: <b>Bug</b>

Auto-formating doesn't work on this codes
```
var response = new {
    dataset = new [] {
        new {
            records = new[] {
                new {
                    svrIp = "192.168.200.13",
                    dbName = "mb_dev_hiep",
                    message = "1 row(s) affected",
                }
            }
        }
    }
};
```

Extension version: 1.16.1
VS Code version: Code 1.27.2 (f46c4c469d6e6d8c46f268d1553c5dc4b475840f, 2018-09-12T07:11:15.873Z)
OS version: Linux x64 4.4.0-137-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3397)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.56GB (4.89GB free)|
|Process Argv|/usr/share/code/code --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by JoeRobich** [comment] 2024-11-11 22:55
The Roslyn formatter does not format initializers. Closing as by design.

**Closed by JoeRobich** 2024-11-11 22:55 UTC
Labels: Bug, OmniSharp
