### ISSUE TITLE
Error on opening project

### ISSUE THREAD

**Issue by james-white-x** [dotnet/vscode-csharp#6224] opened 2023-08-25 10:19 UTC
Type: <b>Bug</b>

## Issue Description ##
I opened the project and got and error. It said to report to you.

## Logs ##
=====================
8/25/2023 1:17:54 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Workspace update handler ActionBlockSlimAsync`1' closed because of an exception: Invalid URI: The format of the URI could not be determined.. (Invalid URI: The format of the URI could not be determined.)
---> (Inner Exception #0) StreamJsonRpc.RemoteInvocationException: Invalid URI: The format of the URI could not be determined.
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass45_1`1.<<OnProjectChangedAsync>g__ApplyInBatchAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.OnBuildUpdateAsync(IProjectVersionedValue`1 update)
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>g__ApplyUpdateWithinLockAsync|1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.ProjectSystem.VSCode.LanguageServices.Workspace.<>c__DisplayClass41_0.<<OnWorkspaceUpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.<>c__DisplayClass3_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.VisualStudio.Threading.ReentrantSemaphore.StackSemaphore.ExecuteAsync(Func`1 operation, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.OnceInitializedOnceDisposedUnderLockAsync.ExecuteUnderLockCoreAsync(Func`2 action, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>
        
### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.81.1
**C# Extension**: 2.0.413
**Using OmniSharp**: true

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.413 [/usr/share/dotnet/sdk]
  7.0.400 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|aspnetcorerazor-html-css-class-completion|kevin-chatham|1.0.3|kevin-chatham.aspnetcorerazor-html-css-class-completion-1.0.3|
|csdevkit|ms-dotnettools|0.3.21|ms-dotnettools.csdevkit-0.3.21-linux-x64|
|csharp|ms-dotnettools|2.0.413|ms-dotnettools.csharp-2.0.413-linux-x64|
|dotnet|leo-labs|1.3.0|leo-labs.dotnet-1.3.0|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|gitflow|vector-of-bool|1.2.1|vector-of-bool.gitflow-1.2.1|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|gitlens|eamodio|14.2.1|eamodio.gitlens-14.2.1|
|mongodb-vscode|mongodb|1.2.1|mongodb.mongodb-vscode-1.2.1|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|sass-indented|syler|1.8.27|syler.sass-indented-1.8.27|
|svg|jock|1.5.3|jock.svg-1.5.3|
|vscode-color-picker|AntiAntiSepticeye|0.0.4|antiantisepticeye.vscode-color-picker-0.0.4|
|vscode-dotnet-pack|ms-dotnettools|1.0.12|ms-dotnettools.vscode-dotnet-pack-1.0.12|
|vscode-dotnet-runtime|ms-dotnettools|1.7.0|ms-dotnettools.vscode-dotnet-runtime-1.7.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-html-css|ecmel|1.13.1|ecmel.vscode-html-css-1.13.1|
|vscode-import-cost|wix|3.3.0|wix.vscode-import-cost-3.3.0|
|vscode-lottie|lottiefiles|1.0.5|lottiefiles.vscode-lottie-1.0.5|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscode-pylance|ms-python|2023.8.40|ms-python.vscode-pylance-2023.8.40|
|vscode-react-native|msjsdiag|1.11.2|msjsdiag.vscode-react-native-1.11.2|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-linux-x64|;

</details>

Extension version: 2.0.413
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (2.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/james/repos/IdentityApp --remote=wsl+Ubuntu --crash-reporter-id f28b5a18-e7d9-4c97-873a-6695beca75bd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|Memory (System)|11.68GB (9.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
vscccc:30803845
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
7ij38806:30736111
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by TCROC** [comment] 2023-08-25 20:27
I'm going to paste my comment here as well.  I'm not really sure which repo this should be commented on, but here is my comment from the other thread:

> Downgrading the C# extension from 2.0.413 to previous version 2.0.376 fixes this error for me
> ^ @christianfosli

I can confirm, downgrading worked for me. I'm currently trying to open a Unity Project in Pop OS (an Ubuntu derivative).

Looks like it was also reported here:

https://github.com/dotnet/vscode-csharp/issues/6224

And 2 weeks ago here:

https://github.com/microsoft/vscode-dotnettools/issues/361

So maybe a regression?

**Comment by jasonmalinowski** [comment] 2023-08-25 23:25
This is fixed by https://github.com/dotnet/vscode-csharp/pull/6231. We plan to ship the fix on Monday, but in the mean time you can work around it by setting the VS Code settign dotnet.dotnetPath to an absolute path containing dotnet.exe. Or downgrade to v2.0.376 since yes this was regressed in v2.0.399 or later.

**Closed by jasonmalinowski** 2023-08-25 23:25 UTC
