### ISSUE TITLE
Fluent c# format document

### ISSUE THREAD

**Issue by JavierMarcuzzi** [dotnet/vscode-csharp#7050] opened 2024-04-15 14:13 UTC
## Markup 
CommunityToolkit.Maui.Markup use fluent, but the format document option doesn't accommodate the code, it would be nice that it accommodates as in pure c#.

## Describe the solution you would like
Work as pure c#.

## Applicable Scenarios
Net maui?

**Comment by dibarbet** [comment] 2024-04-16 19:31
Format document should respect an .editorconfig, where you can configure how formatting behaves.  See https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0055

If something is not working, please provide an example of the original code, how it gets formatted, your editorconfig, and how you expect it to be formatted.

**Comment by JavierMarcuzzi** [comment] 2024-04-17 14:56
Thank you very much, but I don't have the knowledge to perform at that level of configuration. I use the options without touching the settings.

About an example, it can be this original, from https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/markup/markup

using static CommunityToolkit.Maui.Markup.GridRowsColumns;

class SampleContentPage : ContentPage
{
    public SampleContentPage()
    {
        Content = new Grid
        {
            RowDefinitions = Rows.Define(
                (Row.TextEntry, 36)),

            ColumnDefinitions = Columns.Define(
                (Column.Description, Star),
                (Column.Input, Stars(2))),

            Children =
            {
                new Label()
                    .Text("Code:")
                    .Row(Row.TextEntry).Column(Column.Description),

                new Entry
                {
                    Keyboard = Keyboard.Numeric,
                }.Row(Row.TextEntry).Column(Column.Input)
                 .BackgroundColor(Colors.AliceBlue)
                 .FontSize(15)
                 .Placeholder("Enter number")
                 .TextColor(Colors.Black)
                 .Height(44)
                 .Margin(5, 5)
                 .Bind(Entry.TextProperty, static (ViewModel vm) => vm.RegistrationCode, static (ViewModel vm, string text) => vm.RegistrationCode = text)
            }
        };
    }

    enum Row { TextEntry }
    enum Column { Description, Input }
}

**Comment by dibarbet** [comment] 2024-05-07 23:53
I'm not able to reproduce any issues with the above code in a Maui app - pasted in from the sample 'Format Document' leaves the formatting as-is which is generally what I would expect.

Would you mind sharing a before / after screenshot?  Or are you expecting that format document does something else, and if so what?

**Comment by dibarbet** [comment] 2024-09-05 00:27
Closing, not actionable without the requested information.  If you're able to provide it, please re-open the issue with the additional information.

**Closed by dibarbet** 2024-09-05 00:27 UTC
Labels: Needs More Info
