### ISSUE TITLE
cannot continue decompile type in decompiled code

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/vscode-csharp#6733] opened 2023-12-09 14:41 UTC
I see that the omnisharp 1.26 version can do this, but this 2.x.x version cannot do it, which is annoying. For example, it will show green in PinnedScript and can continue decompile.
1.2.6
![image](https://github.com/dotnet/vscode-csharp/assets/126905141/232ec037-5cbc-443d-b0a3-a851a48626ba)
newest 2.x.x
![image](https://github.com/dotnet/vscode-csharp/assets/126905141/e4c04bbc-2a3a-4e63-ab01-8cf34ee545c8)

**Comment by dibarbet** [comment] 2023-12-11 21:07
Believe this should be a duplicate of https://github.com/dotnet/vscode-csharp/issues/5787

**Closed by dibarbet** 2023-12-11 21:07 UTC
