### ISSUE TITLE
Do not remove indentation spaces on New Line

### ISSUE THREAD

**Issue by bernd4** [dotnet/vscode-csharp#5859] opened 2023-06-25 10:55 UTC
## Issue Description ##
In a .cs file
- when entering a new line in a method
- then executing "format document"
- The spaces used for indentation are removed

## Steps to Reproduce ##
- see previous

## Expected Behavior ##
- Do not remove automatically inserted spaces for having a nice indentation.
- Like in the regular Visual Studio (not VSCode)

public void TestMethod() {
....var x = "";
....here there is indentation
}

## Actual Behavior ##
- The spaces are removed

public void TestMethod() {
....var x = "";
here there is NO indentation
}

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.79.2
**C# Extension**: 1.26.0

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-repos|ms-vscode|0.34.0|
|csharp|ms-dotnettools|1.26.0|
|csharpextensions|kreativ-software|1.7.3|
|EditorConfig|EditorConfig|0.16.4|
|LiveServer|ritwickdey|5.7.9|
|material-icon-theme|PKief|4.28.0|
|ng-template|Angular|16.0.0|
|python|ms-python|2023.10.1|
|remote-repositories|ms-vscode|0.36.0|
|remotehub|GitHub|0.58.0|
|vscode-html-css|ecmel|1.13.1|
|vscode-pylance|ms-python|2023.6.30|
|vsliveshare|ms-vsliveshare|1.0.5873|;

</details>

**Comment by JoeRobich** [comment] 2023-06-26 17:38
Duplicate of #1980. Would need https://github.com/microsoft/vscode/issues/13960 to match expected VS behavior.

**Closed** 2023-06-26 17:38 UTC
Labels: Resolved-Duplicate
