### ISSUE TITLE
Error with project files not finding objects or razor tags

### ISSUE THREAD

**Issue by craiggodfrey** [dotnet/vscode-csharp#6852] opened 2024-02-02 23:51 UTC
Type: <b>Bug</b>

When opening files, whether .cs or .razor, the file gets a lot of red error lines and says it cannot find the object even though they are part of the project. If I go through and open every file, then the red error lines go away. 

Extension version: 2.0.1
VS Code version: Code 1.85.2 (Universal) (8b3775030ed1a69b13e4f4c628c612102e30a681, 2024-01-18T06:40:32.531Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.72GB free)|
|Process Argv|--crash-reporter-id c0c8aad0-cf61-4da4-9ae7-38e376327f4a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30951796
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019b:30953937
3ef8e399:30949928

```

</details>

**Comment by dibarbet** [comment] 2024-02-07 21:37
Can you provide some more information?
1.  C# extension version and if you're using devkit
2.  the logs from the 'C#' output window
3.  some of the exact error messages you're seeing (screenshots are always useful)

**Comment by craiggodfrey** [comment] 2024-02-07 21:51
[A screen shot of a computer  Description automatically generated]

[A screenshot of a computer  Description automatically generated]

[A screenshot of a computer  Description automatically generated]

When I click on each file in the project, these error and warning squiggly lines go away, and the red project file names change to white. As I click through the project files, I get more and more of these squiggly lines, until I click through all of the files then they go away.

C# extension version: v2.15.30
C# devkit version: v1.3.10
IntelliCode for C# devkit version: v0.1.26

I don’t know where the logs are. There isn’t anything in the output tab.

From: David Barbet ***@***.***>
Date: Wednesday, February 7, 2024 at 3:38 PM
To: dotnet/vscode-csharp ***@***.***>
Cc: Craig Godfrey ***@***.***>, Author ***@***.***>
Subject: Re: [dotnet/vscode-csharp] Error with project files not finding objects or razor tags (Issue #6852)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Can you provide some more information?

  1.  C# extension version and if you're using devkit
  2.  the logs from the 'C#' output window
  3.  some of the exact error messages you're seeing (screenshots are always useful)

**Comment by craiggodfrey** [comment] 2024-02-07 21:53
Also, this only happens when I reopen the project, or if I open the project in visual studios then go back to vscode.

From: Craig Godfrey ***@***.***>
Date: Wednesday, February 7, 2024 at 3:50 PM
To: dotnet/vscode-csharp ***@***.***>, dotnet/vscode-csharp ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [dotnet/vscode-csharp] Error with project files not finding objects or razor tags (Issue #6852)
[A screen shot of a computer  Description automatically generated]

[A screenshot of a computer  Description automatically generated]

[A screenshot of a computer  Description automatically generated]

When I click on each file in the project, these error and warning squiggly lines go away, and the red project file names change to white. As I click through the project files, I get more and more of these squiggly lines, until I click through all of the files then they go away.

C# extension version: v2.15.30
C# devkit version: v1.3.10
IntelliCode for C# devkit version: v0.1.26

I don’t know where the logs are. There isn’t anything in the output tab.

From: David Barbet ***@***.***>
Date: Wednesday, February 7, 2024 at 3:38 PM
To: dotnet/vscode-csharp ***@***.***>
Cc: Craig Godfrey ***@***.***>, Author ***@***.***>
Subject: Re: [dotnet/vscode-csharp] Error with project files not finding objects or razor tags (Issue #6852)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Can you provide some more information?

  1.  C# extension version and if you're using devkit
  2.  the logs from the 'C#' output window
  3.  some of the exact error messages you're seeing (screenshots are always useful)

**Comment by dibarbet** [comment] 2024-02-23 21:44
@davidwengier - any known problems with re-using incorrect build assets (or mismatch in build assets) between VS and vscode for Razor files?

**Comment by davidwengier** [comment] 2024-02-26 04:43
Been a few reports recently it seems, like https://github.com/dotnet/vscode-csharp/issues/6921 even, where maybe our closed file stuff has changed. We could easily be broken by a change to Roslyn here too, so might not be something we're aware of. Will put this in triage.

**Comment by Filaton** [comment] 2024-03-15 17:46
I also opened my project with Visual Studio one time and since then the issue persists. Tried clean, rebuild, etc. But even deleting and cloning again doesn't fix it.

When opening it in the WSL it works perfectly fine.

**Comment by alexchiraples** [comment] 2024-03-18 14:51
Hi! 

I had downgraded C# extension from v2.22.3 to v2.18.16, seems to be working now. I had similar issues but only for .razor files and in Program.cs.
Current extension list:
C#: v2.18.16
C# Dev Kit: v1.4.29

I will post update it starts reproducing again.
Program.cs showed one errror for App.razor, it did not recognized the generated class
![image](https://github.com/dotnet/vscode-csharp/assets/22675415/ea933c78-0ea7-42b1-841c-ff1a158a5ba6)
I've fixed this issue by adding code behind and partial class for App.razor

` ``
public partial class App : ComponentBase
{
        
}
```

**Comment by ThisIsPedroMoreira** [comment] 2024-04-03 11:55
I have this error too. Any update on this? @davidwengier

**Comment by dibarbet** [comment] 2024-07-24 00:39
There have been a number of fixes and improvements to related features.  Please let me know if you're still having issues on 2.39.29 (release)

**Comment by ThisIsPedroMoreira** [comment] 2024-07-25 10:23
Yes, I still have the issue

**Comment by Filaton** [comment] 2024-07-25 10:25
> There have been a number of fixes and improvements to related features.  Please let me know if you're still having issues on 2.39.29 (release)

In my case it resolved when I disabled my CMake extension.

**Comment by ryzngard** [comment] 2024-08-14 18:48
@ThisIsPedroMoreira can you provide more info? I believe the only known issue now is with large apps and tracked with https://github.com/dotnet/vscode-csharp/issues/6921

**Comment by ryzngard** [comment] 2024-10-09 00:19
I'm going to close this for now. If you hit this issue after `v2.50.25` please file a new issue.

**Closed by ryzngard** 2024-10-09 00:19 UTC
Labels: Razor, needs-more-info
