### ISSUE TITLE
Do not prioritize Copilot fixers over real fixes

### ISSUE THREAD

**Issue by 333fred** [dotnet/vscode-csharp#5894] opened 2023-07-05 23:15 UTC
Type: <b>Bug</b>

I'm on the prerelease version of Copilot (v1.95.239), and I'm seeing that for things like unused usings, the copilot fixer is being prioritized over the real C# fixer for the problem. This is rather annoying, as the real fixer requires no thought and instantly works.

![Image showing Copilot fixers being prioritized](https://github.com/dotnet/vscode-csharp/assets/2371880/96a62667-21d5-40cb-9930-fba359816a02)

Extension version: 2.0.263-g4845f4f265
VS Code version: Code - Insiders 1.80.0-insider (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T10:58:02.000Z)
OS version: Linux x64 5.15.0-75-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|62.70GB (18.01GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 9e8cf102-e785-4922-93ba-24ac731cf9e4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|regolith|
|XDG_CURRENT_DESKTOP|Regolith:GNOME-Flashback:GNOME|
|XDG_SESSION_DESKTOP|regolith|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30776702
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
2i9eh265:30646982
showlangstatbar:30737417
pythonms35:30671666
ecj1e332:30687743
pythonfmttext:30716741
pythoncmvfstr:30726892
fixshowwlkth:30771523
hideindicator:30766887
pythongtdpath:30726887
i26e3531:30780429
gsofa:30778558
pythonnosmt12:30779711
pythonidxpt:30768918
pythondjangots:30768917
pythonnoceb:30776497
copilotsettingt:30767686
e537b577:30772214
h0f32768:30779712
dsvsc013:30777762
dsvsc014:30777825

```

</details>

**Comment by CyrusNajmabadi** [comment] 2023-08-23 15:51
Dupe of https://github.com/microsoft/vscode-copilot-release/issues/349.

**Closed by CyrusNajmabadi** 2023-08-23 15:51 UTC
Labels: Feature Request
