### ISSUE TITLE
Wrong message "ambiguity between X and X" (which are the same)

### ISSUE THREAD

**Issue by ygoe** [dotnet/vscode-csharp#5542] opened 2023-01-18 18:10 UTC
Type: <b>Bug</b>

I'm working on a C# project for a while now and starting today, I repeatedly get the error that something would not be okay with my code. The message on the red underlined code tranlates as "Ambiguity between "MyClass.MyProperty" and "MyClass.MyProperty"". That class and property exists exactly once and shows no issue itself. The message is invalid. Rebuilding the code (Ctrl+Shift+B) does not resolve the error. Reloading the window does resolve it.

I can't show you the code. It's too much in its entirety and even just loading it would not reproduce, you have to actually edit it a lot to see the problem. You never know when it's going to happen. But I've had this 2 or 3 times within the last hour in different places. I assume you have your own projects to try this. My project type is .NET 7 for the Web SDK, but it's only a Web API, so no dangerous* file types like Razor, JavaScript or HTML. (* causing loads of problems on their own)

Somehow the source code analyser gets confused with an increasing size of code. It's already slightly overwhelmed with small code, when it shows errors that are not really there. Making *any* change to the document, or even just saving it to disk (Ctrl+S) immediately resolve such errors or warnings. It looks like the analyser is making a decision what messages to show, while I'm editing my code again (pressing another key) and then ignores my latest edit while it was busy. But only the last input resolved the warnings (previous text was incomplete, leading to the warnings/errors). It cannot keep up with normal typing speed.

It gets more and more annoying to see this code editor making so many errors. I think I'm switching back to Visual Studio as it turned out I'll have it available in this project.

Extension version: 1.25.2
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.71GB (5.92GB free)|
|Process Argv|--crash-reporter-id 1b00a758-578c-4b77-a258-fe145c18e004|
|Screen Reader|no|
|VM|29%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
pyind779cf:30647092
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by ygoe** [comment] 2023-01-22 16:24
Possible steps to reproduce: (not tried, just describing what I did immediately before the error appeared again)

1. Create a class with a field and a constructor, assigning the field in the constructor (e.g. a service with an injected `ILogger`)
2. Create a new empty .cs file
3. In the new file, type the empty definition of a new class
4. Copy the field and constructor from the first class into the second file (now the constructor name is wrong)
5. Manually correct the constructor method name to the second class name

The field cannot be used in the second class because the code analyser is confused and still thinks that we're in the old class. The field name would be defined twice which is nonsense. After reloading the window, the problem disappears.

**Comment by kd8lvt** [comment] 2023-06-15 19:06
I am also encountering this issue, with the NCalc Library - specifically the EvaluateFunction event in the Expression class. 
Diff for some code to peek at: https://github.com/kd8lvt/RimWorld-Math/commit/89070c59d8c6a156df8bf22f631692289bf14b1e#diff-249900a5f6507cd777e5382e9f42e7f28d62c512261bb4cedc1abaee8ed0d8f6
And NCalc's Expression class: https://github.com/ncalc/ncalc/blob/master/src/NCalc/Expression.cs

**Comment by enzonun** [comment] 2023-11-02 02:56
In my case this issue occurs when I open a razor pages project, the .cshtml gives me this errors "Ambiguity between X and X filea...

**Comment by Kampfmoehre** [comment] 2023-11-10 09:41
I also have this error for `.razor` files in a Blazor Server project. I can't use the C# DevKit (since I am working on a commercial project) so I have "Prefer C# Extension" checked. When I check "Use Omnisharp" and reload VS Code the error is gone, but Omnisharp has its problems with razor files (like missing autocomplete for properties and methods).
Is there anything I could provide to narrow down the cause of the problem?

**Comment by Kampfmoehre** [comment] 2023-11-15 09:54
interesting, I also have the problem where Go to definition does not work sometimes but I don't use any of the other framreworks mentioned there or in #6426 , instead I am using ASP.NET Core default DI framework.

**Comment by jasonmalinowski** [comment] 2023-11-20 23:14
@Kampfmoehre @tannmatter Indeed that issue would be a duplicate of #6426. It'll impact any use of an API that's using source generators, and Razor can be one of those in some scenarios. As best I can tell it's unrelated to the original conversation though.

**Comment by ZeroAurora** [comment] 2024-03-08 16:30
Upvoting and also hoping this get resolved (can't believe this issue has been open for one year considering it's impact on editing any Razor pages).
And I also wonder why installing the closed-sourced C# Dev Kit resolved this issue. Can C# Dev Kit impact how Rosyln works?

**Comment by JoeRobich** [comment] 2024-11-14 06:15
A lot has changed with O# code analysis since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues

**Closed by JoeRobich** 2024-11-14 06:15 UTC
Labels: OmniSharp
