### ISSUE TITLE
Can we support adding files via Links (same as Visual Studio)

### ISSUE THREAD

**Issue by deanchalk** [dotnet/vscode-csharp#7160] opened 2024-05-24 14:36 UTC
## Is your feature request related to a problem? Please describe.
I have projects that were created in Visual Studio where files were added to the project as links. For example in the project file you would have something like this:

`<Compile Include="..\caas-application-infrastructure\CaaSInfrastructureConstants.cs"><Link>caas-application-infrastructure\CaaSInfrastructureConstants.cs</Link></Compile>`

C# projects with these links work fine in Visual Studio and Jetbrains Rider IDEs, but not in VS Code with this extension

## Describe the solution you would like
I would like to be able to work on these dotnet projects in VS Code, rather than having to use a better IDE

**Comment by dibarbet** [comment] 2024-07-23 00:39
Should be duplicate of https://github.com/dotnet/vscode-csharp/issues/5788

**Closed by dibarbet** 2024-07-23 00:39 UTC
