### ISSUE TITLE
Element with id <solution> is already registered

### ISSUE THREAD

**Issue by davidfowl** [dotnet/vscode-csharp#7164] opened 2024-05-25 02:27 UTC
I get this error randomly while using devkit and it breaks the solution explorer.

<img width="1198" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/95136/1c234aa0-49a2-42e0-b09e-560757e164d6">

**Comment by davidfowl** [comment] 2024-05-25 16:37
This happens really often when navigating to different VS code windows and back to the solution view. I have some logs captured but not sure which level this error happens at.

**Comment by jasonmalinowski** [comment] 2024-05-30 00:10
@davidfowl Do you have the logs handy to look at?

**Comment by dibarbet** [comment] 2024-09-05 00:40
Issues is on the devkit side, duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1349

**Closed by dibarbet** 2024-09-05 00:40 UTC
Labels: Needs More Info
