### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by GiaiHung** [dotnet/vscode-csharp#6774] opened 2023-12-26 14:21 UTC
Type: <b>Bug</b>

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
Starting server at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --starredCompletionComponentPath c:\Users\DELL\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\components\starred-suggestions\node_modules\@vsintellicode\starred-suggestions-csharp --extension c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslynDevKit\Microsoft.VisualStudio.LanguageServices.DevKit.dll --sessionId 8d2f04ce-4382-41cd-a97e-018a7fb34b871703600251053 --telemetryLevel all --extensionLogDirectory c:\Users\DELL\AppData\Roaming\Code\logs\20231226T201357\window1\exthost\ms-dotnettools.csharp
waiting for named pipe information from server...
[stdout] trce: Program[0]
      .NET Runtime Version: .NET 8.0.0
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.ExternalAccess.AspNetCore.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.CSharp.dll added to workspace.
[stdout] dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Language.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version1_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.Compiler.Mvc.Version2_X.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\DELL\.vscode\extensions\ms-dotnettools.csharp-2.14.8-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
[stdout] {"pipeName":"\\\\.\\pipe\\088da6c1"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:17:55 PM] [Program] Language server initialized
[LanguageServerHost] [02:17:55.867][Start]initialize
[LanguageServerHost] [02:17:55.888][Start]Initialize
[LanguageServerHost] [02:17:56.360][End]Initialize
[LanguageServerHost] [02:17:56.559][End]initialize
[LanguageServerHost] [02:17:56.563][Start]initialized
[LanguageServerHost] [02:17:56.887][End]initialized
[LanguageServerHost] [02:17:56.903][Start]serviceBroker/connect
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] SameProcess proffered brokered service(s): Microsoft.VisualStudio.RemoteBrokeredServiceManifest (0.2).
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] SameProcess proffered brokered service(s): Microsoft.VisualStudio.GlobalBrokeredServiceContainer.MissingServiceDiagnostics (1.0).
[LanguageServerHost] [02:17:56.982][Start]workspace/diagnostic
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] SameProcess proffered brokered service(s): Microsoft.ServiceHub.Framework.AuthorizationService.
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] SameProcess proffered brokered service(s): Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1), Microsoft.CodeAnalysis.LanguageServer.ManagedHotReloadLanguageService (0.1), Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService.
[LanguageServerHost] Processing 0 documents
[Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.BrokeredServiceBridgeProvider] Setting up brokered service bridge
[LanguageServerHost] [02:17:57.080][End]serviceBroker/connect
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "handshake" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "requestServiceChannel" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "cancelServiceRequest" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.CancelServiceRequestAsync(Guid) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "dispose" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.Dispose() (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "handshake" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "requestServiceChannel" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "cancelServiceRequest" -> Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.CancelServiceRequestAsync(Guid) (Microsoft.ServiceHub.Framework.IpcRelayServiceBroker)
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Listening for events from Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.AvailabilityChanged to raise notification.
[BrokeredServiceTraceListener] ServiceBroker Information: 3 : 
[BrokeredServiceTraceListener] Listening started.
[BrokeredServiceTraceListener] ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener] {"id":2,"method":"handshake"}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener] Received: {"jsonrpc":"2.0","id":2,"method":"handshake","params":[{"supportedConnections":"IpcPipe","localServiceHost":{"operatingSystem":0,"processArchitecture":1,"runtime":2,"runtimeVersion":"7.0.14"}}]}
[BrokeredServiceTraceListener] ServiceBroker Information: 6 : 
[BrokeredServiceTraceListener] Received request "2" for method "handshake".
[BrokeredServiceTraceListener] ServiceBroker Information: 0 : 
[BrokeredServiceTraceListener] Added local RPC method "availabilityChanged" -> _proxy_Microsoft.ServiceHub.Framework.IRemoteServiceBroker_f669fd02-8cfb-4fd8-8f67-8f253682e9db.OnAvailabilityChanged(BrokeredServicesChangedEventArgs) (_proxy_Microsoft.ServiceHub.Framework.IRemoteServiceBroker_f669fd02-8cfb-4fd8-8f67-8f253682e9db)
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] IRemoteServiceBroker proffered from remote source: OtherProcessOnSameMachine.
[BrokeredServiceTraceListener] ServiceBroker Information: 1 : 
[BrokeredServiceTraceListener] OtherProcessOnSameMachine proffered brokered service(s): Microsoft.VisualStudio.Debugger.ManagedHotReloadService (0.1), vs-intellicode-base-models (0.1), Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1), Microsoft.CodeAnalysis.LanguageClient.SolutionSnapshotProvider (0.1).
[BrokeredServiceTraceListener] ServiceBroker Information: 3 : 
[BrokeredServiceTraceListener] Listening started.
[BrokeredServiceTraceListener] ServiceBroker Information: 9 : 
[BrokeredServiceTraceListener] Invoking Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.HandshakeAsync(ServiceBrokerClientMetadata, CancellationToken)
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] handshake
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] handshake
[BrokeredServiceTraceListener] ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener] {"id":2}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener] Sent: {"jsonrpc":"2.0","id":2,"result":null}
[BrokeredServiceTraceListener] ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener] {"id":3,"method":"requestServiceChannel"}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener] Received: {"jsonrpc":"2.0","id":3,"method":"requestServiceChannel","params":[{"name":"Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest","version":"0.1"},{"clientCulture":"en-US","clientUICulture":"en-US"}]}
[BrokeredServiceTraceListener] ServiceBroker Information: 6 : 
[BrokeredServiceTraceListener] Received request "3" for method "requestServiceChannel".
[BrokeredServiceTraceListener] ServiceBroker Information: 9 : 
[BrokeredServiceTraceListener] Invoking Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken)
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] requestServiceChannel
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9a32c3fc-5528-42f3-b510-12ccd62ecc1f
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] Requesting pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)"
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)" will be fulfilled by SameProcess
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=0609b850-405b-4e72-a594-42ff7d9fbbd2
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for "Microsoft.ServiceHub.Framework.AuthorizationService" will be fulfilled by SameProcess
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for proxy to "Microsoft.ServiceHub.Framework.AuthorizationService" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9a32c3fc-5528-42f3-b510-12ccd62ecc1f
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] Requesting pipe to "Microsoft.VisualStudio.Server.IBrokeredServiceBridgeManifest (0.1)"
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=2ce05b98-96ca-4111-a97b-dbc885c31b9a
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] requestServiceChannel
[BrokeredServiceTraceListener] ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener] {"id":3}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener] Sent: {"jsonrpc":"2.0","id":3,"result":{"requestId":"4fb50590-4068-4cda-a86d-af8557a1d278","pipeName":"7bbc626282f5432ab19b994f2f5f85a6"}}
[Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.BrokeredServiceBridgeManifest.BrokeredServiceBridgeManifest] Proffered services: Microsoft.CodeAnalysis.LanguageServer.ManagedHotReloadLanguageService (0.1),Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService
[BrokeredServiceTraceListener] ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener] {"id":4,"method":"requestServiceChannel"}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener] Received: {"jsonrpc":"2.0","id":4,"method":"requestServiceChannel","params":[{"name":"Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService"},{"clientCredentials":{},"clientCulture":"en-US","clientUICulture":"en-US"}],"traceparent":"00-a731ce9c3c8acf409300ddd520b737ff-b52578d6c6014948-00"}
[BrokeredServiceTraceListener] ServiceBroker Information: 6 : 
[BrokeredServiceTraceListener] Received request "4" for method "requestServiceChannel".
[BrokeredServiceTraceListener] ServiceBroker Information: 9 : 
[BrokeredServiceTraceListener] Invoking Microsoft.ServiceHub.Framework.IpcRelayServiceBroker.RequestServiceChannelAsync(ServiceMoniker, ServiceActivationOptions, CancellationToken)
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=7299baec-f28e-493f-99da-4205ecc48ee3
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] requestServiceChannel
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9122df82-28cf-4c78-b607-1fe79075a6c5
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] Requesting pipe to "Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService"
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for "Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService" will be fulfilled by SameProcess
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=1b009781-4e05-44f3-a416-f93d1c275cc9
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for "Microsoft.ServiceHub.Framework.AuthorizationService" will be fulfilled by SameProcess
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for proxy to "Microsoft.ServiceHub.Framework.AuthorizationService" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.ServiceHub.Framework.AuthorizationService"
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9122df82-28cf-4c78-b607-1fe79075a6c5
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=94c207b8-cc09-49ff-9a74-c68c754e0fa0
[BrokeredServiceTraceListener] ServiceBroker Start: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)"
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" will be fulfilled by OtherProcessOnSameMachine
[BrokeredServiceTraceListener] ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener] {"id":2,"method":"handshake"}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener] Sent: {"jsonrpc":"2.0","id":2,"method":"handshake","params":[{"supportedConnections":"Multiplexing, IpcPipe","localServiceHost":{"operatingSystem":0,"processArchitecture":1,"runtime":2,"runtimeVersion":"8.0.0"}}],"traceparent":"00-b807c29409ccff499a74c68c754e0fa0-45dff380813e4e45-01"}
[BrokeredServiceTraceListener] ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener] {"id":2}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener] Received: {"jsonrpc":"2.0","id":2,"result":null}
[BrokeredServiceTraceListener] ServiceBroker Information: 11 : 
[BrokeredServiceTraceListener] Received result for request "2".
[BrokeredServiceTraceListener] ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener] {"id":3,"method":"requestServiceChannel"}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener] Sent: {"jsonrpc":"2.0","id":3,"method":"requestServiceChannel","params":[{"name":"Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService","version":"0.1"},{"clientCredentials":{},"clientCulture":"en-US","clientUICulture":"en-US"}],"traceparent":"00-b807c29409ccff499a74c68c754e0fa0-fcbd9e66d9e99d46-01"}
[BrokeredServiceTraceListener] ServiceBroker Information: 7 : 
[BrokeredServiceTraceListener] {"id":3}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 7 : 
[BrokeredServiceTraceListener] Received: {"jsonrpc":"2.0","id":3,"result":{"requestId":"fd0f475b-b4b3-4161-9bd7-c184cf8aeff0","multiplexingChannelId":4}}
[BrokeredServiceTraceListener] ServiceBroker Information: 11 : 
[BrokeredServiceTraceListener] Received result for request "3".
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for proxy to "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)" is Fulfilled by OtherProcessOnSameMachine: NoExplanation.
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] Requesting proxy to "Microsoft.VisualStudio.ProjectSystem.ProjectInitializationStatusService (0.1)"
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9122df82-28cf-4c78-b607-1fe79075a6c5
[BrokeredServiceTraceListener] ServiceBroker Information: 2 : 
[BrokeredServiceTraceListener] Request for pipe to "Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService" is Fulfilled by SameProcess: NoExplanation.
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] Requesting pipe to "Microsoft.VisualStudio.LanguageServices.WorkspaceProjectFactoryService"
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=7299baec-f28e-493f-99da-4205ecc48ee3
[BrokeredServiceTraceListener] ServiceBroker Stop: 0 : 
[BrokeredServiceTraceListener] requestServiceChannel
[BrokeredServiceTraceListener] ServiceBroker Transfer: 0 : 
[BrokeredServiceTraceListener] Transfer, relatedActivityId=9cce31a7-8a3c-40cf-9300-ddd520b737ff
[BrokeredServiceTraceListener] ServiceBroker Information: 8 : 
[BrokeredServiceTraceListener] {"id":4}
[BrokeredServiceTraceListener] ServiceBroker Verbose: 8 : 
[BrokeredServiceTraceListener] Sent: {"jsonrpc":"2.0","id":4,"result":{"requestId":"92d805c2-5ff5-4778-b402-94d74583c6f8","pipeName":"ac8e0910e99148579b2443998347459e"}}
[Info  - 9:18:05 PM] [WorkspaceProjectFactoryService] Project C:\Users\DELL\CODE\.NET\Udemy API Course\3-APIBasics\1-DotnetAPI_Start\DotnetAPI.csproj loaded by C# Dev Kit
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:18:06.110][End]workspace/diagnostic
[Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.ProjectInitializationHandler] Devkit project initialization completed
[LanguageServerHost] [02:18:08.149][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents
[LanguageServerHost] Closing workspace/diagnostics request
[LanguageServerHost] Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost] [02:18:08.164][End]workspace/diagnostic
[LanguageServerHost] [02:18:10.177][Start]workspace/diagnostic
[LanguageServerHost] PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost] previousResults.Length=0
[LanguageServerHost] Processing 0 documents

No auto complete on anything using, types, keywords
Errors that don't exist like missing curly brackets
Lack of refactoring suggestions other people have. I assume no quick fixes available all the time is a not intented

Extension version: 2.14.8
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.47GB free)|
|Process Argv|--crash-reporter-id 9ffb7dc4-f4ca-41c0-a8eb-c2b68d05ab04|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
dsvsc019:30917259
cp7184t:30925682

```

</details>

**Comment by GiaiHung** [comment] 2023-12-26 14:21
No auto complete on anything using, types, keywords
Errors that don't exist like missing curly brackets
Lack of refactoring suggestions other people have. I assume no quick fixes available all the time is a not intented

**Comment by dibarbet** [comment] 2024-01-03 00:53
@GiaiHung generally those symptoms are caused by problems with the project being loaded.  From your attached logs I see

But I'm not seeing any completion requests in your logs.  Can you verify that the expected project is being loaded and it shows up in the solution explorer with all the expected files?  For example:
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/6c8ad5c2-687d-4719-9f85-5412878214a9)

Can you also attach the contents of the 'Projects' output window?

**Comment by dibarbet** [comment] 2024-03-27 22:33
Closing, this is not actionable without the additional information requested.  If you're still having issues on the latest versions of the extensions, feel free to re-open **with** the requested information.

**Closed by dibarbet** 2024-03-27 22:33 UTC
Labels: Needs More Info
