### ISSUE TITLE
Refactoring "move type to Typename.cs" now outputs the file to the root folder, rather than the folder of its current file.

### ISSUE THREAD

**Issue by Dentyr** [dotnet/vscode-csharp#6023] opened 2023-08-03 23:02 UTC
VS Code version: 1.81
C# Extension version: 2.0.320

## Steps to reproduce

1) make a folder in your project
2) make a .cs folder in that file
3) Add two types to the file, with one or either of them being different from the filename
4) Refactor "move type to Typename.cs"

## Expected  behavior
The file should be in the current folder

## Actual behavior
The output is in the root folder

## Additional context
I reinstalled 1.26.0 and it worked fine on that version.

**Comment by dibarbet** [comment] 2023-08-04 01:18
@Cosifne there might be a dupe of this already, but I couldn't find it

**Comment by M0hammad124** [comment] 2023-08-20 06:24
When new class or file adding to project the extension cannot analyze the new class or references
and intellisense also not working for the new class

**Comment by Cosifne** [comment] 2023-08-21 17:25
Fixed in https://github.com/dotnet/roslyn/pull/68995
> Also worth mentioning is that it used to open the new file in a new code window, something it doesn't do for me at least anymore.

For this issue, see https://github.com/dotnet/roslyn/issues/68550#issuecomment-1589778684

> When new class or file adding to project the extension cannot analyze the new class or references
and intellisense also not working for the new class

@M0hammad124 if possible could you set dotnet -> sever -> trace  to `Trace` and share the log under `Output -> C#` and see the log there? It would be great if you could paste it here. (It sounds like another issue, if you could give me the log I can create a new bug tracking this)

**Closed by Cosifne** 2023-08-21 17:25 UTC
Labels: Bug, Triaged

**Comment by Cosifne** [comment] 2023-08-22 22:42
> 

Hi @M0hammad124 
The log itself means that the newly added file is not recognized by the project system. Are you also using C# DevKit?

**Comment by Cosifne** [comment] 2023-08-23 02:16
> @Cosifne
> 
> [Trace.txt](https://github.com/dotnet/vscode-csharp/files/12406045/Trace.txt)
> 
> i add a new file with name 'GetCompletedEmployeeDt' and the intellisense not working in the new class and in other classes intellisense is not familiar with 'GetCompletedEmployeeDt'

Hi @M0hammad124  From the log you shared, it looks like part of your code was found by the project system and the newly added one is not. This looks like a bug and I am going to create a new issue.
