### ISSUE TITLE
Omnisharp: Enable Import Completion - Is not available in v2.0.328

### ISSUE THREAD

**Issue by BerndHme** [dotnet/vscode-csharp#6095] opened 2023-08-10 10:55 UTC
Type: <b>Bug</b>

The setting
> Omnisharp: Enable Import Completion

Is not available in v2.0.32

-----
The suggiostions do show the symbol
- but when entering (tab)
- the using statemint is not added at the top.

-----
Also for future readers.
- If you've updated the extention... en then downgrade again.
- This setting is back deactivated as its default.

-----
![image](https://github.com/dotnet/vscode-csharp/assets/132269491/1e849212-2833-4c53-a572-d22b86fa24c1)

Extension version: 1.26.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.34GB (7.27GB free)|
|Process Argv|C:\\Users\\Bernd\\Documents\\CodeProjects\\.NET Core EF\\LandenStedenTalen --crash-reporter-id 346df053-e9a5-4980-8054-b942de19a289|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
57b77579:30736110
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by ali-718** [comment] 2023-08-10 11:23
happening to me as well my vsode automatically updated it to this version and now i cant code properly

**Comment by BerndHme** [comment] 2023-08-10 12:06
@ali-718 Hi, I don't know if you know...
But you can easily downgrade via the extention page.
I'm using v1.26 until all these issues are resolved.
![image](https://github.com/dotnet/vscode-csharp/assets/132269491/79444048-12bd-4d56-be76-4a2511841a00)

**Comment by genlu** [comment] 2023-08-10 17:49
The options is now
```json
"dotnet.completion.showCompletionItemsFromUnimportedNamespaces": true
```
<img width="730" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/788783/f45b1eaf-d38f-4006-ab45-5164e5a87751">

That said, I think the issue you see is a duplicate of [this bug](https://github.com/dotnet/vscode-csharp/issues/6051) The fix will be released soon. Thanks

**Closed by genlu** 2023-08-10 17:49 UTC
