### ISSUE TITLE
Reloading extension - A element with id "<solution>" is already registered

### ISSUE THREAD

**Issue by scoizzle** [dotnet/vscode-csharp#7425] opened 2024-08-08 18:04 UTC
Type: <b>Bug</b>

## Steps to Reproduce ##
Reload extensions after installing a seperate extension update.

## Expected Behavior ##
Extension reloads gracefully without having to reload window

## Actual Behavior ##
Error message is thrown, Solution explorer pane is empty

### C# log ###
Using dotnet configured on PATH
Dotnet path: /usr/local/share/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/var/folders/sl/bf8tjzhs77z86kdfmxzcdf9h0000gn/T/250ea39d.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 10:57:56 AM] [Program] Language server initialized
[Info  - 10:57:59 AM] [WorkspaceProjectFactoryService] Project /Users/scoizzle/Projects/AspireDemo1/AppHost/AppHost.csproj loaded by C# Dev Kit
[Info  - 10:57:59 AM] [WorkspaceProjectFactoryService] Project /Users/scoizzle/Projects/AspireDemo1/FlakeyWebApp/FlakeyWebApp.csproj loaded by C# Dev Kit
[Info  - 10:57:59 AM] [WorkspaceProjectFactoryService] Project /Users/scoizzle/Projects/AspireDemo1/WebApp/WebApp.csproj loaded by C# Dev Kit
[Info  - 10:57:59 AM] [WorkspaceProjectFactoryService] Project /Users/scoizzle/Projects/AspireDemo1/ServiceDefaults/ServiceDefaults.csproj loaded by C# Dev Kit
[Info  - 10:57:59 AM] [WorkspaceProjectFactoryService] Project /Users/scoizzle/Projects/AspireDemo1/AppHost.Tests/AppHost.Tests.csproj loaded by C# Dev Kit
Using dotnet configured on PATH

### C# LSP Trace Logs ###
Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.tunnel-forwarding does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension adpyke.vscode-sql-formatter does not contribute csharpExtensionLoadPaths
Extension christian-kohler.npm-intellisense does not contribute csharpExtensionLoadPaths
Extension DotJoshJohnson.xml does not contribute csharpExtensionLoadPaths
Extension eamodio.gitlens does not contribute csharpExtensionLoadPaths
Extension EditorConfig.EditorConfig does not contribute csharpExtensionLoadPaths
Extension esbenp.prettier-vscode does not contribute csharpExtensionLoadPaths
Extension mechatroner.rainbow-csv does not contribute csharpExtensionLoadPaths
Extension mindaro-dev.file-downloader does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.blazorwasm-companion does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csdevkit does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.dotnet-maui does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-containers does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh-edit does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.vscode-remote-extensionpack does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cmake-tools does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools-extension-pack does not contribute csharpExtensionLoadPaths
Extension ms-vscode.cpptools-themes does not contribute csharpExtensionLoadPaths
Extension ms-vscode.hexeditor does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-nightly does not contribute csharpExtensionLoadPaths
Extension ms-vscode.live-server does not contribute csharpExtensionLoadPaths
Extension ms-vscode.powershell does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-explorer does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-server does not contribute csharpExtensionLoadPaths
Extension ms-vsliveshare.vsliveshare does not contribute csharpExtensionLoadPaths
Extension streetsidesoftware.code-spell-checker does not contribute csharpExtensionLoadPaths
Extension twxs.cmake does not contribute csharpExtensionLoadPaths

## Environment information ##

**VSCode version**: 1.92.0
**C# Extension**: 2.39.29
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.d7126b9e
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.303/

.NET workloads installed:
 [aspire]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.aspire/8.1.0/WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: arm64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.18.44|ms-vscode.cmake-tools-1.18.44|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|cpptools|ms-vscode|1.21.6|ms-vscode.cpptools-1.21.6-darwin-arm64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.9.55|ms-dotnettools.csdevkit-1.9.55-darwin-arm64|
|csharp|ms-dotnettools|2.39.29|ms-dotnettools.csharp-2.39.29-darwin-arm64|
|dotnet-maui|ms-dotnettools|1.1.16|ms-dotnettools.dotnet-maui-1.1.16-darwin-arm64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|file-downloader|mindaro-dev|1.0.13|mindaro-dev.file-downloader-1.0.13|
|gitlens|eamodio|15.2.3|eamodio.gitlens-15.2.3|
|hexeditor|ms-vscode|1.10.0|ms-vscode.hexeditor-1.10.0|
|js-debug-nightly|ms-vscode|2024.8.217|ms-vscode.js-debug-nightly-2024.8.217|
|live-server|ms-vscode|0.4.14|ms-vscode.live-server-0.4.14|
|npm-intellisense|christian-kohler|1.4.5|christian-kohler.npm-intellisense-1.4.5|
|powershell|ms-vscode|2024.2.2|ms-vscode.powershell-2024.2.2|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|rainbow-csv|mechatroner|3.12.0|mechatroner.rainbow-csv-3.12.0|
|remote-containers|ms-vscode-remote|0.380.0|ms-vscode-remote.remote-containers-0.380.0|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-server|ms-vscode|1.5.2|ms-vscode.remote-server-1.5.2|
|remote-ssh|ms-vscode-remote|0.113.1|ms-vscode-remote.remote-ssh-0.113.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.88.2|ms-vscode-remote.remote-wsl-0.88.2|
|vscode-dotnet-runtime|ms-dotnettools|2.1.1|ms-dotnettools.vscode-dotnet-runtime-2.1.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscode-sql-formatter|adpyke|1.4.4|adpyke.vscode-sql-formatter-1.4.4|
|vsliveshare|ms-vsliveshare|1.0.5936|ms-vsliveshare.vsliveshare-1.0.5936|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

Extension version: 2.39.29
VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|--crash-reporter-id 52400eae-3d97-44fd-b558-93f67d5542c9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplt:31103426
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718

```

</details>

**Comment by dibarbet** [comment] 2024-08-15 23:11
Think this is an issue on the devkit side.  Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1349

**Closed by dibarbet** 2024-08-15 23:11 UTC
