### ISSUE TITLE
Some autocomplete aren't working

### ISSUE THREAD

**Issue by Fairpl3x** [dotnet/vscode-csharp#6059] opened 2023-08-07 13:45 UTC
## Issue Description ##
Some autocomplete aren't working

## Steps to Reproduce ##

1. Type something
2. Autocomplete

Previous C# version (v1.26.0)
![258303944-a06247e2-0397-4226-b110-4c1db098bcd2](https://github.com/dotnet/vscode-csharp/assets/31825109/df159d3c-5e97-4cc1-bfa9-ea80059e9105)
Before

New C# version (v2.0.3)
![258304063-9c338aa5-7c22-4dab-bfe7-e3ce8958b80a](https://github.com/dotnet/vscode-csharp/assets/31825109/e4ca70af-ec02-478a-93df-221277ed1b5f)

## Expected Behavior ##
Auto-completing

## Actual Behavior ##
Does nothing

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
SDK .NET :
 Version:   7.0.101
 Commit:    bb24aafa11

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [c:\program files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.1 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-win32-x64|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|shader|slevesque|1.1.5|slevesque.shader-1.1.5|
|sort-lines|Tyriar|1.10.2|tyriar.sort-lines-1.10.2|
|unity-snippets-modified|lionize|0.4.0|lionize.unity-snippets-modified-0.4.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-icons|vscode-icons-team|12.5.0|vscode-icons-team.vscode-icons-12.5.0|;

</details>

**Comment by JustinGrote** [comment] 2023-08-07 17:08
Probably #6040

**Comment by dibarbet** [comment] 2023-08-07 21:50
Closing as a duplicate of https://github.com/dotnet/vscode-csharp/issues/6011

**Closed by dibarbet** 2023-08-07 21:50 UTC
Labels: Completion
