### ISSUE TITLE
Add "Dim Inactive Regions" setting to dim code inside undefined preprocessor directives

### ISSUE THREAD

**Issue by yasirkula** [dotnet/vscode-csharp#7573] opened 2024-09-17 13:44 UTC
## Is your feature request related to a problem? Please describe.
It's very hard to determine if a code block inside a preprocessor directive is compiled or not:

![image](https://github.com/user-attachments/assets/47a7b9d5-46f0-4e83-8cdd-f15d8c301fe1)

## Describe the solution you would like
Add an option to dim the code inside undefined preprocessor directives.

## Applicable Scenarios
Every C# code that uses preprocessor directives.

## Describe alternatives you've considered
AFAIK there are no alternatives in Visual Studio Code.

## Additional context
- Visual Studio Community Edition has this feature
- Visual Studio Code C++ extension has this feature ([link](https://github.com/Microsoft/vscode-cpptools/issues/1466)) ([link](https://devblogs.microsoft.com/cppblog/visual-studio-code-cc-extension-feb-2018-update/))

**Comment by dibarbet** [comment] 2024-09-17 18:13
@yasirkula this should already be supported, would you mind providing the details listed here?
https://github.com/dotnet/vscode-csharp/blob/main/SUPPORT.md#colorization-problems

**Comment by yasirkula** [comment] 2024-09-17 21:01
@dibarbet I'm using the Dark Modern theme that comes with the built-in `vscode.theme-defaults v1.0.0` extension. Screen recording:

https://github.com/user-attachments/assets/996361b2-76b6-42ee-8f87-cf5052cd6f7c

I've noticed that the code looks dimmed in Visual Studio 2019 Light and Visual Studio 2019 Dark themes.

My VS Code version is as follows:

```
Version: 1.93.1 (system setup)
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by dibarbet** [comment] 2024-09-18 18:02
Thanks.  It looks like the server's semantic classification is working (it has the correct `excludedCode` for the semantic token type).  But it seems as though the Dark Modern theme doesn't provide any specific colorization for it.  Unfortunately, that theme is shipped by VSCode and we can't easily modify it.

I'd generally recommend using the VS 2019 dark/light themes we ship in the extension.  Otherwise, you can enable the correct colorization in the Dark Modern theme by adding the following to your settings.json:
```
"editor.semanticTokenColorCustomizations": {
    "rules": {
        "excludedCode": {
            "foreground": "#808080",
        }
    }
},
```

Closing this as this is the expected behavior.

**Closed by dibarbet** 2024-09-18 18:02 UTC
Labels: Needs More Info
