### ISSUE TITLE
error when typing and accept suggestion

### ISSUE THREAD

**Issue by heartacker** [dotnet/vscode-csharp#5830] opened 2023-06-19 07:33 UTC
## Environment data
名称: C#
ID: ms-dotnettools.csharp
说明: Base language support for C#
版本: 2.0.212
发布者: Microsoft
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp

## Steps to reproduce

1. typing commments ///
2. I want to input inheritdoc
3.  when  i type inher and the accept the suggestion
4. the in put became 'i'
5.  even I type the whole word, and hit the enter, and the input still be a 'i'

## Actual behavior
![intelisense_err_c#](https://github.com/dotnet/vscode-csharp/assets/1876302/8827d75d-63e7-4e4d-b484-34a339044c53)

**Comment by dibarbet** [comment] 2023-06-20 19:44
@genlu FYI - I don't think this is related to the previous completion issue, but I might be wrong

**Comment by genlu** [comment] 2023-06-22 20:57
This is actually https://github.com/microsoft/vscode/issues/184924
The cause is how we categorize what a "complex edit" is, i.e. any text change that's not entirely in the default span. This would be fixed with next insider build. That said, we could change the definition of complex edit so things like this won't need the command to work

**Closed** 2023-08-01 19:44 UTC
Labels: Bug, Triaged
