### ISSUE TITLE
NET Debugging is supported only in Microsoft versions of VS Code

### ISSUE THREAD

**Issue by emanuel-v-r** [dotnet/vscode-csharp#7412] opened 2024-08-02 16:12 UTC
Whenever I run any vscode based ide I ran into this:

```
------------------------------------------------------------------------------
You may only use the Microsoft Visual Studio .NET/C/C++ Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you
develop and test your applications.
------------------------------------------------------------------------------
Unable to start debugging. .NET Debugging is supported only in Microsoft versions of VS Code. See https://aka.ms/VSCode-DotNet-DbgLicense for more information.
```
Being vscode an open source project why locking the dotnet debugger this way? I mean microsoft benefits from all contributions from the community, why not giving this back to the community as well? I thought that was the goal of c#/dotnet.

**Comment by JoeRobich** [comment] 2024-08-02 22:00
Closing as a duplicate of https://github.com/dotnet/vscode-csharp/issues/1059

**Closed by JoeRobich** 2024-08-02 22:00 UTC
Labels: Resolved-Duplicate
