### ISSUE TITLE
Error when creating new files

### ISSUE THREAD

**Issue by raafamaia** [dotnet/vscode-csharp#4181] opened 2020-11-05 07:43 UTC
## Issue Description ##

Hello!

I'm having some trouble using VSCode and the C# extension.
Everytime I create a new file, the Intellisense doens't work, not showing any errors (red underline) on the file.
The OmniSharp Log output shows the following message:

[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/Mock.cs
I reinstalled VSCode and deleted all my extensions folder rm -rf ~/.vscode*, just installed the C# extension and the error persists.

I'm using VSCode version 1.50.1 on a macOS Cataline 10.15.7, dotnet sdk 3.1.403

## Steps to Reproduce ##

Clean Install of VSCode
Install C# extension
Create a dotnet webapi project
`dotnet new webapi -n Test`
Create a new file
Write something
ex: aaaaaa

## Expected Behavior ##

The expect behavior would be the line written with a red underscore, indicating an error.

## Actual Behavior ##

Nothing happens, and you can check errors popping on the OmniSharp Log

```
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Teste/Controllers/teste.cs

```
### OmniSharp log ###
<details>
Here's the full OmniSharp Log, the error lines at the end start appearing as I create a new file and start to type on it.

Starting OmniSharp server at 11/5/2020, 4:28:59 AM
    Target: /Users/rafaelmaia/source/personal/dotnet/Commander

OmniSharp server started.
    Path: /Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/run
    PID: 94751

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.15.7 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.8.0 - "/Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.8.0 - "/Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/rafaelmaia/.vscode/extensions/ms-dotnettools.csharp-1.23.5/.omnisharp/1.37.3/omnisharp/.msbuild
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/rafaelmaia/source/personal/dotnet/Commander'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in '/Users/rafaelmaia/source/personal/dotnet/Commander'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/rafaelmaia/source/personal/dotnet/Commander/Commander.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/rafaelmaia/source/personal/dotnet/Commander'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/rafaelmaia/source/personal/dotnet/Commander/Commander.csproj
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/rafaelmaia/source/personal/dotnet/Commander' on host 94627.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/rafaelmaia/source/personal/dotnet/Commander/Commander.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/rafaelmaia/source/personal/dotnet/Commander/Commander.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: Commander
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
[info]: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionService
        Could not find document for file /Users/rafaelmaia/source/personal/dotnet/Commander/Data/teste1.cs
</details>

### C# log ###
Nothing on C# Log.

## Environment information ##

**VSCode version**: 1.50.1
**C# Extension**: 1.23.5

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.403/

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.3 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-dotnettools|1.23.5|;

</details>

**Comment by filipw** [comment] 2020-11-05 07:47
this is fixed in https://github.com/OmniSharp/omnisharp-vscode/pull/4178

**Comment by duartegjmiguel** [comment] 2020-11-10 19:43
I am having this issue as well.

**Comment by RomainHautefeuille** [comment] 2020-11-18 15:05
Are you sure @filipw ?
I am using 1.23.6 and I still need to manually restart Omnisharp after creating a file.
No completion in the file, nor can I use the new class elsewhere otherwise.

**Comment by filipw** [comment] 2020-11-18 15:23
@JoeRobich should this be fixed now?

**Comment by filipw** [comment] 2020-11-18 15:41
interesting is that I was partly correct 🙂
looks like it works on Windows, but not on MacOS

**Comment by RomainHautefeuille** [comment] 2020-11-18 17:30
hum, it might be a distinct issue but here is an easy reproduction path on Windows:

1. make a new folder, cd into it
2. `dotnet new console`
3. go edit Program class, add property : `public Model MyProperty { get; set; }`
4. use `Show Fixes (ctrl+;)` to create Model `Generate type 'Model' -> Generate class 'Model' in a new file`

now Model.cs is created but Program doesn't see the class, and you can't see the 'x references' hints in the new file.

**Comment by filipw** [comment] 2020-11-19 08:22
Thanks, we had a look at that yesterday with @333fred and indeed it is a bug that crept in due to improvements in handling file changes and due to certain indeterminism in how VS Code sends file events to the server.

It is addressed in https://github.com/OmniSharp/omnisharp-roslyn/pull/2019

**Comment by RomainHautefeuille** [comment] 2020-11-19 10:35
Nice, thanks!

**Comment by TCROC** [comment] 2020-12-10 00:17
When is this going to get released the the VS Code Marketplace?

**Comment by 333fred** [comment] 2020-12-10 17:24
@TCROC if you set `omnisharp.path` to `latest` in your settings, you should see it now.

**Comment by TCROC** [comment] 2020-12-10 20:59
@333fred Awesome thanks!  I just created a new test script from Unity and it appears to be working :)

**Comment by alpha-tango-kilo** [comment] 2020-12-12 12:20
>     1. make a new folder, cd into it
> 
>     2. `dotnet new console`
> 
>     3. go edit Program class, add property : `public Model MyProperty { get; set; }`
> 
>     4. use `Show Fixes (ctrl+;)` to create Model `Generate type 'Model' -> Generate class 'Model' in a new file`
> 
> 
> now Model.cs is created but Program doesn't see the class, and you can't see the 'x references' hints in the new file.

This minimal example works for me having set `omnisharp.path` to `latest`, however within a Unity project adding a new C# script isn't recognised and I get the "Could not find document for file" warning, no autocompletions or reference counter

I'm using VSCodium 1.52.0, C# extension 1.23.7. I'm not massively familiar with C# development so please let me know what other debug info you need if you do

**Comment by TCROC** [comment] 2020-12-14 22:06
> > ```
> > 1. make a new folder, cd into it
> > 
> > 2. `dotnet new console`
> > 
> > 3. go edit Program class, add property : `public Model MyProperty { get; set; }`
> > 
> > 4. use `Show Fixes (ctrl+;)` to create Model `Generate type 'Model' -> Generate class 'Model' in a new file`
> > ```
> > 
> > 
> > now Model.cs is created but Program doesn't see the class, and you can't see the 'x references' hints in the new file.
> 
> This minimal example works for me having set `omnisharp.path` to `latest`, however within a Unity project adding a new C# script isn't recognised and I get the "Could not find document for file" warning, no autocompletions or reference counter
> 
> I'm using VSCodium 1.52.0, C# extension 1.23.7. I'm not massively familiar with C# development so please let me know what other debug info you need if you do

I had the same problem.  It is broken in 1.23.7.  Do this to use the beta where it is fixed: https://github.com/OmniSharp/omnisharp-vscode/issues/4181#issuecomment-742668376

**Comment by alpha-tango-kilo** [comment] 2020-12-15 00:08
That's what I am doing - sorry if I wasn't clear. I set `omnisharp.path` to `latest` and the extension still isn't picking up new scripts in a Unity project I'm working on

The minimal example works though

**Comment by JoeRobich** [comment] 2020-12-15 00:16
@alpha-tango-kilo Sorry you are running into issues. Are you adding the script file outside of Unity? 

I ask because Unity generates old style project files where each source file to be included is individually listed. This is different from SDK style projects created with `dotnet new` which automatically include source files without needing them listed.

I am not sure that OmniSharp would add new files to the workspace without Unity rebuilding the project file to specifically include the source file.

**Comment by alpha-tango-kilo** [comment] 2020-12-15 13:54
> I ask because Unity generates old style project files where each source file to be included is individually listed

I'm not surprised somehow

So I tested this and now I can't even replicate my own issue now 3 days later...

I tried (with Unity open in all cases):

1. Creating a new script in Unity, then opening VSC
2. Creating a new script in Unity with VSC already open
3. Creating a new script in VSC

Everything worked!🤯 Shall report back if I have any further issues down the line.

Also given Unity itself seems also to be a factor here, I'll note that the version I'm using is `2019.4.16f1`

**Comment by TCROC** [comment] 2020-12-15 15:10
I did notice having this issue once when using the "latest" release. It was right after I created a new .asmdef file. I will see if I can recreate it later today.

**Comment by JoeRobich** [comment] 2020-12-19 00:24
@TCROC I would check that Unity is updating the project file after adding the second asmdef and script. You should see a new `<Compile Include="..Path to new script.." />` in the csproj.

**Comment by TCROC** [comment] 2020-12-19 00:37
@JoeRobich I can confirm that behavior is working as expected.  When a new asmdef file is created, a new csproj is correctly created and that ``<Compile Include="..Path to new script.." /> is there.  VS Code just isn't picking up on it and I have to restart VS Code.

**Comment by JoeRobich** [comment] 2020-12-19 01:05
@TCROC Does VS Code stay open with your unity project folder from step 4 thru step 8? or is it closed while adding the new asmdef and script?

**Comment by TCROC** [comment] 2020-12-19 01:09
@JoeRobich Unity and VS Code are both open the entire time

**Comment by TCROC** [comment] 2020-12-19 02:00
> @TCROC Does VS Code stay open with your unity project folder from step 4 thru step 8? or is it closed while adding the new asmdef and script?

To further clarify, VS Code is open in steps 4 - 8.

**Comment by TCROC** [comment] 2020-12-28 15:11
Just checking in to see what the status is on this bug

**Comment by FiniteReality** [comment] 2021-01-07 22:39
I'm also seeing this issue in VSCode using extension version 1.23.8 and OmniSharp 1.37.6-beta.16. I'm not seeing any exceptions, just the `Could not find document for file` message. I'm using a normal SDK-style csproj targeting net5.0.

**Comment by CapClumsy** [comment] 2021-01-10 19:49
> I'm also seeing this issue in VSCode using extension version 1.23.8 and OmniSharp 1.37.6-beta.16. I'm not seeing any exceptions, just the `Could not find document for file` message. I'm using a normal SDK-style csproj targeting net5.0.
Me too, it's not working for me either and just giving that message.

**Comment by CapClumsy** [comment] 2021-01-10 19:53
I noticed that in the changelog of the C# extension it said:  

> For Mono-based development (e.g. Unity) that requires full .NET framework, you need to set "omnisharp.useGlobalMono": "always". The current value of "auto" will remain "never" until Mono upgrades their bundled MSBuild version.  

I tried setting it to always, but it still won't work

**Comment by 333fred** [comment] 2021-01-10 20:12
For those of you who are still seeing this and aren't adding non csharp files (like tcroc is) please file a new issue with specific repro steps. I use the extension every day and have yet to reproduce the issue with csharp files, so more info is needed.

**Comment by TCROC** [comment] 2021-01-31 22:26
https://github.com/OmniSharp/omnisharp-vscode/issues/4181#issuecomment-742795336

This issue is occurring again for me.  I've tested it in both Unity projects and Mono projects.  Running on Ubuntu 20.04.

**Comment by TCROC** [comment] 2021-01-31 22:39
> [#4181 (comment)](https://github.com/OmniSharp/omnisharp-vscode/issues/4181#issuecomment-742795336)
> 
> This issue is occurring again for me. I've tested it in both Unity projects and Mono projects. Running on Ubuntu 20.04.

Never mind.  False alarm.  I just had to increase the file watcher limit on my system.

**Comment by TCROC** [comment] 2021-02-18 22:14
However, I would like to confirm that even with the file watchers issue fixed, it still doesn't work when creating a new asmdef file in Unity (which is the equivalent of adding a new .csproj).

**Comment by JoeRobich** [comment] 2024-09-05 00:23
There have been lots of improvements since this issue was opened. Please open a new issue with logs if you are still running into this.

**Closed by JoeRobich** 2024-09-05 00:23 UTC
Labels: Bug, OmniSharp
