### ISSUE TITLE
Semantic Highlighting Breaks Escape Character Coloring

### ISSUE THREAD

**Issue by ssoher** [dotnet/vscode-csharp#3864] opened 2020-06-21 17:58 UTC
I have my own custom theme with `"semanticHighlighting": true` so the `Excluded Code` is colored correctly. But while semantic highlighting is enabled `constant.character.escape.cs` doesn't get it's assigned color but the color of the scope `string`. If I don't assign a color to `string` it works correctly. Or if I assign those colors but turn off `semanticHighlighting`, it again colors the escape characters correctly. Do I need to define semanticTokenColors, if so please give me an example of how to.

Same theme is used with C/C++ projects and the escape characters are colored correctly.

```js
// Below colors strings and escape characters correctly only if semanticHighlighting is false
// Or "string" scope is removed while semanticHighlighting is enabled
{
    "scope": [
        "string",
    ],
    "settings": {
        "foreground": "#f26557"
    }
},
{
    "scope": [
        "constant.character.escape",
    ],
    "settings": {
        "foreground": "#1e41da",
    }
},
```

**Comment by JoeRobich** [comment] 2024-11-12 08:21
duplicate of https://github.com/dotnet/vscode-csharp/issues/3823

**Closed by JoeRobich** 2024-11-12 08:21 UTC
Labels: Bug, Editor-Syntax Highlighting, OmniSharp, Triaged
