### ISSUE TITLE
Visual Studio Code Failed to find dotnet from path with "which dotnet"

### ISSUE THREAD

**Issue by avatar-lavventura** [dotnet/vscode-csharp#7701] opened 2024-10-27 13:23 UTC
I have installed dotnet sdk inside MacBook and in my terminal `dotnet --info` returns valid information. 

But inside `Visual Studio Code`, I am getting following error message, when I try to run the project:

```
Failed to find dotnet from path with "which dotnet".
Cannot find .NET SDK installation from PATH environment. C# DevKit extension would not work without a proper installation of the .NET SDK accessible through PATH environment. Rebooting might be necessary in some cases. Check the PATH environment logged in the C# DevKit logging window. In some cases, it could be affected how VS code was started.
PATH=/usr/bin:/bin:/usr/sbin:/sbin
```

How can I fix this error? Note that vscode tries to read `PATH` from `/bin/sh` rather than `/bin/bash`.

**Comment by dibarbet** [comment] 2024-10-28 22:43
Looks like the issue is on the devkit side, moving to https://github.com/microsoft/vscode-dotnettools/issues/1565

**Closed by dibarbet** 2024-10-28 22:43 UTC
