### ISSUE TITLE
[Feature Request] Add option to track active open file

### ISSUE THREAD

**Issue by ShreyasJejurkar** [dotnet/vscode-csharp#6225] opened 2023-08-25 10:45 UTC
## Additional context
Visual Studio has this feature where clicking on the symbol (double-sided arrow - sync arrow) in the Solution Explorer toolbar, highlights the file that is currently open in the editor window. 
This is especially helpful when we traverse through a lot of files to find something or when fixing a bug, and we want to know the location of a currently opened file in the solution explorer tree. 

It would be great and helpful if this feature gets added to the C# extension and we can show the icon in the below area, along with the VS code command, so that people can trigger it via keyboard shortcut, or we can add a shortcut key as part of the feature itself.  

![image](https://github.com/dotnet/vscode-csharp/assets/17148381/310efe3b-1e25-4f64-80e8-deec14134ae2)

Edit - I tried finding the corresponding code in this repo, but I guess that is a closed source :(  so can't contribute!

**Comment by dibarbet** [comment] 2023-08-31 00:36
Duplicate of this issue on the devkit side.
https://github.com/microsoft/vscode-dotnettools/issues/180

**Closed by dibarbet** 2023-08-31 00:36 UTC
