### ISSUE TITLE
Can't find SDK using Path environment variable (Windows)

### ISSUE THREAD

**Issue by Janealter** [dotnet/vscode-csharp#6384] opened 2023-09-16 09:27 UTC
Type: <b>Bug</b>

## Issue Description ##
Can't find SDK using Path environment variable, but can find using dotnet.dotnetPath. The path is the same - C:\Program Files\dotnet

## Steps to Reproduce ##
1. Start VSCode
2. See output

## Expected Behavior ##
SDK found successfully using Path environment variable

## Actual Behavior ##
SDK found using dotnet.dotnetPath only 

## Logs ##
See below
        
### C# log ###
<details>
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
Dotnet path: c:\Users\janealter\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.11\dotnet.exe
Activating C# standalone...
Starting server at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel off --extensionLogDirectory c:\Users\janealter\AppData\Roaming\Code\logs\20230916T121305\window1\exthost\ms-dotnettools.csharp
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Scripting.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at c:\Users\janealter\.vscode\extensions\ms-dotnettools.csharp-2.1.2-win32-x64\.roslyn\Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
[Info  - 12:23:22 PM] [Program]Language server initialized
[LanguageServerHost][09:23:22.343][Start]initialize
[LanguageServerHost][09:23:22.347][Start]Initialize
[LanguageServerHost][09:23:22.382][End]Initialize
[LanguageServerHost][09:23:22.410][End]initialize
[LanguageServerHost][09:23:22.413][Start]initialized
[LanguageServerHost][09:23:22.483][End]initialized
[LanguageServerHost][09:23:22.497][Start]workspace/diagnostic
[LanguageServerHost][09:23:22.497][Start]solution/open
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[LanguageServerHost]Processing 0 documents
[Error - 12:23:22 PM] [LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 97
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[LanguageServerHost][09:23:22.516][End]solution/open
</details>

### C# LSP Trace Logs ###
<details>
Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension vscode.microsoft-authentication does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl-recommender does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.tunnel-forwarding does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension eamodio.gitlens does not contribute csharpExtensionLoadPaths
Extension EditorConfig.EditorConfig does not contribute csharpExtensionLoadPaths
Extension GitHub.copilot does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.intellicode-api-usage-examples does not contribute csharpExtensionLoadPaths
Extension VisualStudioExptTeam.vscodeintellicode does not contribute csharpExtensionLoadPaths
Extension vscode-icons-team.vscode-icons does not contribute csharpExtensionLoadPaths
[Trace - 12:23:22 PM] Sending notification 'initialized'.
Params: {}

[Trace - 12:23:22 PM] Sending request 'workspace/diagnostic - (1)'.
Params: {
    "previousResultIds": [],
    "partialResultToken": "cf14cffd-2359-4bc5-8152-4608ee22cc63"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.410][End]initialize"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.413][Start]initialized"
}

[Trace - 12:23:22 PM] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "39a530e7-42dd-41ff-b22a-e56e65077c83",
            "method": "workspace/didChangeConfiguration"
        }
    ]
}

[Trace - 12:23:22 PM] Sending response 'client/registerCapability - (2)'. Processing request took 0ms
No result returned.

[Trace - 12:23:22 PM] Received request 'workspace/configuration - (3)'.
Params: {
    "items": [
        {
            "section": "csharp|symbol_search.dotnet_search_reference_assemblies"
        },
        {
            "section": "visual_basic|symbol_search.dotnet_search_reference_assemblies"
        },
        {
            "section": "csharp|implement_type.dotnet_insertion_behavior"
        },
        {
            "section": "visual_basic|implement_type.dotnet_insertion_behavior"
        },
        {
            "section": "csharp|implement_type.dotnet_property_generation_behavior"
        },
        {
            "section": "visual_basic|implement_type.dotnet_property_generation_behavior"
        },
        {
            "section": "csharp|completion.dotnet_show_name_completion_suggestions"
        },
        {
            "section": "visual_basic|completion.dotnet_show_name_completion_suggestions"
        },
        {
            "section": "csharp|completion.dotnet_provide_regex_completions"
        },
        {
            "section": "visual_basic|completion.dotnet_provide_regex_completions"
        },
        {
            "section": "csharp|completion.dotnet_show_completion_items_from_unimported_namespaces"
        },
        {
            "section": "visual_basic|completion.dotnet_show_completion_items_from_unimported_namespaces"
        },
        {
            "section": "csharp|quick_info.dotnet_show_remarks_in_quick_info"
        },
        {
            "section": "visual_basic|quick_info.dotnet_show_remarks_in_quick_info"
        },
        {
            "section": "navigation.dotnet_navigate_to_decompiled_sources"
        },
        {
            "section": "csharp|highlighting.dotnet_highlight_related_json_components"
        },
        {
            "section": "visual_basic|highlighting.dotnet_highlight_related_json_components"
        },
        {
            "section": "csharp|highlighting.dotnet_highlight_related_regex_components"
        },
        {
            "section": "visual_basic|highlighting.dotnet_highlight_related_regex_components"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_literal_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_literal_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_indexer_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_indexer_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_object_creation_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_object_creation_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_other_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_other_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_implicit_variable_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_implicit_variable_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_lambda_parameter_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_lambda_parameter_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_implicit_object_creation"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_implicit_object_creation"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.tab_width"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.tab_width"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.indent_size"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.indent_size"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.indent_style"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.indent_style"
        },
        {
            "section": "csharp|code_style.formatting.new_line.end_of_line"
        },
        {
            "section": "visual_basic|code_style.formatting.new_line.end_of_line"
        },
        {
            "section": "code_style.formatting.new_line.insert_final_newline"
        },
        {
            "section": "csharp|background_analysis.dotnet_analyzer_diagnostics_scope"
        },
        {
            "section": "visual_basic|background_analysis.dotnet_analyzer_diagnostics_scope"
        },
        {
            "section": "csharp|background_analysis.dotnet_compiler_diagnostics_scope"
        },
        {
            "section": "visual_basic|background_analysis.dotnet_compiler_diagnostics_scope"
        },
        {
            "section": "csharp|code_lens.dotnet_enable_references_code_lens"
        },
        {
            "section": "visual_basic|code_lens.dotnet_enable_references_code_lens"
        },
        {
            "section": "csharp|code_lens.dotnet_enable_tests_code_lens"
        },
        {
            "section": "visual_basic|code_lens.dotnet_enable_tests_code_lens"
        },
        {
            "section": "projects.dotnet_binary_log_path"
        }
    ]
}

[Trace - 12:23:22 PM] Sending response 'workspace/configuration - (3)'. Processing request took 0ms
Result: [
    true,
    null,
    "withOtherMembersOfTheSameKind",
    null,
    "preferThrowingProperties",
    null,
    "true",
    null,
    "true",
    null,
    true,
    null,
    "true",
    null,
    "true",
    "true",
    null,
    "true",
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    4,
    null,
    4,
    null,
    "space",
    null,
    "lf",
    null,
    false,
    "openFiles",
    null,
    "openFiles",
    null,
    true,
    null,
    true,
    null,
    null
]

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.483][End]initialized"
}

[Trace - 12:23:22 PM] Sending notification 'solution/open'.
Params: {
    "solution": "file:///c:/Users/janealter/Builder Defender/Builder Defender.sln"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.497][Start]workspace/diagnostic"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.497][Start]solution/open"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]previousResults.Length=0"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]Processing 0 documents"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "[LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.\r\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)\r\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()\r\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()\r\n   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()\r\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\r\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\r\n   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159\r\n   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 97\r\n   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136"
}

[Trace - 12:23:22 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][09:23:22.516][End]solution/open"
}

[Trace - 12:23:24 PM] Received request 'workspace/diagnostic/refresh - (4)'.
Params: []

[Trace - 12:23:24 PM] Sending response 'workspace/diagnostic/refresh - (4)'. Processing request took 0ms
No result returned.

[Trace - 12:23:24 PM] Received request 'workspace/inlayHint/refresh - (5)'.
Params: []

[Trace - 12:23:24 PM] Sending response 'workspace/inlayHint/refresh - (5)'. Processing request took 1ms
No result returned.
</details>

## Environment information ##

**VSCode version**: 1.82.2
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.11 [c:\Users\janealter\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.11\shared\Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|copilot|GitHub|1.111.404|github.copilot-1.111.404|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|
|vscode-icons|vscode-icons-team|12.5.0|vscode-icons-team.vscode-icons-12.5.0|
|vscodeintellicode|VisualStudioExptTeam|1.2.30|visualstudioexptteam.vscodeintellicode-1.2.30|;

</details>

Extension version: 2.1.2
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (22.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Janealter** [comment] 2023-09-16 09:35
`dotnet --info` shows that there are SDKs installed
```
.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]
```

But the VSCode C# shows that there are not

**Comment by dibarbet** [comment] 2023-09-19 00:12
I think this is a duplicate of https://github.com/dotnet/vscode-csharp/issues/6335, but it looks like you have .net7 installed so I'm not quite as sure.

Does reverting to 2.0.436 help at all?

**Comment by dibarbet** [comment] 2023-10-19 00:14
There have been various fixes in this area, so the issue is either fixed or the logs are out of date.  Try C# extension version 2.7.25.

If the issue is not fixed, please re-open this issue with
1.  New C# output window logs (with `dotnet.server.trace` set to `Trace`) AND
2.  The full output of running `dotnet --info` from the command line.

**Closed by dibarbet** 2023-10-19 00:14 UTC
Labels: Bug, Needs More Info, Triaged
