### ISSUE TITLE
.NET program execution: 'dotnet-%USERNAME%' space issue in account names

### ISSUE THREAD

**Issue by Chizaruu** [dotnet/vscode-csharp#5713] opened 2023-06-07 05:34 UTC
## Environment data
<details>
<summary>`dotnet --info` output:</summary>

.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   A:\Program Files\dotnet\sdk\7.0.203\

</details>

VS Code version: 1.77.0

C# Extension version: v2.0.206

## ~~OmniSharp~~ C# log
<details>
<summary>C# Log</summary>

Dotnet path: a:\Users\Abdul Kadir Ibn Ali\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.5\dotnet.exe  
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Info  - 3:08:45 PM] [LanguageServerProjectSystem]Loaded MSBuild at A:\Program Files\dotnet\sdk\7.0.203
[Info  - 3:08:45 PM] [LanguageServerProjectSystem]Loading b:\GitHub\Misfit Maze\Misfit Maze.sln...
[Info  - 3:08:47 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\UltimateEditorEnhancer-Editor\UltimateEditorEnhancer-Editor.csproj
[Info  - 3:08:47 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\Sirenix.OdinInspector.Modules.UnityMathematics\Sirenix.OdinInspector.Modules.UnityMathematics.csproj
[Info  - 3:08:48 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\Unity.VSCode.Editor\Unity.VSCode.Editor.csproj
[Info  - 3:08:48 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\com.tsk.ess.fpcc.assetstore\com.tsk.ess.fpcc.assetstore.csproj
[Info  - 3:08:48 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\UltimateEditorEnhancer\UltimateEditorEnhancer.csproj
[Info  - 3:08:48 PM] [LanguageServerProjectSystem]Successfully completed load of b:\GitHub\Misfit Maze\CSharpProjFolders\TSKScripts\TSKScripts.csproj
[Info  - 3:08:48 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:03.6715158

</details>

<details>
<summary>Projects Log:</summary>

2023-06-07 15:08:47.916 [info] Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * **You intended to execute a .NET program, but dotnet-a:\Users\Abdul does not exist.**
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

2023-06-07 15:08:49.713 [info] Project system initialization finished. 0 project(s) are loaded, and 6 failed to load.

</details>

## Steps to reproduce

1. Open the script within Unity.
2. Wait for C#/Dev KIt extensions to load.
3. See the error

## Expected behaviour
Projects load.

## Actual behaviour
Projects don't load.

## Additional context
Please note that my Account name is Abdul Kadir Ibn Ali. I feel this has something to do with the issue.

My projects should be compatible with the dev kit extension.

**Comment by dibarbet** [comment] 2023-06-07 17:52
Dupe of https://github.com/microsoft/vscode-dotnettools/issues/24

**Closed by dibarbet** 2023-06-07 17:52 UTC
Labels: Resolved-External
