### ISSUE TITLE
vscode C# extension version 2.1.2 is buggy. IntelliSense is not working properly. I downgraded to v1.26.0 to resolved the issue.

### ISSUE THREAD

**Issue by dechalico** [dotnet/vscode-csharp#6358] opened 2023-09-13 16:57 UTC
## Environment data

`dotnet --info` output:
.NET SDK (reflecting any global.json):
 Version:   6.0.413
 Commit:    10710f7d8e

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         debian.12-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.413/

global.json file:
  Not found

Host:
  Version:      6.0.21
  Architecture: x64
  Commit:       e40b3abf1b

.NET SDKs installed:
  6.0.413 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

VS Code version:
C# Extension version: 2.1.2

**Comment by dibarbet** [comment] 2023-09-13 18:31
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6335

**Closed by dibarbet** 2023-09-13 18:31 UTC
