### ISSUE TITLE
Failed to find dotnet info from path

### ISSUE THREAD

**Issue by scottmwyant** [dotnet/vscode-csharp#6178] opened 2023-08-19 18:49 UTC
We have written the needed data into your
Type: <b>Bug</b>

## Issue Description ##

C# code files, like Program.cs generated by `dotnet new worker` are not colorized properly and there is no intellisense.  Looking through logs, it appears the extension is not able to find dotnet on my system although it's installed in the standard location `C:\Program Files\dotnet`, version 7.0.400.  The ms-dotnettools.vscode-dotnet-runtime extension downloads runtime 7.0.10 but the C# extension is looking for 7.0.100 or greater.

## Steps to Reproduce ##

On Windows install dotnet sdk v7.0.400 to `C:\Program Files\dotnet`.  Install VSCode with the C# extension.  Run `dotet new worker`.

## Expected Behavior ##

Working colorization and intellisense.

## Actual Behavior ##

No colorization or intellisense.

### C# log ###

Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
Found dotnet version 7.0.10. Minimum required version is 7.0.100.
Dotnet path: c:\Users\swyant\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.10\dotnet.exe
Activating C# standalone...
[Info  - 2:28:25 PM] [Program]Language server initialized

### C# LSP Trace Logs ###

Extension vscode.bat does not contribute csharpExtensionLoadPaths
Extension vscode.clojure does not contribute csharpExtensionLoadPaths
Extension vscode.coffeescript does not contribute csharpExtensionLoadPaths
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.cpp does not contribute csharpExtensionLoadPaths
Extension vscode.csharp does not contribute csharpExtensionLoadPaths
Extension vscode.css does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.dart does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.diff does not contribute csharpExtensionLoadPaths
Extension vscode.docker does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.fsharp does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.github-authentication does not contribute csharpExtensionLoadPaths
Extension vscode.go does not contribute csharpExtensionLoadPaths
Extension vscode.groovy does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.handlebars does not contribute csharpExtensionLoadPaths
Extension vscode.hlsl does not contribute csharpExtensionLoadPaths
Extension vscode.html does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ini does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.java does not contribute csharpExtensionLoadPaths
Extension vscode.javascript does not contribute csharpExtensionLoadPaths
Extension vscode.json does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.julia does not contribute csharpExtensionLoadPaths
Extension vscode.latex does not contribute csharpExtensionLoadPaths
Extension vscode.less does not contribute csharpExtensionLoadPaths
Extension vscode.log does not contribute csharpExtensionLoadPaths
Extension vscode.lua does not contribute csharpExtensionLoadPaths
Extension vscode.make does not contribute csharpExtensionLoadPaths
Extension vscode.markdown does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.media-preview does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl-recommender does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug-companion does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.builtin-notebook-renderers does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.objective-c does not contribute csharpExtensionLoadPaths
Extension vscode.perl does not contribute csharpExtensionLoadPaths
Extension vscode.php does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.powershell does not contribute csharpExtensionLoadPaths
Extension vscode.pug does not contribute csharpExtensionLoadPaths
Extension vscode.python does not contribute csharpExtensionLoadPaths
Extension vscode.r does not contribute csharpExtensionLoadPaths
Extension vscode.razor does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.restructuredtext does not contribute csharpExtensionLoadPaths
Extension vscode.ruby does not contribute csharpExtensionLoadPaths
Extension vscode.rust does not contribute csharpExtensionLoadPaths
Extension vscode.scss does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.shaderlab does not contribute csharpExtensionLoadPaths
Extension vscode.shellscript does not contribute csharpExtensionLoadPaths
Extension vscode.simple-browser does not contribute csharpExtensionLoadPaths
Extension vscode.sql does not contribute csharpExtensionLoadPaths
Extension vscode.swift does not contribute csharpExtensionLoadPaths
Extension vscode.theme-abyss does not contribute csharpExtensionLoadPaths
Extension vscode.theme-defaults does not contribute csharpExtensionLoadPaths
Extension vscode.theme-kimbie-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai does not contribute csharpExtensionLoadPaths
Extension vscode.theme-monokai-dimmed does not contribute csharpExtensionLoadPaths
Extension vscode.theme-quietlight does not contribute csharpExtensionLoadPaths
Extension vscode.theme-red does not contribute csharpExtensionLoadPaths
Extension vscode.vscode-theme-seti does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-dark does not contribute csharpExtensionLoadPaths
Extension vscode.theme-solarized-light does not contribute csharpExtensionLoadPaths
Extension vscode.theme-tomorrow-night-blue does not contribute csharpExtensionLoadPaths
Extension vscode.typescript does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.vb does not contribute csharpExtensionLoadPaths
Extension vscode.xml does not contribute csharpExtensionLoadPaths
Extension vscode.yaml does not contribute csharpExtensionLoadPaths
Extension mhutchie.git-graph does not contribute csharpExtensionLoadPaths
Extension ms-azure-devops.azure-pipelines does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-python.python does not contribute csharpExtensionLoadPaths
Extension ms-python.vscode-pylance does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-keymap does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.jupyter-renderers does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-cell-tags does not contribute csharpExtensionLoadPaths
Extension ms-toolsai.vscode-jupyter-slideshow does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-containers does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-ssh-edit does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.remote-wsl does not contribute csharpExtensionLoadPaths
Extension ms-vscode-remote.vscode-remote-extensionpack does not contribute csharpExtensionLoadPaths
Extension ms-vscode.azure-account does not contribute csharpExtensionLoadPaths
Extension ms-vscode.hexeditor does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-explorer does not contribute csharpExtensionLoadPaths
Extension ms-vscode.remote-server does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-xml does not contribute csharpExtensionLoadPaths
Extension redhat.vscode-yaml does not contribute csharpExtensionLoadPaths
Extension ritwickdey.LiveServer does not contribute csharpExtensionLoadPaths
Extension vscode-icons-team.vscode-icons does not contribute csharpExtensionLoadPaths

## Environment information ##

**VSCode version**: 1.81.1
**C# Extension**: 2.0.376
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|azure-pipelines|ms-azure-devops|1.208.0|ms-azure-devops.azure-pipelines-1.208.0|
|csharp|ms-dotnettools|2.0.376|ms-dotnettools.csharp-2.0.376-win32-x64|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|jupyter|ms-toolsai|2023.7.1002162226|ms-toolsai.jupyter-2023.7.1002162226-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|LiveServer|ritwickdey|5.7.9|ritwickdey.liveserver-5.7.9|
|python|ms-python|2023.14.0|ms-python.python-2023.14.0|
|remote-containers|ms-vscode-remote|0.304.0|ms-vscode-remote.remote-containers-0.304.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-server|ms-vscode|1.4.0|ms-vscode.remote-server-1.4.0|
|remote-ssh|ms-vscode-remote|0.102.0|ms-vscode-remote.remote-ssh-0.102.0|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.0|ms-vscode-remote.remote-wsl-0.81.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.0|ms-dotnettools.vscode-dotnet-runtime-1.7.0|
|vscode-icons|vscode-icons-team|12.5.0|vscode-icons-team.vscode-icons-12.5.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-pylance|ms-python|2023.8.30|ms-python.vscode-pylance-2023.8.30|
|vscode-remote-extensionpack|ms-vscode-remote|0.24.0|ms-vscode-remote.vscode-remote-extensionpack-0.24.0|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-win32-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.0.376
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-11955M CPU @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (19.82GB free)|
|Process Argv|--crash-reporter-id 36f4e318-48cb-41b9-a6a4-2c1fee916159|
|Screen Reader|no|
|VM|0%|
</details>
 clipboard because it was too large to send. Please paste.

**Comment by dibarbet** [comment] 2023-08-19 23:10
Thanks this is a duplicate of https://github.com/dotnet/vscode-csharp/issues/6167 and will be fixed in the next release.

Note - even with this error the language server should function normally.

**Closed by dibarbet** 2023-08-19 23:10 UTC

**Comment by jediofgever** [comment] 2023-10-03 19:57
Has it been released?
