### ISSUE TITLE
 intellisense not show summary in vs code

### ISSUE THREAD

**Issue by mypursuit** [dotnet/vscode-csharp#6989] opened 2024-03-24 14:23 UTC
In the latest NET8 and Visual Studio Code create a webapi project ,but class summary does not work in Intellisense 

![image](https://github.com/dotnet/vscode-csharp/assets/10861805/a5537d9b-a69f-4f70-9bcf-516ebf408769)

Mouse hover the code after writed it，the summary show well
![image](https://github.com/dotnet/vscode-csharp/assets/10861805/c9098e16-0f89-4c75-91a8-827df978087a)

**Comment by dibarbet** [comment] 2024-03-25 20:02
@mypursuit vscode only shows documentation in the completion list if you click the arrow on the right side to expand it.  See the following:
![intellisense_docs](https://github.com/dotnet/vscode-csharp/assets/5749229/ad27a83e-9eaf-4491-a0d4-902d05c7fac2)

Going to close this issue as by design.

**Closed** 2024-03-25 20:03 UTC
Labels: Resolved-By Design, Triaged

**Comment by mypursuit** [comment] 2024-03-26 02:08
@dibarbet  Thank you very much
