### ISSUE TITLE
Text in quick info tooltips does not wrap

### ISSUE THREAD

**Issue by henry-js** [dotnet/vscode-csharp#6386] opened 2023-09-18 12:43 UTC
Type: <b>Bug</b>

## Steps to Reproduce ##
1. Create a c# project.
2. Call a standard system function ie File.Open().
3. Press `ctrl + space` on the FileMode parameter.

![image](https://github.com/dotnet/vscode-csharp/assets/79054685/d36b219c-cc00-4de1-b443-66e3fe348d2f)

## Expected Behavior ##
When pressing `ctrl + space` to view parameter information, the text description should wrap when reaching the end of the box.

## Actual Behavior ##
Text remains on a single line forcing the user to stretch the tooltip to read descriptions.
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>
```

[Trace - 1:38:42 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost] c:\\Users\\jhenry\\source\\repos\\streams\\Program.cs found in workspace Host"
}


[Trace - 1:38:42 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost] [12:38:42.059][Start]completionItem/resolve"
}


[Trace - 1:38:42 PM] Received response 'completionItem/resolve - (68)' in 6ms.
Result: {
    "label": "FileMode.Create",
    "kind": 20,
    "documentation": {
        "kind": "markdown",
        "value": "```csharp\r\nFileMode.Create = 2\r\n```\r\n  \r\nSpecifies&nbsp;that&nbsp;the&nbsp;operating&nbsp;system&nbsp;should&nbsp;create&nbsp;a&nbsp;new&nbsp;file\\.&nbsp;If&nbsp;the&nbsp;file&nbsp;already&nbsp;exists,&nbsp;it&nbsp;will&nbsp;be&nbsp;overwritten\\.&nbsp;This&nbsp;requires&nbsp;System\\.Security\\.Permissions\\.FileIOPermissionAccess\\.Write&nbsp;permission\\.&nbsp;FileMode\\.Create&nbsp;is&nbsp;equivalent&nbsp;to&nbsp;requesting&nbsp;that&nbsp;if&nbsp;the&nbsp;file&nbsp;does&nbsp;not&nbsp;exist,&nbsp;use&nbsp;FileMode\\.CreateNew;&nbsp;otherwise,&nbsp;use&nbsp;FileMode\\.Truncate\\.&nbsp;If&nbsp;the&nbsp;file&nbsp;already&nbsp;exists&nbsp;but&nbsp;is&nbsp;a&nbsp;hidden&nbsp;file,&nbsp;an&nbsp;UnauthorizedAccessException&nbsp;exception&nbsp;is&nbsp;thrown\\."
    },
    "sortText": "FileMode_0002",
    "textEdit": {
        "range": {
            "start": {
                "line": 3,
                "character": 40
            },
            "end": {
                "line": 3,
                "character": 41
            }
        },
        "newText": "FileMode.Create"
    },
    "commitCharacters": [
        " ",
        "{",
        "}",
        "[",
        "]",
        "(",
        ")",
        ".",
        ",",
        ":",
        ";",
        "+",
        "-",
        "*",
        "/",
        "%",
        "&",
        "|",
        "^",
        "!",
        "~",
        "=",
        "<",
        ">",
        "?",
        "@",
        "#",
        "'",
        "\"",
        "\\"
    ],
    "data": {
        "ResultId": 0
    }
}
```
## Environment information ##

**VSCode version**: 1.82.2
**C# Extension**: 2.2.10
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|auto-close-tag|formulahendry|0.5.14|formulahendry.auto-close-tag-0.5.14|
|auto-rename-tag|formulahendry|0.1.10|formulahendry.auto-rename-tag-0.1.10|
|better-comments|aaron-bond|3.0.2|aaron-bond.better-comments-3.0.2|
|codesnap|adpyke|1.3.4|adpyke.codesnap-1.3.4|
|codespaces|GitHub|1.15.2|github.codespaces-1.15.2|
|commitlint|joshbolduc|2.4.7|joshbolduc.commitlint-2.4.7|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10-win32-x64|
|csharp|ms-dotnettools|2.2.10|ms-dotnettools.csharp-2.2.10-win32-x64|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4461040|ms-dotnettools.dotnet-interactive-vscode-1.0.4461040|
|foam-vscode|foam|0.25.2|foam.foam-vscode-0.25.2|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|glsl-canvas|circledev|0.2.15|circledev.glsl-canvas-0.2.15|
|go|golang|0.39.1|golang.go-0.39.1|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|jupyter|ms-toolsai|2023.8.1002501831|ms-toolsai.jupyter-2023.8.1002501831-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|lorem-ipsum|Tyriar|1.3.1|tyriar.lorem-ipsum-1.3.1|
|markdown-all-in-one|yzhang|3.5.1|yzhang.markdown-all-in-one-3.5.1|
|markdown-emoji|bierner|0.3.0|bierner.markdown-emoji-0.3.0|
|markdown-mermaid|bierner|1.19.0|bierner.markdown-mermaid-1.19.0|
|material-icon-theme|PKief|4.30.1|pkief.material-icon-theme-4.30.1|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|output-colorizer|IBM|0.1.2|ibm.output-colorizer-0.1.2|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|python|ms-python|2023.16.0|ms-python.python-2023.16.0|
|rainbow-csv|mechatroner|3.7.1|mechatroner.rainbow-csv-3.7.1|
|remote-containers|ms-vscode-remote|0.309.0|ms-vscode-remote.remote-containers-0.309.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-ssh|ms-vscode-remote|0.106.4|ms-vscode-remote.remote-ssh-0.106.4|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|rust-analyzer|rust-lang|0.3.1665|rust-lang.rust-analyzer-0.3.1665-win32-x64|
|semantic-kernel|ms-semantic-kernel|0.9.4|ms-semantic-kernel.semantic-kernel-0.9.4|
|snippetica-csharp|josefpihrt-vscode|1.0.0|josefpihrt-vscode.snippetica-csharp-1.0.0|
|svg|jock|1.5.3|jock.svg-1.5.3|
|TabOut|albert|0.2.2|albert.tabout-0.2.2|
|theme-bluloco-dark|uloco|3.7.4|uloco.theme-bluloco-dark-3.7.4|
|theme-bluloco-light|uloco|3.7.3|uloco.theme-bluloco-light-3.7.3|
|vim|vscodevim|1.26.0|vscodevim.vim-1.26.0|
|vsc-community-material-theme|Equinusocio|1.4.6|equinusocio.vsc-community-material-theme-1.4.6|
|vsc-material-theme|Equinusocio|33.10.5|equinusocio.vsc-material-theme-33.10.5|
|vsc-material-theme-icons|equinusocio|3.0.4|equinusocio.vsc-material-theme-icons-3.0.4|
|vscode-autohotkey2-lsp|thqby|2.1.6|thqby.vscode-autohotkey2-lsp-2.1.6|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-markdownlint|DavidAnson|0.51.0|davidanson.vscode-markdownlint-0.51.0|
|vscode-paste-image|mushan|1.0.4|mushan.vscode-paste-image-1.0.4|
|vscode-peacock|johnpapa|4.2.2|johnpapa.vscode-peacock-4.2.2|
|vscode-postgresql|ms-ossdata|0.3.0|ms-ossdata.vscode-postgresql-0.3.0|
|vscode-pylance|ms-python|2023.9.10|ms-python.vscode-pylance-2023.9.10|
|vscode-sql-formatter|adpyke|1.4.4|adpyke.vscode-sql-formatter-1.4.4|
|vscode-tailwindcss|bradlc|0.10.0|bradlc.vscode-tailwindcss-0.10.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscode-zig|ziglang|0.4.3|ziglang.vscode-zig-0.4.3|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|
|webgl-glsl-editor|raczzalan|1.3.6|raczzalan.webgl-glsl-editor-1.3.6-win32-x64|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

Extension version: 2.2.10
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (2.85GB free)|
|Process Argv|--crash-reporter-id ddc56781-b0b1-44f0-97a9-e059279adce6|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dibarbet** [comment] 2023-09-18 21:02
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6275

Should be fixed in the next release

**Closed by dibarbet** 2023-09-18 21:02 UTC
