### ISSUE TITLE
csharp.referencesCodeLens.enabled DOESN'T WORK!!!! FIX IT ASAP!!!!!

### ISSUE THREAD

**Issue by vladkor-alt** [dotnet/vscode-csharp#6015] opened 2023-08-03 11:29 UTC
subj!!!!! FIX IT!!!!!! NOW!!!!!!!!

**Comment by KnorpelSenf** [comment] 2023-08-03 15:15
relax and install 1.x

**Comment by Kidsunbo** [comment] 2023-08-03 15:52
Just downgrade to previous version will fix the issue. But anyway, I switch to Rider.

**Comment by dibarbet** [comment] 2023-08-03 18:18
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5809

**Closed by dibarbet** 2023-08-03 18:18 UTC
