### ISSUE TITLE
Trying to open intellisense in an open file, while omnisharp is still loading causes "Ambiguity between ..." error

### ISSUE THREAD

**Issue by RononDex** [dotnet/vscode-csharp#2923] opened 2019-03-19 08:34 UTC
## Environment data
`dotnet --info` output:
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.103\

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.2.103 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

VS Code version: 1.32.3
C# Extension version: 1.17.1

## Steps to reproduce
1. Open Visual Studio Code (with a big .sln, that takes some time to load)
2. Have a .cs file already open from last vscode start (should automatically open last open files)
3. Try to open intellisense while omnisharp is still building intellisense
4. Intellisense will show symbols from within the file shortly after
5. After omnisharp has finished parsing everything in the .sln, it now shows an  "Ambiguity between ..." error on every symbol in that file.

## Expected  behavior
No  "Ambiguity between ..." errors

## Actual behavior
 "Ambiguity between ..." error on every symbol defined in that already open file

## My analysis on the issue
After trying to figure out how this happens, I think I was able to narrow it down:
Omnisharp has an internal Queue of all the files to parse. When a user tries to open intellisense inside an already open file, while mnisharp is still parsing the files from the selected .sln and the open file is still in that "queue"  and not parsed yet, it priorizes the opened file so it parses it first ( to ensure that intellisense works with at least the symbols defined in that open file). 

However, after "priority" parsing it, there is still an "old" entry in the queue from when omnisharp started parsing the .sln initially. This causes the file to be parsed twice in the end and  "Ambiguity between ..." errors appear

**Comment by akshita31** [comment] 2019-03-19 16:52
I think this should be fixed in the later versions of omnisharp. My guess is that we are adding the file as a miscellaneous file before the workspace has been completely initialized and the project also adds the file hence omnisharp thinks that there are two files hence the ambiguity error.

Could you try setting "omnisharp.path": "latest" and checking if the error still reproduces ?

**Comment by NTaylorMullen** [comment] 2019-03-19 16:56
@akshita31 had this happen yesterday to me with beta6 bits, for me it's super inconsistent/racey so never a reliable repro.

**Comment by rchande** [comment] 2019-03-19 17:19
@akshita31 I don't think that adding a file as a misc file and a regular file would have the effect you describe. Misc files go into a separate project that isn't referenced by anything, so I don't think the compiler would find the same type declared twice in the same project.

**Comment by NTaylorMullen** [comment] 2019-03-19 18:33
@danroth27 just ran into this guy too today with beta6 bits.

**Comment by rchande** [comment] 2019-03-19 18:34
@RononDex I can't reproduce this on the latest C# extension beta + latest omnisharp build. Do you have the option `"omnisharp.enableMsBuildLoadProjectsOnDemand"` set?

**Comment by rchande** [comment] 2019-03-19 18:34
@NTaylorMullen Can you guys move to beta-10?

**Comment by rchande** [comment] 2019-03-19 18:35
@NTaylorMullen, right, the razor thing. Can you set omnisharp.Path to 'latest'?

**Comment by NTaylorMullen** [comment] 2019-03-19 18:38
> @NTaylorMullen, right, the razor thing. Can you set omnisharp.Path to 'latest'?

Will give it a shot and report back if I see issues.

**Comment by danroth27** [comment] 2019-03-20 04:41
Looks like this was a Razor tooling specific issue.

**Comment by RononDex** [comment] 2019-03-20 08:53
@rchande the omnisharp related settings in my vscode config:
```json
    "omnisharp.disableMSBuildDiagnosticWarning": true,
    "omnisharp.maxFindSymbolsItems": 2000,
```

My omnisharp.json:
```json
{
	"RoslynExtensionsOptions": {
    "LocationPaths": [
      "C:\\Roslynator"
    ],
	"EnableAnalyzersSupport": true
  },
  "FormattingOptions": {
    "NewLine": "\r\n",
    "UseTabs": false,
    "TabSize": 4,
    "IndentationSize": 4,
    "SpacingAfterMethodDeclarationName": false,
    "SpaceWithinMethodDeclarationParenthesis": false,
    "SpaceBetweenEmptyMethodDeclarationParentheses": false,
    "SpaceAfterMethodCallName": false,
    "SpaceWithinMethodCallParentheses": false,
    "SpaceBetweenEmptyMethodCallParentheses": false,
    "SpaceAfterControlFlowStatementKeyword": true,
    "SpaceWithinExpressionParentheses": false,
    "SpaceWithinCastParentheses": false,
    "SpaceWithinOtherParentheses": false,
    "SpaceAfterCast": false,
    "SpacesIgnoreAroundVariableDeclaration": false,
    "SpaceBeforeOpenSquareBracket": false,
    "SpaceBetweenEmptySquareBrackets": false,
    "SpaceWithinSquareBrackets": false,
    "SpaceAfterColonInBaseTypeDeclaration": true,
    "SpaceAfterComma": true,
    "SpaceAfterDot": false,
    "SpaceAfterSemicolonsInForStatement": true,
    "SpaceBeforeColonInBaseTypeDeclaration": true,
    "SpaceBeforeComma": false,
    "SpaceBeforeDot": false,
    "SpaceBeforeSemicolonsInForStatement": false,
    "SpacingAroundBinaryOperator": "single",
    "IndentBraces": false,
    "IndentBlock": true,
    "IndentSwitchSection": true,
    "IndentSwitchCaseSection": true,
    "LabelPositioning": "oneLess",
    "WrappingPreserveSingleLine": true,
    "WrappingKeepStatementsOnSingleLine": true,
    "NewLinesForBracesInTypes": true,
    "NewLinesForBracesInMethods": true,
    "NewLinesForBracesInProperties": true,
    "NewLinesForBracesInAccessors": true,
    "NewLinesForBracesInAnonymousMethods": true,
    "NewLinesForBracesInControlBlocks": true,
    "NewLinesForBracesInAnonymousTypes": true,
    "NewLinesForBracesInObjectCollectionArrayInitializers": true,
    "NewLinesForBracesInLambdaExpressionBody": true,
    "NewLineForElse": true,
    "NewLineForCatch": true,
    "NewLineForFinally": true,
    "NewLineForMembersInObjectInit": true,
    "NewLineForMembersInAnonymousTypes": true,
    "NewLineForClausesInQuery": true
  }
}
```

(I used to test the roslyn analysers build with it)

**Comment by RononDex** [comment] 2019-03-20 09:00
@akshita31 if I use "omnisharp.path": "latest"
I get the following output in vscode Omsniharp log:
```
Error occured in loading omnisharp from omnisharp.path
Could not start the server due to Error: 404
```

**Comment by RononDex** [comment] 2019-03-20 16:40
@rchande @akshita31 Just tried with the beta10 release, still got the same issue (occurred with git checkout, checking out another branch)

**Comment by SirIntruder** [comment] 2019-03-21 18:21
It's true that when you start typing document is added to the MiscFilesProject, but OmnisharpWorkspace.TryPromoteMiscellaneousDocumentsToProject will add that misc document to the first project that is loaded if they are path of the same folder tree. This is just a heuristic and it could as well be wrong, problem is that there is no recovery mechanism when another project comes with a real hard reference to that file.

Proper fix for this would be if documents created by OmnisharpWorkspace.TryPromoteMiscellaneousDocumentsToProject would be marked as transient in BufferManager, so server would know that they should be removed if a "real" parent shows up.

**Comment by JoeRobich** [comment] 2024-11-12 00:09
A lot has changed with O# project loading since this issue was opened. If you are still having problems, please open a new issue.

**Closed by JoeRobich** 2024-11-12 00:09 UTC
Labels: OmniSharp
