### ISSUE TITLE
"Find references" does not show refs in .cshtml/razor files

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/vscode-csharp#7590] opened 2024-09-21 12:01 UTC
Type: <b>Bug</b>

## Issue Description ##

If a member is called from `.cshtml` file, it does not show up in "Find References"

## Steps to Reproduce ##

Call a (static) method in `.chtml` then use "Find References"

## Expected Behavior ##

Should show references **just like VS 2022** does

## Actual Behavior ##

Shows nothing

## Environment information ##

**VSCode version**: 1.93.1
**C# Extension**: 2.45.25
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.34944930
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

.NET workloads installed:
 [maccatalyst]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    17.2.8053/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8053\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    8.0.61/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.61\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    34.0.95/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.95\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: VS 17.10.35122.118
   Manifest Version:    8.0.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|copilot|GitHub|1.232.0|github.copilot-1.232.0|
|copilot-chat|GitHub|0.20.3|github.copilot-chat-0.20.3|
|csdevkit|ms-dotnettools|1.10.18|ms-dotnettools.csdevkit-1.10.18-win32-x64|
|csharp|ms-dotnettools|2.45.25|ms-dotnettools.csharp-2.45.25-win32-x64|
|eml|leighlondon|0.4.0|leighlondon.eml-0.4.0|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|remote-wsl|ms-vscode-remote|0.88.3|ms-vscode-remote.remote-wsl-0.88.3|
|vscode-dotnet-runtime|ms-dotnettools|2.1.5|ms-dotnettools.vscode-dotnet-runtime-2.1.5|
|vscode-icontheme-nomo-dark|be5invis|1.3.6|be5invis.vscode-icontheme-nomo-dark-1.3.6|
|vscode-innosetup|chouzz|1.9.3|chouzz.vscode-innosetup-1.9.3|
|vscode-tailwindcss|bradlc|0.12.10|bradlc.vscode-tailwindcss-0.12.10|
|vscode-yaml|redhat|1.15.0|redhat.vscode-yaml-1.15.0|;

</details>

Extension version: 2.45.25
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by dibarbet** [comment] 2024-09-24 17:50
dupe of https://github.com/dotnet/razor/issues/9804

**Closed by dibarbet** 2024-09-24 17:50 UTC
