### ISSUE TITLE
Cannot execute 2 times debug of unit test

### ISSUE THREAD

**Issue by tsalinger** [dotnet/vscode-csharp#2106] opened 2018-03-13 07:59 UTC
>This issue has been moved from [Microsoft/vscode/](https://github.com/Microsoft/vscode/issues/45618)
Author is @massimilianokraus.
---
Issue Type: <b>Bug</b>

Just the official C# extension.
MSTest unit test.
I click the little gray "debug test" under the TestMethod Attribute. The first time the unit test is executed well.
But if I click again "debug test", in the output it says "Debugging method <method-name>...", and it remains blocked there forever.
I must close the window and reopen it to make the unit test debugging to work again.
Only if I put a breakpoint at the end and do "stop" at runtime, it works multiple times.

VS Code version: Code 1.21.0 (9a199d77c82fcb82f39c68bb33c614af01c111ba, 2018-03-07T10:54:22.798Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron .|
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|1.9.2
vscode-eslint|dba|1.4.7
tslint|eg2|1.0.28
dotnet|for|0.0.3
dotnet-test-explorer|for|0.2.0
vscode-yarn|gam|1.6.0
vscode-nuget-package-manager|jmr|1.1.6
vscodeilviewer|jos|0.0.1
mssql|ms-|1.3.0
csharp|ms-|1.14.0
debugger-for-chrome|msj|4.2.0
oracle-plsql|myc|1.0.3
vetur|oct|0.11.7
vscode-sort-json|ric|1.11.0
aspnet-helper|sch|0.6.4

</details>
Reproduces only with extensions

---

**Comment by rchande** [comment] 2018-03-14 18:43
@akshita31 Want to take a look?

**Comment by rchande** [comment] 2018-03-14 21:17
Repros on OS X, not Windows.

**Comment by dmccaffery** [comment] 2018-05-03 02:12
FWIW, this has been driving me nuts for ages ;-) Its hit/miss.

**Comment by xivk** [comment] 2018-05-09 09:32
I can reproduce this on Ubuntu 16.04 and @pietervdvn on Ubuntu 17.10

**Comment by DanielSSilva** [comment] 2018-05-19 15:50
As in the referenced issue above, I also have this problem on Mint 18.3. In my case I also lose Intellinsense

**Comment by akshita31** [comment] 2018-05-23 19:02
I can definitely reproduce this problem. On setting a breakpoint I realised that somehow we are closing the socket so an exception is occuring. I am investigating further. Thanks a lot @tsalinger for filing this

**Comment by akshita31** [comment] 2018-05-23 22:21
@gregg-miskelly @DustinCampbell I tried to understand the issue here and seems that we are closing the socket to the omnisharp server somehow. I tried several times but this issue doesn't reproduce on Windows. Any idea what might be going wrong ? 
cc @rchande

**Comment by akshita31** [comment] 2018-05-23 23:04
In omnisharp-roslyn we are getting the exception - "System.InvalidOperationException: Debug session already started".

**Comment by nwise** [comment] 2018-08-11 19:57
+1 for a solution to this

**Comment by trydis** [comment] 2018-08-14 10:43
Another +1

**Comment by bertrand-benoit** [comment] 2019-02-01 13:33
Another +1

**Comment by trackingallday** [comment] 2020-06-11 21:37
Another + 1

**Comment by JoeRobich** [comment] 2024-11-11 21:35
A lot has changed with unit testing since this issue was opened. If you are still running into problems, please open a new issue.

**Closed by JoeRobich** 2024-11-11 21:35 UTC
Labels: Bug, OmniSharp, Test
