### ISSUE TITLE
getting error running/debugging dotnet application

### ISSUE THREAD

**Issue by chadams** [dotnet/vscode-csharp#7252] opened 2024-06-20 19:35 UTC
Type: <b>Bug</b>

## Issue Description ##
getting error running/debugging dotnet application

## Steps to Reproduce ##
1. Created a dotnet MVC web app with no edits.
2. then ran debugger

## Expected Behavior ##
expect to see starter app web page

## Actual Behavior ##

open(vsdbg, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.90.2
**C# Extension**: 2.34.12
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.302/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  1.0.1 [/usr/local/share/dotnet/sdk]
  6.0.423 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]
  8.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|bun-vscode|oven|0.0.12|oven.bun-vscode-0.0.12|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|csdevkit|ms-dotnettools|1.7.27|ms-dotnettools.csdevkit-1.7.27-darwin-x64|
|csharp|ms-dotnettools|2.34.12|ms-dotnettools.csharp-2.34.12-darwin-x64|
|dotenv|mikestead|1.0.1|mikestead.dotenv-1.0.1|
|error-gutters|IgorSbitnev|1.0.1|igorsbitnev.error-gutters-1.0.1|
|gitlens|eamodio|15.1.0|eamodio.gitlens-15.1.0|
|headwind|heybourn|1.7.0|heybourn.headwind-1.7.0|
|lit-plugin|runem|1.4.3|runem.lit-plugin-1.4.3|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|sort-typescript-imports|miclo|1.4.1|miclo.sort-typescript-imports-1.4.1|
|Theme-FlatlandMonokai|gerane|0.0.6|gerane.theme-flatlandmonokai-0.0.6|
|Theme-Zeus-Sublime-Text|gerane|0.0.5|gerane.theme-zeus-sublime-text-0.0.5|
|todo-tree|Gruntfuggly|0.0.226|gruntfuggly.todo-tree-0.0.226|
|vscode-docker|ms-azuretools|1.29.1|ms-azuretools.vscode-docker-1.29.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.6|ms-dotnettools.vscode-dotnet-runtime-2.0.6|
|vscode-dotnet-watch|Murugaratham|1.1.8|murugaratham.vscode-dotnet-watch-1.1.8|
|vscode-eslint|dbaeumer|3.0.10|dbaeumer.vscode-eslint-3.0.10|
|vscode-jest|Orta|6.2.5|orta.vscode-jest-6.2.5|
|vscode-status-bar-format-toggle|tombonnike|3.2.0|tombonnike.vscode-status-bar-format-toggle-3.2.0|
|vscode-tailwindcss|bradlc|0.10.5|bradlc.vscode-tailwindcss-0.10.5|
|vscode-todo-highlight|wayou|1.0.5|wayou.vscode-todo-highlight-1.0.5|;

</details>

Extension version: 2.34.12
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin x64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 8, 6|
|Memory (System)|16.00GB (2.10GB free)|
|Process Argv|. --crash-reporter-id 0fdb6d2d-c3ee-4c94-b509-f4602766d95b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by WardenGnaw** [comment] 2024-06-20 23:49
Duplicate of #7251

**Closed by WardenGnaw** 2024-06-20 23:49 UTC
