### ISSUE TITLE
Fails to load any project using .NET 8 Preview 7

### ISSUE THREAD

**Issue by alexrp** [dotnet/vscode-csharp#6081] opened 2023-08-09 09:00 UTC
## Issue Description ##

The C# extension fails to load any project that is configured to use .NET 8 Preview 7 via `global.json`.

## Steps to Reproduce ##

```console
$ dotnet new globaljson
$ dotnet new console
$ code .
```

(With .NET 8 Preview 7 SDK installed.)

## Expected Behavior ##

The project should load.

## Actual Behavior ##

It doesn't; the status bar shows the project as failing to load and IntelliSense is broken.

## Logs ##

C# and C# LSP Trace Logs here: https://gist.github.com/alexrp/1eed0672e9511580361e1960e37babda

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found</details>

<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cake-vscode|cake-build|2.1.1|cake-build.cake-vscode-2.1.1|
|csdevkit|ms-dotnettools|0.3.21|ms-dotnettools.csdevkit-0.3.21-win32-x64|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-win32-x64|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|gitconfig-lsp|yy0931|0.10.0|yy0931.gitconfig-lsp-0.10.0|
|github-code-owners|chdsbd|3.1.0|chdsbd.github-code-owners-3.1.0|
|gitignore|codezombiech|0.9.0|codezombiech.gitignore-0.9.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|live-server|ms-vscode|0.4.9|ms-vscode.live-server-0.4.9|
|msbuild-project-tools|tintoy|0.4.9|tintoy.msbuild-project-tools-0.4.9|
|remote-wsl|ms-vscode-remote|0.81.0|ms-vscode-remote.remote-wsl-0.81.0|
|svg|jock|1.5.3|jock.svg-1.5.3|
|vscode-clangd|llvm-vs-code-extensions|0.1.24|llvm-vs-code-extensions.vscode-clangd-0.1.24|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-firefox-debug|firefox-devtools|2.9.8|firefox-devtools.vscode-firefox-debug-2.9.8|
|vscode-github-actions|github|0.26.1|github.vscode-github-actions-0.26.1|
|vscode-html-css|ecmel|1.13.1|ecmel.vscode-html-css-1.13.1|
|vscode-markdownlint|DavidAnson|0.51.0|davidanson.vscode-markdownlint-0.51.0|
|vscode-proto3|zxh404|0.5.5|zxh404.vscode-proto3-0.5.5|
|vscode-pull-request-github|GitHub|0.70.0|github.vscode-pull-request-github-0.70.0|
|vscode-remote-extensionpack|ms-vscode-remote|0.24.0|ms-vscode-remote.vscode-remote-extensionpack-0.24.0|
|vscode-systemd-support|hangxingliu|1.0.1|hangxingliu.vscode-systemd-support-1.0.1|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-win32-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscode-zig|ziglang|0.4.3|ziglang.vscode-zig-0.4.3|;

</details>

**Comment by dibarbet** [comment] 2023-08-10 01:20
Thanks - it looks like you're using devkit.  This is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/318

**Closed by dibarbet** 2023-08-10 01:20 UTC

**Comment by alexrp** [comment] 2023-08-10 08:19
Just for future reference, is there a rule of thumb for which of the two repos I should be filing bugs on?
