### ISSUE TITLE
Extension stops indexing .razor (Blazor) component files after a certain number unless you open the file.

### ISSUE THREAD

**Issue by TrieBr** [dotnet/vscode-csharp#6921] opened 2024-02-25 19:33 UTC
## Issue Description ##

I think I finally found the main issue preventing me from using VS Code.

I have `dotnet.backgroundAnalysis.compilerDiagnosticsScope` and `dotnet.backgroundAnalysis.analyzerDiagnosticsScope` both set to `fullSolution` and `csharp.maxProjectFileCountForDiagnosticAnalysis` set to 9999999999. However it appears that the extension ignores this setting for razor files. After a certain number of razor files, you end up with tons of "Found markup element with unexpected name "SomeComponent" errors until you go open `SomeComponent.razor`

## Steps to Reproduce ##

1. Clone my test repo here.
```
git clone -b test-large-solution https://github.com/TrieBr/blazor-input-bug.git
```
2. Open `BlazorInputBug/InputBug/Pages/Counter.razor`. Notice that "InputTextFour" is underlined and an error shows `Found markup element with unexpected name 'InputTextFour'. If this is intended to be a component, add a @using directive for its namespace.`. NOTE: Sometimes (flaky) it does work, but you can rename the component to something else like `InputTextFive` or `InputTextSix` and observe the same behavior.

3. Open `BlazorInputBug/InputBug/Shared/Inputs/InputTextFour.razor`. Then go back to `BlazorInputBug/InputBug/Pages/Counter.razor` and observe the problem goes away.

4. Delete most of the other files (`BlazorInputBug/InputBug/Shared/Inputs/InputText{11..50.razor}`) and command pallete => reload the window. The problem goes away. You can change between `InputTextTwo`, `InputTextThree`, `InputTextFour`, etc and they all work.

5. Re-add more files (`for i in {11..50}; do cp InputText.razor "InputText$i.razor"; done`, reload the window and see the problem comes back. You change between `InputTextTwo`, `InputTextThree`, `InputTextFour`, etc and is starts to say "Found markup element with unexpected name"

## Expected Behavior ##

When dotnet.backgroundAnalysis.compilerDiagnosticsScope is set to `fullSolution`, all razor files should be indexed, and I shouldn't have to go open the ".razor" file to get rid of reference errors.

## Actual Behavior ##

After enough razor files in the solution (my tests seem to break at only 50, but i didn't bisect a smaller number). Intellesense stop working for Blazor components

## Logs ##

[Archive.zip](https://github.com/dotnet/vscode-csharp/files/14397547/Archive.zip)
        
### C# log ###
https://pastebin.com/xwDQQM8k

### C# LSP Trace Logs ###
https://pastebin.com/KrCEXRNw

**Comment by davidwengier** [comment] 2024-02-26 04:43
Like https://github.com/dotnet/vscode-csharp/issues/6852, seems like our closed file support might have stopped working.

**Comment by karanveersp** [comment] 2024-04-12 20:17
Hmm. I think I'm seeing this too. I just created a new Blazor server app using the dotnet CLI and the `PageTitle` component, along with all the other components referenced in the `_Imports.razor` file all highlight as red, unrecognized tags.
![Screenshot 2024-04-12 at 4 13 32 PM](https://github.com/dotnet/vscode-csharp/assets/7011511/4c890a90-86f1-486e-9e40-99ed12443d5c)

**Comment by danielscatigno-ncpc** [comment] 2024-05-16 15:29
I'm also facing this problem and one workaround I Found is to create a code behind class for the Component or Razor page

**Comment by ktravelet** [comment] 2024-08-16 04:48
I'm facing this issue on M1 mac. The issue is that I cant reliably reproduce it. It seems to appear after renaming files and all goes crazy afterwords. I havent figured out a consistent workaround either

**Comment by ryzngard** [comment] 2024-08-27 01:11
> it seems to appear after renaming files and all goes crazy afterwords. I havent figured out a consistent workaround either

This seems to be a new repro. The current issue has 100% repro and we believe we have a fix. @ktravelet can you file a separate issue when you get into that state? The best thing to do would be set razor logs to trace in your `settings.json` with `"razor.server.trace": "Trace"` and when you hit the issue use the `Razor: report an issue` command

**Comment by ryzngard** [comment] 2024-10-21 21:15
I'm going to close this for now. Known issues are fixed. If you are still having issues please file a new feedback item

**Closed by ryzngard** 2024-10-21 21:15 UTC
Labels: Razor

**Comment by TrieBr** [comment] 2024-10-21 22:21
Thanks @ryzngard! I just want to say I tried VSCode recently and was surprised to see how much better intellisense is working for razor files now. Thanks for all your work on this!
