### ISSUE TITLE
Argument completion pops up when function has no arguments

### ISSUE THREAD

**Issue by Kotsuha** [dotnet/vscode-csharp#6374] opened 2023-09-15 06:59 UTC
Type: <b>Bug</b>

## Steps to Reproduce ##

1. In Unity, create a Test script.
2. Copy-paste this example: https://docs.unity3d.com/2019.1/Documentation/ScriptReference/TestTools.Constraints.AllocatingGCMemoryConstraint.html

3. Place the cursor at the end of `Is.AllocatingGCMemory`. Press `(`.

## Expected Behavior ##

VSCode should show a pop-up describing the method description and arguments.

## Actual Behavior ##

Two pop-ups are shown. The first one is not as expected.

![vscode-csharp-extension-issue](https://github.com/dotnet/vscode-csharp/assets/10438710/275a06a0-a666-418b-8ed5-b0ba1cf1b381)

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.82.1
**C# Extension**: 2.2.10
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10|
|csharp|ms-dotnettools|2.2.10|ms-dotnettools.csharp-2.2.10|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|
|vscode-settings-cycler|hoovercj|1.0.1|hoovercj.vscode-settings-cycler-1.0.1|
|vstuc|visualstudiotoolsforunity|0.9.0|visualstudiotoolsforunity.vstuc-0.9.0|;

</details>

Extension version: 2.2.10
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz (16 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.23GB free)|
|Process Argv|--crash-reporter-id 4f340c22-f013-4a44-bdbc-3bf3283d34dc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30835153
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by dibarbet** [comment] 2023-09-15 22:41
Both popups are expected and appear to be correct.  However generally you should be seeing both at once - the completion at the bottom and signature help above.
E.g.
<img width="479" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/982d1803-041b-4e15-822d-8b89ed217bf5">

If however, the bottom of the window is too close to the cursor, vscode will show the completion list up top, which covers signature help.  You can see signature help in the background in your screenshot.  You can dismiss completion by hitting escape.

The only thing we could do on the extension side is disable completion in argument lists, which we do not wish to do.  We don't control the rendering here.
I'm closing this as by design

**Comment by Kotsuha** [comment] 2023-09-16 11:31
@dibarbet Thank you for taking a look at this. I believe the `Is.AllocatingGCMemory()` takes zero parameters...? That's why I do not expect to see the first pop-up. In the GIF I posted, you can see the second pop-up does not show any overloads.

**Comment by dibarbet** [comment] 2023-09-18 18:57
@Kotsuha ah I see now.   Assigning to @genlu to see if we want to disable completion if the function has no parameters.

**Comment by levanlongktmt** [comment] 2023-10-11 02:03
I have the same problem, argument completion is so useless, no matter what type of function parameter, it always suggests by the alphabet of class, variables, namespace, etc...
<img width="1088" alt="Screenshot 2023-10-11 at 8 59 00 AM" src="https://github.com/dotnet/vscode-csharp/assets/9171324/20be4835-73f2-4dcc-9d40-94586f60b164">
<img width="1058" alt="Screenshot 2023-10-11 at 8 59 22 AM" src="https://github.com/dotnet/vscode-csharp/assets/9171324/1ad2771f-6480-4426-bf4e-ca71ea0badb6">

**Comment by genlu** [comment] 2023-11-13 21:39
@levanlongktmt Yea I hear you. The original motivation for triggering in argument list in C# (in VS) is that the intellicode would suggest the likely item via "starred item", plus we have a "target type filter" in VS that would filter down the list to items fit the inferred type in current context. Neither of these are available in C# extension in vs code.

@dibarbet maybe we should have this option disabled in C# extension by default unless intellicode is available?

**Comment by dibarbet** [comment] 2023-11-13 21:50
> @dibarbet maybe we should have this option disabled in C# extension by default unless intellicode is available?

I'm not opposed to that idea, but it will require some additional work.  I don't believe VSCode allows us to change the default value of an option based on the presence of an extension.  

But maybe we can potentially detect if any of the settings.json contains a value for the setting, and if not choose the default based on the activation of the intellicode extension?  We would have to insert that into the [option middle layer though](https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/configurationMiddleware.ts) (since the option value gets sent directly from vscode to the server).

**Comment by genlu** [comment] 2023-11-13 22:45
Filed https://github.com/dotnet/vscode-csharp/issues/6665 to track the unaddressed issue (when invoked method does accept arguments)

**Closed** 2023-11-14 23:49 UTC
Labels: Triaged
