### ISSUE TITLE
Missing Command Error

### ISSUE THREAD

**Issue by PaitoAnderson** [dotnet/vscode-csharp#3003] opened 2019-04-17 18:26 UTC
## Issue Description ##

I just started getting this today, where sometimes it shows `!!MISSING: command!!` above a class instead of the references count, restarting VSCode didn't help.

## Steps to Reproduce ##

Open .cs file

## Expected Behavior ##

`0 references`

## Actual Behavior ##

`!!MISSING: command!!`
<img width="345" alt="Screen Shot 2019-04-17 at 2 16 11 PM" src="https://user-images.githubusercontent.com/4108718/56311353-d1009b80-611b-11e9-8ed1-1ef47c808f8e.png">

### OmniSharp log ###
<details>Starting OmniSharp server at 4/17/2019, 2:16:48 PM
    Target: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.sln

OmniSharp server started with Mono 5.18.1.
    Path: /Users/REDACTED/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/OmniSharp.exe
    PID: 10458

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 10.14.4 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            2: StandAlone 15.0 - "/Users/REDACTED/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Mono 15.0 - "/Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin"
            CscToolPath = /Users/REDACTED/.vscode/extensions/ms-vscode.csharp-1.19.0/.omnisharp/1.32.18/omnisharp/.msbuild/Current/Bin/Roslyn
            CscToolExe = csc.exe
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/REDACTED/Developer/REDACTEDWeb/src'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.WorkspaceInitializer
        Project system 'OmniSharp.DotNet.DotNetProjectSystem' is disabled in the configuration.
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.sln'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.Tests/REDACTED.REDACTED.Tests.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.REDACTED/REDACTED.REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/REDACTED/Developer/REDACTEDWeb/src'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpWorkspaceOptionsProvider
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/REDACTED/Developer/REDACTEDWeb/src' on host 10408.
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Microsoft.CodeAnalysis.Analyzers.MetaAnalyzers.CodeFixes.ApplyDiagnosticAnalyzerAttributeFix' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.Tests/REDACTED.REDACTED.Tests.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.Tests/REDACTED.REDACTED.Tests.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.Tests/REDACTED.REDACTED.Tests.csproj'
[info]: OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.CachingCodeFixProviderForProjects
        Skipping code fix provider 'Xunit.Analyzers.FixProviders.MemberFixBase' because it's language doesn't match 'C#'.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.REDACTED/REDACTED.REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.REDACTED/REDACTED.REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED.REDACTED/REDACTED.REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/REDACTED/Developer/REDACTEDWeb/src/REDACTED.REDACTED/REDACTED.REDACTED.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED.Tests
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED.REDACTED
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: REDACTED.REDACTED
</details>

### C# log ###
Blank

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Mono Information</summary>
        OmniSharp using global mono :5.18.1</details>
<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.106
 Commit:    aa79b139a8

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.106/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.101 [/usr/local/share/dotnet/sdk]
  2.1.200 [/usr/local/share/dotnet/sdk]
  2.1.300 [/usr/local/share/dotnet/sdk]
  2.1.301 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.19.0|
|dart-code|Dart-Code|2.25.1|
|EditorConfig|EditorConfig|0.13.0|
|flutter|Dart-Code|2.25.1|
|msbuild-project-tools|tintoy|0.2.54|
|prettier-vscode|esbenp|1.8.1|
|vscode-react-native|vsmobile|0.9.2|
|vscode-typescript-tslint-plugin|ms-vscode|1.0.0|
|vscodeintellicode|VisualStudioExptTeam|1.1.5|
|vsliveshare|ms-vsliveshare|1.0.45|;

</details>

**Comment by Hardhik** [comment] 2019-04-24 19:10
Surprisingly, I saw this today in the Visual Studio IDE too.

**Comment by akshita31** [comment] 2019-04-25 00:28
@PaitoAnderson That is awkward. Can you share the repro project. Does it reproduce when all other extensions are disbaled?

**Comment by PaitoAnderson** [comment] 2019-04-25 02:20
@akshita31 Yes it does, unfortunately it's not open source, what's the best way to securely share repro project with you? My email is on my profile.

**Comment by akshita31** [comment] 2019-04-25 18:25
@PaitoAnderson Can you send it over email - akagarw@microsoft.com

**Comment by aspann** [comment] 2019-04-27 15:02
I've ran into the same issue today. Solution for me was to change the `"omnisharp.useGlobalMono"` back to `"auto"` in the settings.json. (or simply remove that line. `"auto"` is the default value)

The problem might be related to an update of mono and/or MSBuild.

MSBuild: 15.9.20.62856
Mono: 5.20.1.19

**Comment by anorborg** [comment] 2019-05-16 17:31
I've hit this as well in one of my repos. I attempted to to create a minimal repo to reproduce, but unfortunately wasn't able to. I tried disabling all other extensions and also verified my `omnisharp.useGlobalMono` setting was `auto` (though I do not have mono installed separately).

## Environment Information:
**VS Code**: 1.33.1
**C# Extension**:  1.19.1

<details><summary>dotnet --info</summary>
.NET Core SDK (reflecting any global.json):
 Version:   2.2.203
 Commit:    e5bab63eca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.203/

Host (useful for support):
  Version: 2.2.4
  Commit:  f95848e524

.NET Core SDKs installed:
  2.2.101 [/usr/local/share/dotnet/sdk]
  2.2.203 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>

**Comment by akshita31** [comment] 2019-05-16 17:34
@anorborg Can you try setting "omnisharp.useGlobalMono": never. That way omnisharp will use the built-in version of mono.

**Comment by anorborg** [comment] 2019-05-16 17:45
@akshita31 no change unfortunately. If it helps, the behavior it appears to be isolated to a particular interface and implementation. The intellisense will not register an error if the interface isn't implemented, however i'll still get a standard build error. When I implement I am able to build and run, but the implemented method has the "MISSING: command"

**Comment by ivars001** [comment] 2019-05-27 11:29
@akshita31 Thanks! Worked for me

**Comment by bmolnar2** [comment] 2019-10-05 07:47
> @anorborg Can you try setting "omnisharp.useGlobalMono": never. That way omnisharp will use the built-in version of mono.

This one worked for me too, thanks. Seems like solved the missing AssemblyResolve issue as well.

**Comment by paulhannon0** [comment] 2021-01-12 09:26
Was there ever a solution for this besides the useGlobalMono workaround? None of the options for that setting have had any effect for me. I've never had this issue before, only just started appearing.

**Comment by doivosevic** [comment] 2021-02-22 10:15
I'm encountering this issue when working on a Rust project. I don't have C# related tooling installed

**Comment by dergyitheron** [comment] 2021-03-21 20:12
I am having this issue as well with Rust project. I have OmniSharp installed as well. Tried updating an restarting, nothing seems to be working. Using rust-analyzer.

**Comment by equt** [comment] 2021-03-29 02:46
The bug has been fixed in the rust-analyzer and will be available in the [next release](https://github.com/rust-analyzer/rust-analyzer/pull/8183).

Not sure what causes this in omnisharp-vscode, but it seems to occur when the macro expands or annotations being generated by VS Code,

> ..., this appears when annotations can't be resolved(the 135 implementations thing that appears above structs and the like), this resolving failure happens when macros create items currently which then appears at the top of the file as the text ranges are mapped incorrectly, ...

quote from https://github.com/rust-analyzer/rust-analyzer/issues/8218, hope it could help :).

**Comment by jsoref** [comment] 2021-05-27 17:35
Fwiw, I triggered
![image](https://user-images.githubusercontent.com/2119212/119871251-44c32400-bef0-11eb-88f5-7e6f83989be3.png)

By clicking one of the (git) merge marker resolution links and this appeared roughly where one of the merge markers was.

**Comment by Andy-AO** [comment] 2021-12-17 22:56
> @anorborg Can you try setting "omnisharp.useGlobalMono": never. That way omnisharp will use the built-in version of mono.

Thanks it worked for me, after restart vscode.

**Comment by cyqsimon** [comment] 2022-12-27 11:28
This problem doesn't seem to be language-specific. I was writing a handlebars template and got this. This is some CSS in the `<style>` element of a `.hbs` file: ![screenshot](https://user-images.githubusercontent.com/28627918/209658637-270c44c1-121d-4451-96fe-eca30dbcf68b.png)

In my specific case I was able to isolate the problem to the GitLens extension. I think it's related to those two issues: https://github.com/gitkraken/vscode-gitlens/issues/1220, https://github.com/gitkraken/vscode-gitlens/issues/2209.

**Comment by jsoref** [comment] 2022-12-27 14:32
> This problem doesn't seem to be language-specific.

@cyqsimon: indeed it isn't.
... but the VSCode ecosystem is extremely hostile to filing bugs against its core.

If you aren't a core contributor, I wouldn't suggest spending the time trying to convince them to Do The Right Thing™. There are brick walls that would be more comfortable and satisfying banging your head against.

**Comment by archer884** [comment] 2023-02-19 00:02
Shit's still broke, yo.

**Comment by mihailik** [comment] 2023-07-14 10:47
What is this?

`!!MISSING: command!! | !!MISSING: command!!`

I don't have any **OmniSharp** installed, but still get the issue.

<img width="464" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/4041967/571db682-f0bb-47e2-a221-4b5d3a336b47">

**Comment by twatkins-skyhop** [comment] 2023-07-14 21:06
Same on a golang repo. Was actually only looking to see the git blame info for a function, but anything below this omits it. Even to 8 lines above it just in the middle of an arbitrary multiline var initialization. The git blame just stops there. All the other hover actions work just fine. Nothing wrong with the file as far as golang is concerned.

Interestingly, it appears on an interface as with the above commenter. Hover actions for this line work fine too.
<img width="789" alt="Screenshot 2023-07-14 at 3 04 24 PM" src="https://github.com/dotnet/vscode-csharp/assets/129192195/7cec1421-4fa9-4abe-a879-fb5ba622f75d">

**Comment by JoeRobich** [comment] 2024-11-12 00:22
A lot has changed with O# startup since this issue was opened. If you are still having problems, please open a new issue.

**Closed by JoeRobich** 2024-11-12 00:22 UTC
Labels: Bug, OmniSharp
