### ISSUE TITLE
Problems Window - Error States "Unable to open: File not found"

### ISSUE THREAD

**Issue by DanJ210** [dotnet/vscode-csharp#3040] opened 2019-05-02 22:34 UTC
Posted this in VS Code first and they said that this was a C# extension issue and to post here.

This happens every now and then but often enough. I'll be shown errors and clicking on some will state that the file does not exist. There is a duplicate set of the same errors from the same file below. Both show a slightly different path. Have no idea what's happening here.

Is this workaround what you have to do with every project to ensure you don't get this issue?

In the .csproj add <GenerateFullPaths>true</GenerateFullPaths> inside <PropertyGroup></PropertyGroup>

![image](https://user-images.githubusercontent.com/16159685/57109245-f3d9a500-6d02-11e9-8291-51402d2e6cde.png)

![image](https://user-images.githubusercontent.com/16159685/57111020-9e07fb80-6d08-11e9-8d27-e5817a3966ea.png)

- VSCode Version: 1.33.1
- OS Version: 1803

Steps to Reproduce:

1. Very hard to reproduce. Seems random. Been running the same .Net Core app all day. All of a sudden this happened.
2. Doesn't seem like it has steps to reproduce.
3. Occurs with all extensions disabled.

Does this issue occur when all extensions are disabled?: Yes

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.33.1
**C# Extension**: 1.19.0

<details><summary>Dotnet Information</summary>
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview-010184
 Commit:    c57bde4593

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview-010184\

Host (useful for support):
  Version: 3.0.0-preview-27324-5
  Commit:  63a01b08e5

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009472 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.200 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  3.0.100-preview-010184 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview-19075-0444 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview-27324-5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview-27325-3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|auto-close-tag|formulahendry|0.5.6|
|auto-rename-tag|formulahendry|0.0.15|
|azure-account|ms-vscode|0.8.2|
|beautify|HookyQR|1.4.11|
|csharp|ms-vscode|1.19.0|
|debugger-for-chrome|msjsdiag|4.11.3|
|debugger-for-edge|msjsdiag|1.0.8|
|dotnet-core-essentials|KishoreIthadi|0.0.6|
|dotnet-test-explorer|formulahendry|0.6.6|
|gitlens|eamodio|9.6.3|
|JavaScriptSnippets|xabikos|1.7.2|
|minify|HookyQR|0.4.3|
|mssql|ms-mssql|1.6.0|
|npm-intellisense|christian-kohler|1.3.0|
|nuget-reverse-package-search|jesschadwick|0.1.68|
|path-intellisense|christian-kohler|1.4.2|
|php-debug|felixfbecker|1.13.0|
|php-intellisense|felixfbecker|2.3.10|
|team|ms-vsts|1.149.2|
|theme-tinaciousdesign|tinaciousdesign|0.2.6|
|tslint-vue|prograhammer|1.5.6|
|vetur|octref|0.19.3|
|vscode-azureappservice|ms-azuretools|0.14.0|
|vscode-azurefunctions|ms-azuretools|0.17.0|
|vscode-docker|PeterJausovec|0.6.1|
|vscode-gitignore-generator|piotrpalarz|1.0.1|
|vscode-great-icons|emmanuelbeziat|2.1.47|
|vscode-icons|vscode-icons-team|8.6.0|
|vscode-npm-script|eg2|0.3.5|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vscodeintellicode|VisualStudioExptTeam|1.1.5|
|vsliveshare|ms-vsliveshare|1.0.125|
|vsliveshare-audio|ms-vsliveshare|0.1.50|
|vue-peek|dariofuzinato|1.0.2|
|vuejs-extension-pack|mubaidr|1.1.3|
|wilderminds-aspnetcore-snippets|wilderminds|0.2.1|
|xml|DotJoshJohnson|2.4.0|
|yo|samverschueren|0.9.3|;

</details>

**Comment by DanJ210** [comment] 2019-06-18 15:53
Still getting this issue quite often.

**Comment by rchande** [comment] 2019-06-18 20:39
@DanJ210 This sounds like a duplicate of https://github.com/OmniSharp/omnisharp-vscode/issues/1197 -- can you try the workaround discussed in that issue?

**Comment by DanJ210** [comment] 2019-06-19 15:30
It sounds like the same issue. I suppose I can try the workaround.

**Comment by dombarnes** [comment] 2019-10-17 08:32
Issue #1197 suggests this has now been fixed but I am still seeing the issues in v1.21.5 of the C# Extension

**Comment by JoeRobich** [comment] 2024-11-12 00:35
Cannot reproduce this with the current release.

**Closed by JoeRobich** 2024-11-12 00:35 UTC
Labels: OmniSharp
