### ISSUE TITLE
Intellisense Not Working

### ISSUE THREAD

**Issue by kbvatral** [dotnet/vscode-csharp#6376] opened 2023-09-15 12:36 UTC
## Environment data
`dotnet --info` output:

.NET SDK:
 Version:   7.0.100     
 Commit:    e12b7af219  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.414 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

VS Code version: 1.82.2
C# Extension version: 2.1.2 (reproducible in versions >=2.0)
C# Dev Kit Version: 0.4.10 (reproducible in other versions)

## Steps to reproduce

1. Open a Godot generated C# project in VSCode
2. Open any .cs file
3. Attempt to use autocomplete/intellisense features
4. Intellisense completions show up in popup menu, but do not input when selected (see GIF)

![IntellisenseIssue](https://github.com/dotnet/vscode-csharp/assets/26103348/32c7b5c6-d1c4-4ede-83c2-d30baf4c6de1)

## Expected  behavior
Expect code to be generated into the .cs file based on the autocomplete popup suggestion.

## Actual behavior
No code is generated, and occasionally, some of the typed code is overridden (see GIF).

## Additional context
Possibly related to #6036 ?

Extensions currently installed:

- doggy8088.netcore-editorconfiggenerator
- geequlim.godot-tools
- GrapeCity.gc-excelviewer      
- jan-dolejsi.pddl
- kleber-swf.unity-code-snippets
- ms-dotnettools.csdevkit       
- ms-dotnettools.csharp
- ms-dotnettools.vscode-dotnet-runtime
- ms-dotnettools.vscodeintellicode-csharp
- ms-python.isort
- ms-python.python
- ms-python.vscode-pylance
- ms-toolsai.jupyter
- ms-toolsai.jupyter-keymap
- ms-toolsai.jupyter-renderers
- ms-toolsai.vscode-jupyter-cell-tags
- ms-toolsai.vscode-jupyter-slideshow
- ms-vscode-remote.remote-ssh
- ms-vscode-remote.remote-ssh-edit
- ms-vscode.cpptools
- ms-vscode.mono-debug
- ms-vscode.remote-explorer
- neikeq.godot-csharp-vscode
- njpwerner.autodocstring
- ritwickdey.LiveServer
- VisualStudioExptTeam.intellicode-api-usage-examples
- VisualStudioExptTeam.vscodeintellicode
- Vue.volar

**Comment by dibarbet** [comment] 2023-09-16 00:27
This is a duplicate of https://github.com/dotnet/vscode-csharp/issues/6011

The next release should either fix the issue, or have more debug info so that we can track down the cause of the problem.

**Closed by dibarbet** 2023-09-16 00:27 UTC
