### ISSUE TITLE
Cannot create .NET debug configurations. The active C# project is not within folder

### ISSUE THREAD

**Issue by ahanusa** [dotnet/vscode-csharp#6050] opened 2023-08-05 23:15 UTC
Type: <b>Bug</b>

## Issue Description ##

Cannot create and debug a new web api project with vs code on a mac

## Steps to Reproduce ##

From command line:

mkdir MyApiProj
cd MyApiProj
dotnet new webapi
code .

In vs code after project is open:

Hit F5
Select .NET 5+ and .NET Core

## Expected Behavior ##

A launch.json file with the appropriate config to start a debugging session against the new api project.

## Actual Behavior ##

An error in lower right-hand bottom of screen:

"Cannot create .NET debug configurations. The active C# project is not within folder '/Users/Aaron/work/MyApiProj'.
A launch."

NOTE: A launch.json file is created, however, only contains the following content:

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": []
}

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.81.0
**C# Extension**: 2.0.328
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
A valid dotnet installation could not be found</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|birds-of-paradise|Programming-Engineer|0.1.2|programming-engineer.birds-of-paradise-0.1.2|
|blazorwasm-companion|ms-dotnettools|1.1.4|ms-dotnettools.blazorwasm-companion-1.1.4|
|csharp|ms-dotnettools|2.0.328|ms-dotnettools.csharp-2.0.328-darwin-x64|
|csharpextensions|jchannon|1.3.1|jchannon.csharpextensions-1.3.1|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|gitblame|waderyan|10.4.0|waderyan.gitblame-10.4.0|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|json|Meezilla|0.1.2|meezilla.json-0.1.2|
|ng-template|Angular|16.1.4|angular.ng-template-16.1.4|
|nugetpackagemanagergui|aliasadidev|2.0.6|aliasadidev.nugetpackagemanagergui-2.0.6|
|path-intellisense|christian-kohler|2.8.4|christian-kohler.path-intellisense-2.8.4|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|remote-containers|ms-vscode-remote|0.304.0|ms-vscode-remote.remote-containers-0.304.0|
|Theme-BirdsofParadise|gerane|0.0.5|gerane.theme-birdsofparadise-0.0.5|
|theme-github|thomaspink|1.0.1|thomaspink.theme-github-1.0.1|
|Theme-peacocks-in-space|gerane|0.0.5|gerane.theme-peacocks-in-space-0.0.5|
|trailing-spaces|shardulm94|0.4.1|shardulm94.trailing-spaces-0.4.1|
|vim|vscodevim|1.25.2|vscodevim.vim-1.25.2|
|vscode-commons|redhat|0.0.6|redhat.vscode-commons-0.0.6|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|ms-dotnettools.vscode-dotnet-runtime-1.6.0|
|vscode-guid|heaths|1.7.0|heaths.vscode-guid-1.7.0|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscode-resx-editor|DominicVonk|0.0.5|dominicvonk.vscode-resx-editor-0.0.5|
|vscode-theme-onelight|akamud|2.3.0|akamud.vscode-theme-onelight-2.3.0|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|;

</details>

Extension version: 2.0.328
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|. --crash-reporter-id ab71c575-1d1a-4ad3-88ac-549c056db4b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by WardenGnaw** [comment] 2023-08-07 17:45
With C# Dev Kit installed, you will want to use the `C#` in the dropdown menu instead of ` .NET 5+ and .NET Core`.

See https://code.visualstudio.com/docs/csharp/debugging#_existing-launchjson

**Comment by ahanusa** [comment] 2023-08-07 17:47
> With C# Dev Kit installed, you will want to use the `C#` in the dropdown menu instead of ` .NET 5+ and .NET Core`.
> 
> See https://code.visualstudio.com/docs/csharp/debugging#_existing-launchjson

I don't have the C# Dev Kit installed.

**Comment by WardenGnaw** [comment] 2023-08-07 18:49
Sorry, I misread the installed extensions. 

Can you delete the existing blank `launch.json` and use the command pallette (F1 or Ctrl + Shift + P) and run `.NET: Generate Assets for Build and Debug`?

**Comment by ahanusa** [comment] 2023-08-07 18:51
> Sorry, I misread the installed extensions.
> 
> Can you delete the existing blank `launch.json` and use the command pallette (F1 or Ctrl + Shift + P) and run `.NET: Generate Assets for Build and Debug`?

No worries.

No, I get the following error when I do that:

`Could not locate .NET Core project in DeleteMeApi. Assets were not generated.`

**Comment by WardenGnaw** [comment] 2023-08-07 19:50
> Dotnet Information
A valid dotnet installation could not be found

This is an interesting error. If you use the VS Code terminal, does the `dotnet` CLI work?

Also, @dibarbet Any ideas why Generate Asset would be failing to find the project for a webapi?

**Comment by ahanusa** [comment] 2023-08-07 19:51
> > Dotnet Information
> > A valid dotnet installation could not be found
> 
> This is an interesting error. If you use the VS Code terminal, does the `dotnet` CLI work?
> 
> Also, @dibarbet Any ideas why Generate Asset would be failing to find the project for a webapi?

Yes, the CLI works just fine

**Comment by dibarbet** [comment] 2023-08-07 19:53
I think this is because of https://github.com/dotnet/vscode-csharp/issues/5722
If you add a solution to your project and re-open in vscode do things work?

**Comment by ahanusa** [comment] 2023-08-07 19:56
I've been using VSCode for over 7 years and have never had to create a solution file.  Is this new?

**Comment by dibarbet** [comment] 2023-08-07 21:48
Yes, we switched the server implementation in the last update.  For now, you can either set the `dotnet.server.useOmnisharp` flag.  We should be updating the new implementation to support csproj in the next week or so as well.

**Comment by dibarbet** [comment] 2023-08-07 21:56
For now - closing this as a duplicate of https://github.com/dotnet/vscode-csharp/issues/5722 .  When that issue is fixed this should work as well.  

Workarounds for now
1.  Add a sln file
2.  Set the `dotnet.server.useOmnisharp` option to get back the old behavior which can load projects.
3.  Downgrade the extension to a 1.x version.

**Closed by dibarbet** 2023-08-07 21:56 UTC
Labels: Debugger

**Comment by SamuelEarl** [comment] 2023-08-23 01:33
> For now - closing this as a duplicate of #5722 . When that issue is fixed this should work as well.
> 
> Workarounds for now
> 
> 1. Add a sln file
> 2. Set the `dotnet.server.useOmnisharp` option to get back the old behavior which can load projects.
> 3. Downgrade the extension to a 1.x version.

I have used VSCode for HTML, CSS, and JavaScript for quite a few years, but I know almost nothing about C# or .Net. So I don't know what a sln file is or what `dotnet.server.useOmnisharp` is (let alone how to set it). I've also never had to downgrade a VSCode extension before. Do you mind providing step-by-step instructions for someone who is new to C# development? 

Thank you!
