### ISSUE TITLE
Cannot match the appropriate completion name of the Symbol

### ISSUE THREAD

**Issue by DFVSQY** [dotnet/vscode-csharp#6077] opened 2023-08-09 02:18 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK (反映任何 global.json):
 Version:   6.0.300
 Commit:    8473146e7d

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  5.0.413 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

VS Code version:
```
Version: 1.81.0 (system setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.17763
```

C# Extension version:
```
v2.0.328
```

## Steps to reproduce

There is a C# class:
```
public static class GameObjectExt
{
    public static void SetRotXYZW(this GameObject go, float x, float y, float z, float w)
    {
        go.transform.rotation = new Quaternion(x, y, z, w);
    }
}
```

When I enter `SetRotXYZW` for symbol search, the symbol name cannot be fully matched:
![image](https://github.com/dotnet/vscode-csharp/assets/8075421/a7cfab78-cd03-4bb7-8382-81702941c114)

**Comment by dibarbet** [comment] 2023-11-09 01:09
I've tried reproducing this in a few different ways but haven't been able to - does this still reproduce for you on the latest versions of the extension?

If it does, please set `dotnet.server.trace` to `Trace` and attach the output window logs from `C#` and `C# LSP Trace Logs`
Thanks!

**Comment by DFVSQY** [comment] 2023-11-09 02:10
@dibarbet This problem is still exist, there is no log in C# label and no `C# LSP Trace Logs` label. I use this plugin in unity project, so my config is:
![image](https://github.com/dotnet/vscode-csharp/assets/8075421/c77d9c38-2ed2-41fe-9755-cce28df6551d)

**Comment by dibarbet** [comment] 2023-11-09 19:28
Ah - this is using O#.  FYI that the latest version of the C# extension should support loading old style unity projects without needing O# (as long as you have a global .net framework install as before).  Can you let me know if that works better?

**Comment by DFVSQY** [comment] 2023-11-10 02:05
> Ah - this is using O#. FYI that the latest version of the C# extension should support loading old style unity projects without needing O# (as long as you have a global .net framework install as before). Can you let me know if that works better?

When I change the setting to `"dotnet.server.useOmnisharp”: false`, the function symbol of C# can be located correctly, but there is no prompt for function parameter description, and it does not support features like code jumping in C#. According to my own tests and documentation, when using older versions of Unity, the configuration item `“dotnet.server.useOmnisharp”` must be set to `true` to work properly.
![image](https://github.com/dotnet/vscode-csharp/assets/8075421/f68a3d95-6237-42ae-960c-ce7cfb53fabd)

**Comment by dibarbet** [comment] 2023-11-10 03:14
> but there is no prompt for function parameter description, and it does not support features like code jumping in C#.

Can you expand on these?  Not sure I understand which features you're talking about (a screenshot or gif of what isn't working may help).

> when using older versions of Unity, the configuration item “dotnet.server.useOmnisharp” must be set to true to work properly.

This used to be the case, but we believe we've fixed most of the issues with older versions of Unity on the new extension version.  Screenshots of exactly what isn't working for you (and the contents of the C# output window log) would generally be useful for us to help diagnose what is going wrong.

I ask because the majority of our focus is on the non-O# version of the extension, so it would be best if we could resolve the issues you're having there.

Thanks!

**Comment by DFVSQY** [comment] 2023-11-10 05:14
> > but there is no prompt for function parameter description, and it does not support features like code jumping in C#.
> 
> Can you expand on these? Not sure I understand which features you're talking about (a screenshot or gif of what isn't working may help).
> 
> > when using older versions of Unity, the configuration item “dotnet.server.useOmnisharp” must be set to true to work properly.
> 
> This used to be the case, but we believe we've fixed most of the issues with older versions of Unity on the new extension version. Screenshots of exactly what isn't working for you (and the contents of the C# output window log) would generally be useful for us to help diagnose what is going wrong.
> 
> I ask because the majority of our focus is on the non-O# version of the extension, so it would be best if we could resolve the issues you're having with it.
> 
> Thanks!

Please look at these two pictures. The first one shows a screenshot of the symbols in C#, listing out the function parameters. However, the function parameters are not listed in the symbols in the second screenshot.

![image](https://github.com/dotnet/vscode-csharp/assets/8075421/68bbcffc-d6f4-4e14-9602-d73b90ac6fa4)

![image](https://github.com/dotnet/vscode-csharp/assets/8075421/91890aba-7452-420a-baa2-30a47ee94ed1)

The C# output window log:

[Csharp_Log.log](https://github.com/dotnet/vscode-csharp/files/13315811/Csharp_Log.log)

**Comment by dibarbet** [comment] 2023-11-10 09:16
Got it, the version without parameters is intentional, but it may be possible to change given enough feedback.  Is that the only issue preventing you from using the non-O# version of the extension?  I think you also mentioned an issue with "code jumping" - I wasn't sure what that was.  

Otherwise, please add the details of any problems preventing you from using the non-O# version of the extension.

**Comment by DFVSQY** [comment] 2023-11-10 13:42
> Got it, the version without parameters is intentional, but it may be possible to change given enough feedback. Is that the only issue preventing you from using the non-O# version of the extension? I think you also mentioned an issue with "code jumping" - I wasn't sure what that was.
> 
> Please add the details of any problems preventing you from using the non-O# version of the extension.

Please add parameters info for the symbols, i think it's very important.

There are some other issues for the non-O# version:

- There is no code intelligent function
- CodeLen is only work in single file
- I don't know the default solution file(.sln)
- I can't goto the definition

**Comment by dibarbet** [comment] 2024-05-22 23:26
Closing this issue.  We've made a number of updates to how project loading works in the extension.  Please try the latest versions of the C# and Unity extensions and file a *new* issue if you encounter problems.

**Closed by dibarbet** 2024-05-22 23:26 UTC
Labels: Bug, OmniSharp, Needs More Info, Triaged
