### ISSUE TITLE
Code lens System.ArgumentNullException in diff editor

### ISSUE THREAD

**Issue by vchirikov** [dotnet/vscode-csharp#5843] opened 2023-06-21 11:57 UTC
## Environment data
`dotnet --info` output:

```
.NET SDK:
 Version:   8.0.100-preview.3.23178.7
 Commit:    e300b0e1e6
```

VS Code version: 1.79.2
C# Extension version: v2.0.212

## log

```
[Error - 2:48:15 PM] [LanguageServerHost]System.ArgumentNullException: Value cannot be null. (Parameter 'Document is null when it was required for codeLens/resolve')
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext.GetRequiredDocument() in /_/src/Features/LanguageServer/Protocol/Handler/RequestContext.cs:line 191
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 38
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 124
   
   
...


[Error - 2:48:15 PM] Request codeLens/resolve failed.
  Message: Value cannot be null. (Parameter 'Document is null when it was required for codeLens/resolve')
  Code: -32000 
  
...

[Error - 2:48:17 PM] [LanguageServerHost]System.ArgumentNullException: Value cannot be null. (Parameter 'Document is null when it was required for codeLens/resolve')
   at Microsoft.CodeAnalysis.LanguageServer.Handler.RequestContext.GetRequiredDocument() in /_/src/Features/LanguageServer/Protocol/Handler/RequestContext.cs:line 191
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 38
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
```

## Steps to reproduce

1. Open modified cs file diff (diff editor)
2. See the errors

Codelens related config:
```js
  "csharp.referencesCodeLens.enabled": false,
  "csharp.testsCodeLens.enabled": true,
  "merge-conflict.codeLens.enabled": true,
  "diffEditor.codeLens": true,
```

## Expected  behavior
No errors

## Actual behavior

Error popup & error logs

**Comment by vchirikov** [comment] 2023-07-03 11:12
@beccamc any updates on this?

**Comment by beccamc** [comment] 2023-07-07 16:45
@vchirikov I am able to reproduce and have tracked down the root cause. We're having an issue with URL encodings coming from VS Code making file paths not equivalent. I am working on a fix. Thanks for your patience on this!

**Comment by beccamc** [comment] 2023-07-31 21:31
The root cause is the [DocumentUriConverter ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.languageserver.protocol.documenturiconverter?view=visualstudiosdk-2022)returning a path using URL encodings. Working with the relevant team on a fix. 

This test case is a simple way to reproduce...

```
        var gitString = "git:/c:/Repos/MyRepo/MyNewFile.cs?{\"path\":\"c:\\\\Repos\\\\MyRepo\\\\MyNewFile.cs\",\"ref\":\"~\"}";
        var myUri = new System.Uri(gitString);

        var serializedWithConverter = JsonConvert.SerializeObject(myUri, new DocumentUriConverter());
        var deserializedWithConverter = JsonConvert.DeserializeObject<Uri>(serializedWithConverter, new DocumentUriConverter());

        // this fails because "%22": "%5C%5C" are used 
        Assert.Equal(myUri.OriginalString, deserializedWithConverter.OriginalString);
```

**Comment by vchirikov** [comment] 2023-08-25 07:07
@beccamc will it be included in august releases? the extension doesn't work at all without it

**Comment by beccamc** [comment] 2023-08-25 16:47
@tmat Do you know about the status of the DocumentUri fix?

**Comment by tmat** [comment] 2023-08-25 16:54
Where is `Uri.OriginalString` used?

**Comment by beccamc** [comment] 2023-08-25 22:37
@tmat This was supposed to be fixed by this PR I believe - https://github.com/dotnet/roslyn/pull/69304. This went in a couple weeks ago. I can check and see if the issue still reproduces.

**Comment by tmat** [comment] 2023-08-25 23:26
I don't think it would be. That fix only addressed issues with certain Unicode characters.

**Comment by beccamc** [comment] 2023-12-20 22:59
@tmat Do you mind taking over this issue?

**Closed** 2024-07-29 18:08 UTC
Labels: Bug, Triaged
