### ISSUE TITLE
Format doesn't work for newly added unsaved file

### ISSUE THREAD

**Issue by Siccity** [dotnet/vscode-csharp#3596] opened 2020-02-21 09:42 UTC
Issue Type: <b>Bug</b>

1. Create new file `Ctrl+N`
2. Paste some unformatted C# code `Ctrl+V`
3. Set Language Mode to C# `Ctrl+K, M`
4. Format `Alt+Shift+F`

The format hotkey does nothing.

5. Save file `Ctrl+S`

Formatting works again.

Extension version: 1.21.12
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3510)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (17.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by filipw** [comment] 2020-02-21 10:55
I am not sure this is a bug - the langauge server knows nothing about a new file until it's saved for the first time (== added to the Roslyn workspace on the server).

Please note that this only applies to **newly added** files, if you have an **existing** unsaved file then formatting works fine.

**Comment by Siccity** [comment] 2020-02-21 12:35
But shouldn't C# files be able to format using global settings?

I don't know what happens behind the veil, but on the front-end I don't see why it should be impossible to format an unsaved C# class the same way you can with json or a javasript.

I was using FixFormat previously but I'm currently trying to switch to using omnisharps formatter. I do a lot of helping on various forums and I find it very handy to use vscode to format loose copy/pasted code snippets without opening a project.

**Comment by filipw** [comment] 2020-02-21 13:03
C# formatting doesn't happen in the editor but, like all C# language services, through Roslyn (the compiler) in the language server. 

The C# extension itself has no semantic understanding of the [C# formatting rules](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#formatting-options) or other formatting means like [.editorconfig](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019).  In other words, the compiler has to be initialized for the formatting to succeed. It doesn't need a project, loose (so called "misc files") files are also supported but they need to be saved.

**Comment by cartermp** [comment] 2020-03-12 20:48
There's no global understanding as @filipw mentions, when creating a raw new file that's unsaved. You can set it to be C# by clicking here:

<img width="301" alt="image" src="https://user-images.githubusercontent.com/6309070/76565586-1e8aa300-6468-11ea-8997-944eef7687b3.png">

But there is no recognized formatter.

**Comment by JoeRobich** [comment] 2024-11-12 07:03
Closing as by design.

**Closed by JoeRobich** 2024-11-12 07:03 UTC
Labels: Feature Request, OmniSharp, Triaged
