### ISSUE TITLE
The setting 'editor.codeLens' cannot be overrided by 'csharp.referencesCodeLens.enabled' anymore

### ISSUE THREAD

**Issue by th3W3n** [dotnet/vscode-csharp#6070] opened 2023-08-08 12:26 UTC
## Environment data
`dotnet --info` output:
VS Code version: 1.81.0
C# Extension version: 2.0.328

## Steps to reproduce
1. Set as below on Settings.json file:
```json
"editor.codeLens": true,
"csharp.referencesCodeLens.enabled": false
```
2. Open an C# file, you'll then see "xxx references" everywhere now, which were not shown before.

**Comment by ben-perry** [comment] 2023-08-08 13:55
The setting is no longer working for me too, the visual clutter is annoying.

**Comment by dibarbet** [comment] 2023-08-08 18:14
This is a dupe of https://github.com/dotnet/vscode-csharp/issues/5809 and will be fixed in this weeks release.

**Closed by dibarbet** 2023-08-08 18:14 UTC
Labels: Bug, Triaged
