### ISSUE TITLE
Only open files show problems in Problems tab

### ISSUE THREAD

**Issue by tverboon** [dotnet/vscode-csharp#1525] opened 2017-05-30 09:49 UTC
## Environment data
`dotnet --info` output:
.NET Command Line Tools (2.0.0-preview1-005977)

Product Information:
 Version:            2.0.0-preview1-005977
 Commit SHA-1 hash:  414cab8a0b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview1-005977/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview1-002111-00
  Build    : 1ff021936263d492539399688f46fd3827169983

VS Code version: 1.12.2

C# Extension version: 1.10.0

## Steps to reproduce
We just migrated from project.json to csproj. With project.json compile errors were found in the entire workspace. With the new MSBuild projects, only problems are detected when the file is open. To reproduce I could just remove a parameter from a method in an interface.

## Expected  behavior
See all errors, warnings and info in my workspace when I change something that introduces problems.

## Actual behavior
No problems are detected, when the changed interface file is the only open file. When I open the implementation class, a compile error will be detected.

**Comment by DustinCampbell** [comment] 2017-05-30 19:18
Thanks for the report @tverboon.

**Comment by tverboon** [comment] 2017-05-31 09:31
I was looking in the code and I saw a _isHugeProject() check for 1000 source files, which is determined by Compile Item in MSBuild. So I added this to our common.props

```
<Target Name="Counter">
    <Message Text="Items: '@(Compile->Count())'" />
</Target>
```

Adding all counts in our projects and the total is 1325 files. I guess our project is 'huge' 😄
 #838 would solve this issue. Guess this one can be closed then.

**Comment by DustinCampbell** [comment] 2017-05-31 18:27
Ah, that makes sense. Yes, this is essentially a duplicate of that.

I think I'll repurpose this to add some sort of easily dismiss-able message for largish projects to let helpful users (like yourself!) know what the heck is going on.

Thanks for the additional information!

**Comment by tverboon** [comment] 2017-06-01 06:16
I just increased the file limit to 2000 and did some tests with our project, but I am happy with the file limit as it is now. It's just not fast enough on my 4GHz Core i7 iMac. How is this handled in Visual Studio, as I guess it's mostly Roslyn doing the work?

Is it possible to do an analysis to determine if it's a public change? When I do remove unnecessary usings, only the current file should be reanalysed. If I change a public method signature, the whole project needs to be analysed, but that's what we want in that case. If we change the body of a (public) method, only the body needs to be analysed, so file analysis would be enough, right?

**Comment by DustinCampbell** [comment] 2017-06-01 13:49
In VS, we have full solution analysis turned off by default. So, in VS you only get errors in open files unless you build.

![image](https://cloud.githubusercontent.com/assets/116161/26682757/6e271d14-4696-11e7-814a-79744eee9623.png)

**Comment by JoeRobich** [comment] 2024-11-08 22:45
Closing as an option for max document count for file analysis was added.

**Closed by JoeRobich** 2024-11-08 22:45 UTC
Labels: Bug, OmniSharp, Editor-Diagnostics
