### ISSUE TITLE
Problems window no longer populates with linter errors unless file is open

### ISSUE THREAD

**Issue by GrahamMThomas** [dotnet/vscode-csharp#6211] opened 2023-08-23 20:50 UTC
## Environment data
`dotnet --info` output:

```
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/<username>/.dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4
```
VS Code version: 1.81.1
C# Extension version: v2.0.413

## OmniSharp log
```
Starting OmniSharp server at 8/23/2023, 1:55:47 PM
    Target: <REDACTED>

OmniSharp server started with .NET 7.0.400
.
    Path: /home/gthomas/.vscode-server/extensions/ms-dotnettools.csharp-2.0.413-linux-x64/.omnisharp/1.39.7-net6.0/OmniSharp.dll
    PID: 32300

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Unknown 0.0 (Unknown)
[info]: OmniSharp.Services.DotNetCliService
        Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
[info]: OmniSharp.Services.DotNetCliService
        Using the 'dotnet' on the PATH.
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 3 MSBuild instance(s)
            1: .NET Core SDK 7.0.400 17.7.1 - "/home/gthomas/.dotnet/sdk/7.0.400/"
            2: .NET Core SDK 7.0.302 17.6.1 - "/home/gthomas/.dotnet/sdk/7.0.302/"
            3: .NET Core SDK 6.0.405 17.3.2 - "/home/gthomas/.dotnet/sdk/6.0.405/"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: .NET Core SDK 7.0.400 17.7.1 - "/home/gthomas/.dotnet/sdk/7.0.400/"
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '<REDACTED>'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Did not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Detecting projects in '<REDACTED>'.
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '<REDACTED>'
------------ <REDACT> More "Queue Project update"
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '<REDACTED>'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Did not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '<REDACTED>' on host 31762.
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: <REDACT>
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '<REDACT>'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '<REDACT>'
------------ <REDACT> More "Load project, success, adding project"
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: <REDACT>
------------ <REDACT> More "Update Project"
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 331.
```

## Steps to reproduce

1. Open project with `code .` at root of c# solution

## Expected  behavior
Expected ~225 problems from omnisharp linter to appear within vscodes "Problems" window

## Actual behavior
Shows 0 problems unless I open an individual file. Once a file is open the linter problems will appear.

## Additional context
I've tried increasing `csharp.maxProjectFileCountForDiagnosticAnalysis` with no luck.

Rollback to `v2.0.328` and expected behavior appears.

**Comment by dibarbet** [comment] 2023-08-23 23:00
cc @mavasani 
What is the value of the background analysis scope option?
<img width="530" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/b76680f0-4c5c-4ef7-ae14-bbb380b70e77">

If its open files, and you set it to 'fullSolution' does it work?

**Comment by GrahamMThomas** [comment] 2023-08-23 23:05
Yes that solved it. Was that behavior change intended? I looked in the Changelog and didn't see anything obvious.

Feel free to close.

**Comment by benjaminmillhouse** [comment] 2023-08-24 16:47
FYI - Seeing the same behavior - This feels like a "breaking change" that should have been called out better...
The Problem Window already lets you pick whether or not you want to show for active files or not.  But it appears this setting is overriding whatever you have selected in that window...

<img width="1378" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/13835886/a2f25434-0b36-4701-a556-1a7106eb3a12">

**Comment by dibarbet** [comment] 2024-03-27 23:13
> The Problem Window already lets you pick whether or not you want to show for active files or not. But it appears this setting is overriding whatever you have selected in that window...

The problems window settings only control the display of the diagnostics - the C# extension settings change whether or not analysis of files actually happens which can drastically impact performance (full solution diagnostics can slow things down a lot in large solutions).  Hence the need for different settings.

I expect there is more we can do here to advertise what is happening when full solution analysis is turned off - though we need to come up with a good UX for it.

For now closing this  issue as by design.

**Closed** 2024-03-27 23:13 UTC
Labels: Resolved-By Design, Needs More Info
