### ISSUE TITLE
`Fix All: Remove unnecessary usings` failed

### ISSUE THREAD

**Issue by DarkRRRabbit** [dotnet/vscode-csharp#7559] opened 2024-09-12 14:07 UTC
1. Open any C# code that contains unnecessary usings and press `ctrl+ .`
2. Select `Fix All: Remove unnecessary usings`
3. Select `Project` or `Solution`
4. Show error:
`JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title`

## Log
```
Using dotnet configured on PATH
Dotnet path: D:\Portable\dotnet\bin\dotnet.exe
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\2d723b39"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:57:40 PM] [Program] Language server initialized
[Info  - 9:57:49 PM] [WorkspaceProjectFactoryService] Project D:\***\AliceBot.Core.csproj loaded by C# Dev Kit
[Error - 10:00:28 PM] [LanguageServerHost] System.Text.Json.JsonException: JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](JsonElement element, JsonSerializerOptions options)
   at Microsoft.CommonLanguageServerProtocol.Framework.SystemTextJsonLanguageServer`1.DeserializeRequest[TRequest](Object serializedRequest, RequestHandlerMetadata metadata) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/SystemTextJsonLanguageServer.cs:line 50
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.TryDeserializeRequest[TRequest](AbstractLanguageServer`1 languageServer, RequestHandlerMetadata requestHandlerMetadata, Boolean isMutating, TRequest& request) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 117
Error making codeAction/resolveFixAll request: JSON deserialization for type 'Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActions.RoslynFixAllCodeAction' was missing required properties, including the following: title
```

### VSCode

Version: 1.93.0

Commit: 4849ca9bdf9666755eb463db297b69e5385090e3

Date: 2024-09-04T13:02:38.431Z

Electron: 30.4.0

ElectronBuildId: 10073054

Chromium: 124.0.6367.243

Node.js: 20.15.1

V8: 12.4.254.20-electron.0

OS: Windows_NT x64 10.0.19045

OS version: Windows_NT x64 10.0.22631

### Extension

version: v2.45.20

**Comment by JoeRobich** [comment] 2024-09-12 16:09
Thanks for opening an issue. This appears to be a duplicate of https://github.com/dotnet/vscode-csharp/issues/7535. The fix will be in a future version of the C# extension.

**Closed by JoeRobich** 2024-09-12 16:09 UTC
Labels: Resolved-Duplicate
