### ISSUE TITLE
False error message for WPF application in VS Code

### ISSUE THREAD

**Issue by High-Banana** [dotnet/vscode-csharp#7603] opened 2024-09-25 17:17 UTC
Type: <b>Bug</b>

Create a new WPF application on VS Code by typing "dotnet new wpf" on console.
That's it. Now just wait till the extension finishes loading and you start to get "The name 'InitializeComponent' does not exist in the current context" error message with red underline. That method definitely exists because it was automatically created. The application however runs correctly without any issues after typing "dotnet run".
The same issue appears when I call a UI Control from xaml file to cs file. It keeps saying it does not exist in this context but the application runs without any issues. The error message should not appear there since it definitely exists.
If I turn off the C# Dev Kit extension, those error messages goes away and the applications runs fine as usual.

Extension version: 2.45.25
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4500U with Radeon Graphics          (6 x 2371)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.42GB (1.25GB free)|
|Process Argv|--crash-reporter-id e84effd4-77c1-49ca-8cf3-bb462902f6c2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyonecf:30548226
vscrpc:30673769
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl2:31139839
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
cf971741:31144450
defaultse:31133495
fje88620:31121564
iacca2:31144504

```

</details>

**Comment by dibarbet** [comment] 2024-09-25 18:46
duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1018

**Closed by dibarbet** 2024-09-25 18:46 UTC
