### ISSUE TITLE
C# plugin doesn't work for me in vs code

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/vscode-csharp#4474] opened 2021-04-05 05:14 UTC
Please paste the output from your clipboard

## Issue Description ##
The C# extension is not working for me under kubuntu 20.10 as has not even when I was in windows

## Steps to Reproduce ##
I don't think you will be able to reproduce this due to the fact I am not even getting errors. 
(I have debugged with people in the C# discord aka Klarth and 333fred)

## Expected Behavior ##
I would assume I would just have the same or simular experience to vs 2019

## Actual Behavior ##
- No auto complete on anything using, types, keywords 
- Errors that don't exist like missing curly brackets
- Lack of refactoring suggestions other people have. I assume no quick fixes available all the time is a not intented  

## Logs ##
not sure what to put I assume nothing since i get no errors?

### OmniSharp log ###
https://gist.github.com/Shadowblitz16/c01b50a4231b8b8d71808827962ecb7e

### C# log ###
NA

## Environment information ##

**VSCode version**: 1.55.0
**C# Extension**: 1.23.9

<details><summary>Mono Information</summary>
        OmniSharp using built-in mono</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.10
 OS Platform: Linux
 RID:         ubuntu.20.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|better-toml|bungcip|0.3.2|
|cargo|panicbit|0.2.3|
|crates|serayuzgur|0.5.7|
|csharp|ms-dotnettools|1.23.9|
|kde-breeze-dark-cs|Shadowblitz16|0.0.1|
|rust-analyzer|matklad|0.2.538|
|rust-and-friends|nyxiative|1.0.0|
|rust-doc-viewer|JScearcy|2.0.1|
|rust-flash-snippets|lorenzopirro|1.2.0|
|rust-mod-generator|ZhangYue|1.0.3|
|rust-syntax|dustypomerleau|0.5.0|
|rust-targets|PolyMeilex|1.0.1|
|syntax-highlighter|evgeniypeshkov|0.5.0|
|vscode-lldb|vadimcn|1.6.1|
|vscode-nuget-package-manager|jmrog|1.1.6|
|vsliveshare|ms-vsliveshare|1.0.4070|;

</details>

## Example ##
Menu has a Update method but..
![image](https://user-images.githubusercontent.com/2453707/113542627-85aa5680-9599-11eb-9dfd-31c1fef4ca8b.png)
![image](https://user-images.githubusercontent.com/2453707/113543964-49c4c080-959c-11eb-9f16-04ab18e62bb5.png)

**Comment by JoeRobich** [comment] 2021-04-08 15:24
@Shadowblitz16 It appears from you log that the project was loaded. I am not sure why you are not seeing completion. Is this a project that you can share with us?

**Comment by JoeRobich** [comment] 2021-04-08 15:34
@Shadowblitz16 We found an issue in your log that has been fixed in the newer builds of OmniSharp. Could you try this prerelease C# extension and see if your issue is resolved https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.10 ([Instructions for installing beta releases](https://github.com/OmniSharp/omnisharp-vscode/wiki/Installing-Beta-Releases))

**Comment by Shadowblitz16** [comment] 2021-04-09 04:14
@JoeRobich Its not my project. I debugged it with the people on C# discord and it worked for them

I can try the newer version. 
I will get back to you.

**Comment by Shadowblitz16** [comment] 2021-04-09 20:47
@JoeRobich I am getting autocomplete now as far as I know but its slow and now my project doesn't run when I do `dotnet run`
also I am still not getting quick fixes

**Comment by JoeRobich** [comment] 2021-04-09 21:14
@Shadowblitz16 Could you set the OmniSharp LogLevel to trace and share the OmniSharp log from the output pane when you are seeing these issues? Also, to it would be helpful if you could share the project or repo that issues can be reproduced with. I was able to build and run the following Raylib repo with no issue - https://github.com/ChrisDill/Raylib-cs-Examples.

**Comment by Shadowblitz16** [comment] 2021-04-09 21:38
https://gist.github.com/Shadowblitz16/0479c5d4f27ec1d65711792bb0314e99
https://github.com/Shadowblitz16/Asteroids-Raylib/blob/master/src/Program.cs

**Comment by JoeRobich** [comment] 2021-04-09 22:25
@Shadowblitz16 If I swap the `Raylib.InitWindow` and `Menu.ObjectCreate` lines in Program.cs you app runs.

**Comment by Shadowblitz16** [comment] 2021-04-09 22:58
@JoeRobich I was just trying to get it to compile and then I looked up and it was highlighted wrongly.

**Comment by JoeRobich** [comment] 2021-04-10 00:03
> I was just trying to get it to compile and then I looked up and it was highlighted wrongly.

Ah, ok. We have had issues where the editor and the language server would end up with different views of the source code. There was a change in 1.23.10 which I believed would fix this issue. Please let me know if you see this again.

**Comment by Shadowblitz16** [comment] 2021-04-10 04:30
@JoeRobich I have been coding with the extension all day today and it kinda worked but its slow and eventually just stops working.
not sure if it helps but here is a log from my entire day of coding..
https://gist.github.com/Shadowblitz16/055d053451d6c11c4028ec771a2c4e2d

**Comment by JoeRobich** [comment] 2024-11-13 00:22
A lot has changed with O# since this issue was opened. If you are still having problems, please open a new issue at https://github.com/omnisharp/omnisharp-roslyn/issues

**Closed by JoeRobich** 2024-11-13 00:22 UTC
Labels: OmniSharp, Needs More Info, Triaged
