### ISSUE TITLE
[macOS 11 x64] Cannot compile or debug with VSCode for C# Program

### ISSUE THREAD

**Issue by at4gamlite** [dotnet/vscode-csharp#7251] opened 2024-06-20 06:26 UTC
Type: <b>Bug</b>

## Issue Description ##
I have encountered the error message below. Have attempted to uninstall and reinstall VSCode, reinstall extensions and so on, but error still persists.

=======================================================

Internal error in the debugger.
Exception = System.DllNotFoundException
Message = Unable to load shared library 'vsdbg' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable:
dlopen(/Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/vsdbg.dylib, 1): image not found
dlopen(vsdbg.dylib, 1): image not found
dlopen(/Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

dlopen(libvsdbg.dylib, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

dlopen(/Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/vsdbg, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

dlopen(vsdbg, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
Referenced from: /Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
Expected in: /usr/lib/libc++.1.dylib

dlopen(/Users/anson/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg, 1): image not found
dlopen(libvsdbg, 1): image not found
Code = 80131524
at VsDbg.NativeEntryPoint.EnsureInitialized(String[] args)
at VsDbg.Transports.LocalTransport.b__28_0()

VS Code version: Code 1.90.2 (Universal) (5437499, 2024-06-18T22:37:41.291Z)
OS version: Darwin x64 20.6.0
Modes:

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.90.2
**C# Extension**: 2.34.12
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.302/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  3.1.426 [/usr/local/share/dotnet/sdk]
  8.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.18.42|ms-vscode.cmake-tools-1.18.42|
|cpptools|ms-vscode|1.20.5|ms-vscode.cpptools-1.20.5-darwin-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.7.27|ms-dotnettools.csdevkit-1.7.27-darwin-x64|
|csharp|ms-dotnettools|2.34.12|ms-dotnettools.csharp-2.34.12-darwin-x64|
|debugpy|ms-python|2024.6.0|ms-python.debugpy-2024.6.0-darwin-x64|
|git-graph|mhutchie|1.30.0|mhutchie.git-graph-1.30.0|
|githistory|donjayamanne|0.6.20|donjayamanne.githistory-0.6.20|
|go|golang|0.41.4|golang.go-0.41.4|
|material-icon-theme|PKief|5.4.2|pkief.material-icon-theme-5.4.2|
|python|ms-python|2024.8.1|ms-python.python-2024.8.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.6|ms-dotnettools.vscode-dotnet-runtime-2.0.6|
|vscode-pylance|ms-python|2024.6.1|ms-python.vscode-pylance-2024.6.1|;

</details>

Extension version: 2.34.12
VS Code version: Code 1.90.2 (Universal) (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:37:41.291Z)
OS version: Darwin x64 20.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 90, 83|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 1f173ea7-b16a-470c-9d8a-b7706ed84c07|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
bdiig495:31013172
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
legacy_priority:31077528

```

</details>

**Comment by chadams** [comment] 2024-06-20 19:33
Getting exact same error, different environment.

<details>
<summary>Debug Console (VSCode)</summary>

```bash
Message = Unable to load shared library 'vsdbg' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/vsdbg.dylib, 1): image not found
dlopen(vsdbg.dylib, 1): image not found
dlopen(/Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

dlopen(libvsdbg.dylib, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

dlopen(/Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/vsdbg, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

dlopen(vsdbg, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg.dylib (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

dlopen(/Users/chadams/.vscode/extensions/ms-dotnettools.csharp-2.34.12-darwin-x64/.debugger/x86_64/libvsdbg, 1): image not found
dlopen(libvsdbg, 1): image not found

Code = 80131524
   at VsDbg.NativeEntryPoint.EnsureInitialized(String[] args)
   at VsDbg.Transports.LocalTransport.<Init>b__28_0()

```
</details>


<details>
  <summary>dotnet --info</summary>
  
```bash
.NET SDK (reflecting any global.json):
 Version:   6.0.423
 Commit:    c5c9e53229

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.423/

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  1.0.1 [/usr/local/share/dotnet/sdk]
  6.0.423 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]
  8.0.300 [/usr/local/share/dotnet/sdk]
  8.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set
```
</details>

**Comment by WardenGnaw** [comment] 2024-06-21 00:03
The issue is that the debugger now builds on macOS 12 machines as macOS 11 is deprecated for Azure Pipeline Build Agents.
See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

The workaround would be to use an older version of the C# Extension starting from [v2.33.17](https://github.com/dotnet/vscode-csharp/releases/tag/v2.33.17) or before or update your macOS to macOS 12.

**Comment by at4gamlite** [comment] 2024-06-21 00:26
> The issue is that the debugger now builds on macOS 12 machines as macOS 11 is deprecated for Azure Pipeline Build Agents. See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
> 
> The workaround would be to use an older version of the C# Extension starting from [v2.33.17](https://github.com/dotnet/vscode-csharp/releases/tag/v2.33.17) or before or update your macOS to macOS 12.
> 
> Also .NET 8 only supports [macOS 12+](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos) and .NET 6 will be out of support on Nov 12, 2024.
> 
> See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

This does solve my problem for now. Thanks

**Comment by alexnavfr** [comment] 2024-06-21 14:07
> > The issue is that the debugger now builds on macOS 12 machines as macOS 11 is deprecated for Azure Pipeline Build Agents. See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
> > The workaround would be to use an older version of the C# Extension starting from [v2.33.17](https://github.com/dotnet/vscode-csharp/releases/tag/v2.33.17) or before or update your macOS to macOS 12.
> > Also .NET 8 only supports [macOS 12+](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos) and .NET 6 will be out of support on Nov 12, 2024.
> > See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
> 
> This does solve my problem for now. Thanks

Mine too. Could you please add the note about that issue into Changes?
Something like "Version is compatible with MacOs 12+ and older version of MasOs now more supported". It will be helpful for peoples still used 10.15+. Thanks.

**Comment by Alejoho** [comment] 2024-06-29 16:38
> The issue is that the debugger now builds on macOS 12 machines as macOS 11 is deprecated for Azure Pipeline Build Agents. See https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
> 
> The workaround would be to use an older version of the C# Extension starting from [v2.33.17](https://github.com/dotnet/vscode-csharp/releases/tag/v2.33.17) or before or update your macOS to macOS 12.
> 
> Also .NET 8 only supports [macOS 12+](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#macos) and .NET 6 will be out of support on Nov 12, 2024.
> 
> See https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Thank you. This solved my problem too.

**Comment by WardenGnaw** [comment] 2024-07-24 17:47
Closing this issue now as the latest extension will warn of the OS restriction and ask users to update.

For folks who can not update, please use an older version of the extension that does not require this limitation starting from [v2.33.17](https://github.com/dotnet/vscode-csharp/releases/tag/v2.33.17) or before

Thank you for reporting this!

**Closed by WardenGnaw** 2024-07-24 17:47 UTC
Labels: Debugger

**Comment by alexnavfr** [comment] 2024-07-25 06:03
Great job! Thanks a lot guys!
