### ISSUE TITLE
Problem with the Language Server: command 'roslyn.changeRazorCSharp' already exists

### ISSUE THREAD

**Issue by geo-bontognali** [dotnet/vscode-csharp#5824] opened 2023-06-18 05:22 UTC
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

VS Code version: 1.79.2
C# Extension version: v2.0.212

## Steps to reproduce

1. Go to 'Any C# Project"
2. Press "CTRL+Shift+P' and select "> .NET: Restart Language Server
4. See error: "Command: .NET Restart Language Server resulted in an error: command 'roslyn.changeRazorCSharp' already exists"

## Expected  behavior
The Language Server restarts

## Actual behavior
The Language Server seems to restart but the code highlighting is incomplete, often simply wrong and in glitchy in general.

## Additional context
After working on a project for a while, sometimes even from the beginning, the code highlighting, the warnings and the errors stop working properly. If I try to restart the language Server than I receive that error.
I've installed the C# dev Kit.

**Comment by Igorgro** [comment] 2023-06-18 10:43
Duplicate of #5779

**Comment by dibarbet** [comment] 2023-06-19 21:24
Yup - closing as duplicate of https://github.com/dotnet/vscode-csharp/issues/5779

**Closed by dibarbet** 2023-06-19 21:24 UTC
