### ISSUE TITLE
No .editorconfig or omnisharp.json support currently or only partial support.

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6215] opened 2023-08-23 23:28 UTC
From vscode-dotnettools created by @Toonic: https://github.com/microsoft/vscode-dotnettools/issues/413  

### Describe the Issue

Using the following Extensions:
- Unity v0.9.0
- C# Dev Kit v0.3.21
- The other included extensions.

When attempting to format code using a .editorconfig with **Omnisharp: Enable Editor Config Support** on, or with omnisharp.json when it is off, code will not format using given settings.

### Steps To Reproduce

1: Use the above extensions/configurations.
2: Use the following .editorconfig
```
# top-most EditorConfig file
root = true

[*]
indent_style = tab
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

# comment this out if there is nothing inside of it
# dotnet_diagnostic needs to happen after this, not in it
[*.cs]
csharp_new_line_before_open_brace = none
csharp_new_line_before_else = false
csharp_new_line_before_catch = false
csharp_new_line_before_finally = false
```
3: Use the following omnisharp.json
```
{
    "FormattingOptions": {
        "NewLinesForBracesInLambdaExpressionBody": false,
        "NewLinesForBracesInAnonymousMethods": false,
        "NewLinesForBracesInAnonymousTypes": false,
        "NewLinesForBracesInControlBlocks": false,
        "NewLinesForBracesInTypes": false,
        "NewLinesForBracesInMethods": false,
        "NewLinesForBracesInProperties": false,
        "NewLinesForBracesInObjectCollectionArrayInitializers": false,
        "NewLinesForBracesInAccessors": false,
        "NewLineForElse": false,
        "NewLineForCatch": false,
        "NewLineForFinally": false
    }
}
```

4: Write some code similar to:

```csharp
public void Foo() {
    //Test code here.
}
```

5: Format file.

### Expected Behavior

Code should be formatted as such.

```csharp
public void Foo() {
    //Test code here.
}
```

Code is instead formatted as:
```csharp
public void Foo() 
{
    //Test code here.
}
```

**Comment by arkalyanms** [comment] 2023-08-23 23:29
first step might be to confirm if the omnisharp option being selected is the right one. @Cosifne fyi

**Comment by dibarbet** [comment] 2023-08-24 00:48
FYI to whoevers investigating - we don't support omnisharp.json in Roslyn LSP (and don't plan to), however the .editorconfig should be respected.

**Comment by glektarssza** [comment] 2023-09-20 13:54
Quick update; this seems to occur on my Macbook Pro mainly when adding a new file to a project. Other files respect my `.editorconfig` settings but when I add a new file only that file does not respect the settings until I reload my VSCode window.

VSCode Info:

```
Version: 1.82.2
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0
```

VSCode Extension Info:

```
ms-dotnettools.csharp v2.1.2
ms-dotnettools.csdevkit v0.4.10
```

`dotnet --info`:

```
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.401/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  7.0.401 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by dibarbet** [comment] 2023-10-19 18:06
> This forces me to choose between having better debugging support from the Unity extension and better formatting support from the old Omnisharp formatter. I thought that at least I can still use the old formatter, but apparently not. My formatting settings (as specified by either a local ${workspaceFolder}/omnisharp.json or "global" %USERPROFILE%/.omnisharp/omnisharp.json)

@500-internal-server-error would you mind detailing what formatting (and other) settings you're using in omnisharp.json?  It is possible we already support them (via .editorconfig) or we can consider adding them.

**Comment by 500-internal-server-error** [comment] 2023-10-20 03:52
@dibarbet I lost my actual preferred settings<sup>1</sup>, but for my current project I notice it formats using tabs rather than spaces. Actually, it seems to want to follow my VSCode settings (which I have set to use tabs by default), which I don't want it to - thats the entire reason I have a local `omnisharp.json` in the first place, so that regardless of what editor settings anyone may have the formatting after they edit it will be the same.

Also it seems to insist on using CRLF rather than LF. I don't want to deal with that headache, so I prefer to use LF anywhere and anytime, including on Windows.

Regardless, here is my `omnisharp.json`: https://pastebin.com/zhVwTrqb

---

<sup>1</sup>: I used [this method](https://stackoverflow.com/a/60131766) to obtain the default formatting settings for Omnisharp. I had a custom one that made C# look more like Java (K&R-ish instead of Allman-ish), but given how the extension had trouble with tabs and spaces I imagine I would've been even more annoyed if I had used that and suddenly it doesn't do it anymore. I had the exact same VSCode formatting settings and `omnisharp.json` file, but after updating the C# extension and installing the Unity extension (and the other extensions it comes with that I can't get rid of) suddenly Omnisharp formatting broke.

**Comment by dibarbet** [comment] 2023-10-20 06:20
> Actually, it seems to want to follow my VSCode settings (which I have set to use tabs by default), which I don't want it to - thats the entire reason I have a local omnisharp.json in the first place, so that regardless of what editor settings anyone may have the formatting after they edit it will be the same.

@500-internal-server-error
You can add workspace specific settings in a `.vscode/settings.json` file in your workspace to configure the tab settings per language.  This file can be checked in to your repo if you want to ensure others opening the repo use the same settings.  For example:
```
"[csharp]": {
    "editor.insertSpaces": false,
    // Need this if you have existing files with spaces as indentation to force vscode to use tabs instead
    "editor.detectIndentation": false
}
```

Same is possible for end of lines via the `"files.eol": "\n"` setting (note that it only applies to new files - existing files you have to switch via the picker at the bottom right of the vscode window).

To get warnings for either of these settings you can add an .editorconfig to your workspace (this can also be checked in).  I'd recommend that you keep the vscode settings synced with the .editorconfig settings otherwise you'll get a weird experience.  There may be bugs here (as noted in the original description of this issue), let me know if you have problems.  For example in an .editorconfig at your workspace root:
```
root = true

[*.{cs}]
# Set use tabs
indent_style = tab
# Set end of line
end_of_line = lf
# Enable warnings for formatting errors
dotnet_diagnostic.IDE0055.severity = warning
```

I didn't go through every setting in your omnisharp.json, but they appeared to be mainly formatting related.  It is very possible to add those rules to your .editorconfig file as well, see https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/csharp-formatting-options

**Comment by 500-internal-server-error** [comment] 2023-10-20 10:51
@dibarbet Thank you, I will try the `.editorconfig`-based formatting out. A question though, does the link you mention contain all the possible configurations, and will it continue to be updated as configuration options are added and/or removed? If not, where can I find or generate such a document detailing those options, similar to how I was able to generate an `omnisharp.json` containing all the possible configurations from the Omnisharp `.dll` file?

Thanks in advance.

**Comment by dibarbet** [comment] 2023-10-20 17:42
> does the link you mention contain all the possible configurations, and will it continue to be updated as configuration options are added and/or removed?

Generally yes, we should be keeping those docs up to date.  There are more than formatting rules as well, see https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/

> where can I find or generate such a document

It is also possible to generate a .editorconfig file via the dotnet cli - `dotnet new editorconfig` - the template will have a lot of rules configured which you may or may not want, but it should give a good example of what you can do.

**Comment by dibarbet** [comment] 2024-05-23 00:13
Closing this issue.  Using the latest version of the C# extension and C# devkit, I'm able to format the document using the .editorconfig described in the issue using the Roslyn LSP.

We do not support omnisharp.json in the Roslyn LSP (by design), however most settings that could be configured in omnisharp.json are supported in .editorconfig.

If anyone is encountering issues with .editorconfig in the latest versions of the C# extension, please file a new issue.  Thank you!

**Closed by dibarbet** 2024-05-23 00:13 UTC
Labels: Editor-Formatting, EditorConfig
