### ISSUE TITLE
'Accept suggestion on Enter' not working for a particular Unity class

### ISSUE THREAD

**Issue by SweatyTryhardx10** [dotnet/vscode-csharp#6083] opened 2023-08-09 13:55 UTC
Type: <b>Bug</b>

## Issue
Accepting a suggestion, when inserting function calls or variables, using any form of input (e.g. enter, mouse) reverts the text back to the state it was in when the sugggestions list was first shown. __However, this only happens for a particular class.__

**Expected result**
Accepting a suggestion from the suggestions list inserts the suggestion into the script.
**Actual result**
Accepting a suggestion from the suggestions list reverts the code to the state when the suggestions list was initially shown.

## Steps to reproduce
1. Configure VS Code for authoring Unity code by installing the Unity Extension v0.9.0 ([see extension post](https://code.visualstudio.com/docs/other/unity))
2. Download the latest Visual Studio Editor package in Unity
3. Attempt to override SetPosition-function from the UnityEditor.Experimental.GraphView.Node class by typing the following:
    *override S*

Extension version: 1.6.0
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (3.07GB free)|
|Process Argv|D:\\Unity Projects\\Chemical Beats -g D:\\Unity Projects\\Chemical Beats\\Assets\\Scripts\\Editor\\AIBehaviourTree\\GraphNode.cs:1:0 --crash-reporter-id 09d8f480-131b-4380-9e29-c77f065f947c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
f8hc8238:30694864
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofb:30804716
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by dibarbet** [comment] 2023-08-10 01:18
This is a known issue with override completion.  Duplicate of https://github.com/dotnet/vscode-csharp/issues/6011

**Closed by dibarbet** 2023-08-10 01:18 UTC
