### ISSUE TITLE
Variable values cannot be evaluated on debug 

### ISSUE THREAD

**Issue by WardenGnaw** [dotnet/vscode-csharp#6936] opened 2024-02-28 19:02 UTC
Originally from https://github.com/microsoft/vscode-dotnettools/issues/957 by @algot 

----------------------

### Describe the Issue

When I tried to debug a simple code snippet and I was not able to evaluate functions because of an error

`To prevent an unsafe abort when evaluating the function 'OpenQA.Selenium.WebElement.ComputedAccessibleLabel.get' all threads were allowed to run`

Please see screen recording for additional details.
https://imgur.com/a/drDg8wS

At the same time in Visual Studio and Rider there are "reevaluate an expression"/"force refresh" icons
![image](https://github.com/microsoft/vscode-dotnettools/assets/1395043/be56f22d-137f-4661-99a5-5954441a6d29)
![image](https://github.com/microsoft/vscode-dotnettools/assets/1395043/c084c3f3-1831-43b8-bad9-86ad092d47e9)

But VS Code doesn't provide this functionality. Or this is possible with some workaround?

### Steps To Reproduce

- `dotnet new nunit`
- `dotnet add package Selenium.WebDriver`
- `dotnet add package Selenium.WebDriver.ChromeDriver`
- insert code snippet inside `UnitTest1.cs`:

```
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;

namespace selenium_temp;

public class Tests
{
    [Test]
    public void Test1()
    {
        var driver = new ChromeDriver();
        driver.Navigate().GoToUrl("https://www.selenium.dev/selenium/web/web-form.html");
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMilliseconds(500);
        var textBox = driver.FindElement(By.Name("my-text"));
        var submitButton = driver.FindElement(By.TagName("button"));

        textBox.SendKeys("Selenium");
        submitButton.Click();

        driver.Quit();
    }
}
```

- Start the test in debug mode in VS Code.
- Try to evaluate on of the local variable.

### Expected Behavior

Local variables can be evaluated by hovering over it and in Locals/Watch views.

### Environment Information

- macOS 14.3.1
- dotnet 8.0.100
- Selenium.WebDriverC# 4.18.1
- Chrome 122.0.6261.6901
- VS Code 1.86.2

**Comment by gregg-miskelly** [comment] 2024-02-28 19:40
Actually, this is a duplicate of #2613.

**Closed by gregg-miskelly** 2024-02-28 19:40 UTC
Labels: Feature Request, Debugger, Debugger-ExpressionEvaluation
