### ISSUE TITLE
Roslyn showing invalid signature help in completion/diag

### ISSUE THREAD

**Issue by mikadumont** [dotnet/vscode-csharp#5764] opened 2023-06-08 20:44 UTC
C# Extension Version:v2.0.41-beta.gc3fb724edb
C# Dev Kit Extension Version:

Steps to reproduce:

1. Use attached project
2. uncomment line 14 and create a new WebApp ctor 
EXPECT: proper signature help 

ACTUAL: not accurate
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/5e2b8e28-1b51-44ec-bda1-22edc68e3ebd)

VS:
![image](https://github.com/dotnet/vscode-csharp/assets/46729679/ff138382-4d24-4cf7-a695-2ee190c6a1fb)

**Comment by dibarbet** [comment] 2024-07-24 00:42
duplicate of https://github.com/dotnet/vscode-csharp/issues/6670 and fixed in the latest versions of the extension

**Closed by dibarbet** 2024-07-24 00:42 UTC
Labels: Bug, Triaged
