### ISSUE TITLE
Using new language server for < .NET 6

### ISSUE THREAD

**Issue by darichey** [dotnet/vscode-csharp#5847] opened 2023-06-21 18:44 UTC
Hi, the readme calls out that you must revert to the Omnisharp server for projects that require versions prior to .NET 6:
> Note: If working on a solution that requires versions prior to .NET 6, install a Full Framework runtime and MSBuild tooling.
> 
> * Set omnisharp.useModernNet to false and if you are on the pre-release verion, set dotnet.server.useOmnisharp to true
> * Windows: .NET Framework along with MSBuild Tools
> * MacOS/Linux: Mono with MSBuild

I was curious about the underlying reasons for this. Would it be infeasible to support these older versions with the new language server?

Thanks!

**Comment by dibarbet** [comment] 2023-06-21 21:25
We're planning on supporting this scenario in the LSP version of the C# extension for O# parity, but it hasn't arrived yet.

Closing this as a duplicate of https://github.com/dotnet/vscode-csharp/issues/5721

**Closed by dibarbet** 2023-06-21 21:25 UTC
Labels: Resolved-Duplicate, Feature Request, Triaged
