### ISSUE TITLE
C# - Static class not recognized as accessible to newly created classes until VS Code is restarted.

### ISSUE THREAD

**Issue by roblourens** [dotnet/vscode-csharp#2161] opened 2018-04-08 15:48 UTC
_From @keithdfox on April 8, 2018 3:59_

Issue Type: <b>Bug</b>

Example  static class:

`public static class Globals {
	
	public static class InputVals
	{
		public static bool overUI = false;
	}
	
}`

Now create a new class and attempt to access overUI:

`if (Globals.InputVals.overUI) { }`

**Globals** will then be underlined in red with the error:

> The name 'Globals' does not exist in the current context [Assembly-CSharp-firstpass, Assembly-CSharp-Editor-firstpass]

I can reproduce this 100% of the time.

VS Code version: Code 1.22.1 (950b8b0d37a9b7061b6f0d291837ccc4015f5ecd, 2018-04-06T02:26:57.615Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz (4 x 2594)|
|Memory (System)|7.89GB (3.55GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-power-mode|hoo|2.2.0
csharp|ms-|1.14.0
unity-debug|Uni|1.3.0

(12 theme extensions excluded)

</details>

_Copied from original issue: Microsoft/vscode#47414_

**Comment by SirIntruder** [comment] 2018-04-09 22:36
This is a duplicate of those issues:
https://github.com/OmniSharp/omnisharp-vscode/issues/2040
https://github.com/OmniSharp/omnisharp-vscode/issues/1970

anyway most of problems would go away if o# put transient files in only one .csproj in folder instead of all .csproj files in a folder. Assuming Assembly-CSharp would be picked over Assembly-CSharp-firstpass (guess alphabetic sorting would work that out 😆 ) Perfect would be if omnisharp knew to do unity project tie-breaking, but omnisharp shouldn't have to maintain code for this

There is also a bug with interaction between MSBuild project updates and transient files I explained in https://github.com/OmniSharp/omnisharp-vscode/issues/2040, which makes recovering from these errors impossible without omnisharp restart.

**Comment by akshita31** [comment] 2019-03-19 16:27
@SirIntruder Can you confirm if we can close this now ?
@keithdfox Can you try setting "omnisharp.path": "latest" and checking if the error still reproduces?

**Comment by keithdfox** [comment] 2019-03-19 16:40
I'm not using vscode currently

**Comment by Admiralfeb** [comment] 2022-01-22 06:00
I just confirmed this issue in 1.63.2.
I went through the [Xunit tutorial](https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test). As `PrimeService` didn't have any instance, I adjusted the code to make it a static class.

Until VSCode was restarted, the UnitTest file did not pick up the change.

**Comment by JoeRobich** [comment] 2024-11-11 21:40
A lot has changed with project loading and watching since this issue was opened. If you are still running into problems, please open a new issue.

**Closed by JoeRobich** 2024-11-11 21:40 UTC
Labels: OmniSharp
