### ISSUE TITLE
C# extension version greater that 2.0.436 can not find .NET SDK

### ISSUE THREAD

**Issue by moteus** [dotnet/vscode-csharp#6357] opened 2023-09-13 11:57 UTC
## Steps to Reproduce ##
I got this error when run vscode on my local envirnment
### C# log (versoin 2.0.436) ###
<details>Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (undefined) does not match the architecture of the extension (x64).
Dotnet path: /home/amelnichuk/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet
Activating C# standalone...
[Info  - 2:41:10 PM] [Program]Language server initialized
[Info  - 2:41:10 PM] [LanguageServerProjectSystem]Loaded MSBuild at /home/amelnichuk/devtools/dotnet/sdk/6.0.201
[Info  - 2:41:10 PM] [LanguageServerProjectSystem]Loading /home/amelnichuk/repos/tpd/tpd.sln...
</details>

### C# log (versoin 2.2.10) (the same for the 2.1.2) ###
<details>
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (undefined) does not match the architecture of the extension (x64).
Dotnet path: /home/amelnichuk/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet
Activating C# standalone...
[Info  - 2:47:57 PM] [Program] Language server initialized
A compatible .NET SDK was not found.

Requested SDK version: 6.0.200
global.json file: /home/amelnichuk/repos/tpd/global.json

Installed SDKs:
No .NET SDKs were found.

Install the [6.0.200] .NET SDK or update [/home/amelnichuk/repos/tpd/global.json] to match an installed SDK.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[Error - 2:47:58 PM] [LanguageServerHost] System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 147
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 92
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
The architecture of the .NET runtime (undefined) does not match the architecture of the extension (x64).
</details>

## Environment information ##

**VSCode version**: 1.82.1
**C# Extension**: 2.2.10
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.11 [/home/amelnichuk/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/amelnichuk/devtools/dotnet]

global.json file:
  /home/amelnichuk/repos/tpd/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|apache-netbeans-java|asf|19.0.0|asf.apache-netbeans-java-19.0.0|
|code-runner|formulahendry|0.12.0|formulahendry.code-runner-0.12.0|
|csharp|ms-dotnettools|2.2.10|ms-dotnettools.csharp-2.2.10-linux-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|dotnet|formulahendry|0.0.4|formulahendry.dotnet-0.0.4|
|esbuild-problem-matchers|connor4312|0.0.2|connor4312.esbuild-problem-matchers-0.0.2|
|gradle-language|naco-siren|0.2.3|naco-siren.gradle-language-0.2.3|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jestRunIt|vespa-dev-works|0.6.0|vespa-dev-works.jestrunit-0.6.0|
|jupyter|ms-toolsai|2023.8.1002501831|ms-toolsai.jupyter-2023.8.1002501831-linux-x64|
|lua|sumneko|3.7.0|sumneko.lua-3.7.0-linux-x64|
|lua-debug|devCAT|1.1.1|devcat.lua-debug-1.1.1|
|lua-mobdebug|AlexeyMelnichuk|0.0.5|alexeymelnichuk.lua-mobdebug-0.0.5|
|mssql|ms-mssql|1.20.1|ms-mssql.mssql-1.20.1|
|python|ms-python|2023.16.0|ms-python.python-2023.16.0|
|remote-containers|ms-vscode-remote|0.309.0|ms-vscode-remote.remote-containers-0.309.0|
|remote-explorer|ms-vscode|0.4.1|ms-vscode.remote-explorer-0.4.1|
|remote-server|ms-vscode|1.4.3|ms-vscode.remote-server-1.4.3|
|remote-ssh|ms-vscode-remote|0.106.4|ms-vscode-remote.remote-ssh-0.106.4|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.81.3|ms-vscode-remote.remote-wsl-0.81.3|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.2.0|ms-mssql.sql-database-projects-vscode-1.2.0|
|trxviewer|scabana|1.0.3|scabana.trxviewer-1.0.3|
|vscode-docker|ms-azuretools|1.26.0|ms-azuretools.vscode-docker-1.26.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-gradle|vscjava|3.12.7|vscjava.vscode-gradle-3.12.7|
|vscode-gradle-extension-pack|richardwillis|0.0.4|richardwillis.vscode-gradle-extension-pack-0.0.4|
|vscode-icons|vscode-icons-team|12.5.0|vscode-icons-team.vscode-icons-12.5.0|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-language-babel|mgmcdermott|0.0.39|mgmcdermott.vscode-language-babel-0.0.39|
|vscode-npm|fknop|3.3.0|fknop.vscode-npm-3.3.0|
|vscode-npm-scripts|traBpUkciP|0.2.1|trabpukcip.vscode-npm-scripts-0.2.1|
|vscode-proto3|zxh404|0.5.5|zxh404.vscode-proto3-0.5.5|
|vscode-pylance|ms-python|2023.9.10|ms-python.vscode-pylance-2023.9.10|
|vscode-remote-extensionpack|ms-vscode-remote|0.24.0|ms-vscode-remote.vscode-remote-extensionpack-0.24.0|
|yarn-lock-syntax|mariusschulz|0.2.0|mariusschulz.yarn-lock-syntax-0.2.0|;

</details>

**Comment by dibarbet** [comment] 2023-09-13 18:33
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6335 - see https://github.com/dotnet/vscode-csharp/issues/6335#issuecomment-1716563335 for a workaround

**Closed by dibarbet** 2023-09-13 18:33 UTC
