### ISSUE TITLE
`Go To Definition` doesn't show me the actuall implementation (VSCode)

### ISSUE THREAD

**Issue by moamlrh** [dotnet/vscode-csharp#5969] opened 2023-07-29 07:06 UTC
Type: <b>Bug</b>

When I press F12 or use the `Go To Definition` option, it only shows me the definition without any implementation. Similarly, when I click on `Go To Implementation`, it doesn't work either, it shows me **No** Implementation Found For "BlaBla"

Btw I was using `C# Release version` it was work fine tho, but when I upgraded to the pre-release version I got this problem

* It works fine on my own code, but when I'm trying to use it on an external library it will show me just the definition without any implementation.

Sample :
```
public class User : ClassFromExternalLibrary
{
   // code here
}
```
When I press "F12/go-to-def" on `ClassFromExternalLibrary`  will show me the *definition* with this on top of the file:
```
#region Assembly ExternalLibarayNameHere, Version=2.0, Culture=neutral, PublicKeyToken=null
// /home/user/.nuget/packages/ExternalLibarayNameHere/2.0/lib/net6.0/ExternalLibarayNameHere.dll
#endregion
```

I'm using :

- VSCode Information :
Version: 1.80.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.4-200.fc38.x86_64

- C# extension (v2.0.312 "Pre-Release version")
- C# Dev Kit extension (v0.3.18 Pre-Release version)
- Dotnet version (8.0.100-preview.6.23330.14)

- Everything is work fine (autocomplete, intellicode, go-to-def(on my own code))

Extension version: 2.0.312
VS Code version: Code 1.80.2 (2ccd690cbff1569e4a83d7c43d45101f817401dc, 2023-07-27T20:41:52.615Z)
OS version: Linux x64 6.4.4-200.fc38.x86_64
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30792625
gsofa:30797621
pythonnosmt12:30797651
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014:30797589

```

</details>

**Comment by moamlrh** [comment] 2023-08-14 13:55
any updates ? @dibarbet

**Comment by moamlrh** [comment] 2023-08-14 21:41
Exactly, I was trying to to see the implementation/code of any external function/class like _a function from Nuget package_

Btw I solved the issue by disabled ```
C# DevKit
``` extension, I'm not sure if it was an issue with ```
C# DebKit
```

But I do need to use this extension `C# DevKit`

**Comment by CyrusNajmabadi** [comment] 2023-08-21 19:30
Dupe of: https://github.com/dotnet/vscode-csharp/issues/5969

**Comment by dibarbet** [comment] 2023-08-21 20:17
@CyrusNajmabadi the dupe links to this issue.  Meant to link another one?

**Closed** 2023-08-21 23:34 UTC
Labels: Editor-Go To Definition

**Comment by dibarbet** [comment] 2023-08-28 21:08
This should be in this weeks release (Wednesday).

**Comment by JasonLeeForOnly** [comment] 2023-09-07 06:13
Same problem here,Was the lateset version of C# DevKit settled?

**Comment by christophwille** [comment] 2023-09-07 10:48
It does work, but you need what we described here https://twitter.com/ilspy/status/1697115935629267198

Enable dotnet.navigation.navigateToDecompiledSource
![image](https://github.com/dotnet/vscode-csharp/assets/344208/c07e060d-2afd-4cfb-b593-2c640df56e66)

**Comment by moamlrh** [comment] 2023-09-07 11:26
>  NEED HELP Unable to decompile and view the classes of interfaces in the assembly.
> 
> Name: C# Dev Kit ID: ms-dotnettools.csdevkit Version: 0.5.2

It works for me on this version `v2.0.436` 

![image](https://github.com/dotnet/vscode-csharp/assets/63509020/0ae037ce-2ba7-4557-b664-11c4a0c351e3)
![image](https://github.com/dotnet/vscode-csharp/assets/63509020/80b95529-e5d9-4448-bc0b-d86234d2b2f9)

**Comment by nhoefer2** [comment] 2024-07-22 04:55
What if I wanted to view the source of packages using the package symbols?
I find this very odd because when I ctrl+click something, it will take me to the decompiled code but when I step into the code from the debugger (which uses the symbols), it gives me very different code.  It almost seems like a bug because when I step into the code with the debugger, it shows me the source from the symbols but its not actually running that code. Instead, it behaves like its running the compiled binary. I'm seeing weird things when debugging like a function returning when stepping over a line that doesn't even have a return (not from an exception thrown). Has anyone else ever encountered this?

**Comment by dibarbet** [comment] 2024-07-22 17:52
> I find this very odd because when I ctrl+click something, it will take me to the decompiled code but when I step into the code from the debugger (which uses the symbols), it gives me very different code

It is possible you're seeing the [sourcelink](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) source in the debugger - which is the real, not decompiled source.  We are tracking enabling source link for goto definition here - https://github.com/dotnet/vscode-csharp/issues/6784

> Instead, it behaves like its running the compiled binary. I'm seeing weird things when debugging like a function returning when stepping over a line that doesn't even have a return (not from an exception thrown). Has anyone else ever encountered this?

If you're debugging a binary built with optimizations enabled (e.g. release mode) this can happen with either decompiled source or source link source.
