### ISSUE TITLE
OmniSharp does not respect `files.exclude`

### ISSUE THREAD

**Issue by firelizzard18** [dotnet/vscode-csharp#1694] opened 2017-08-09 19:26 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

VS Code version: Code 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e, 2017-07-19T23:34:09.706Z)
C# Extension version: csharp|ms-|1.11.0

## Steps to reproduce
Open VSCode on a directory that has projects (mine are in subfolders) that are excluded by `files.exclude` (I'm doing it from `.vscode/settings.json`).

## Expected  behavior
OmniSharp does not try to process projects within excluded folders.

## Actual behavior
OmniSharp tries to process projects within excluded folders.

## Other Details
I'm transitioning a large project (50+ libraries, 5+ apps) from MSBuild (Visual Studio) to dotnet (VSCode). I have configured VSCode to ignore all the projects that have not been transitioned yet. OmniSharp is trying to process the un-transitioned projects.

**Comment by DustinCampbell** [comment] 2017-08-09 19:27
Thanks for the request. This is a good feature request.

**Comment by nihique** [comment] 2017-10-02 10:33
+1

**Comment by sequitur** [comment] 2017-10-04 12:58
Right now my "problems" panel on a C# has well over 99 problems (no literally), all of them in vendor code, which renders the feature kind of useless. Is there a workaround or another configuration I can change to prevent this from happening?

**Comment by joopscheer** [comment] 2017-10-09 07:50
Having the same problems as @sequitur. In the settings.json the "obj" and "bin" directories are in the "files.exclude" section. However the generated AssemblyInfo.cs files are still analysed. This results in warnings like "Unnecessary using directive.'.

**Comment by DustinCampbell** [comment] 2017-10-09 13:50
> Having the same problems as @sequitur. In the settings.json the "obj" and "bin" directories are in the "files.exclude" section. However the generated AssemblyInfo.cs files are still analysed. This results in warnings like "Unnecessary using directive.'.

One option is to set the `csharp.suppressHiddenDiagnostics` setting to true. This will keep diagnostics that are "hidden", such as remove unnecessary usings, from displaying in the editor and the problems pane. That means that remove unnecessary usings also won't squiggle in open files, but the light bulb will still be available to use.

I should mention that this particular feature request is about using `files.exclude` to help inform the projects that OmniSharp processes. It isn't about getting it to somehow ignore files in processed projects that might contain files that belong to the project. OmniSharp will always process files in "obj" because MSBuild will use it when processing the project. Ignoring files in "obj" could introduce errors in other files for certain project types.

**Comment by ghandmann** [comment] 2018-03-22 12:52
Is there any progress so far with this? Currently this issue renders VS Code useless for me, since the whole IntelliSense is broken down, because of one subproject. Quite frustrating.

**Comment by rchande** [comment] 2018-04-11 19:40
@ghandmann This is being worked on in https://github.com/OmniSharp/omnisharp-vscode/pull/2171

**Comment by andrewb273** [comment] 2019-10-01 23:16
I see #2171 has been merged in, yet I'm still facing the same issue: OmniSharp is trying to load a .Net Framework project for which I've explicitly excluded the .csproj of.

**Comment by kaleidawave** [comment] 2019-10-12 10:20
Any updates on this. I am working on a WPF project and OmniSharp is currently telling all my classes have already be implemented as it is scanning the `obj` folder.

**Comment by Saltallica** [comment] 2019-11-14 20:15
Agreed - very annoying.

**Comment by mrjohnr** [comment] 2020-01-22 10:59
same problem here using Local history extension that creates .history folder inside project root,need a way to exclude it.thanks

**Comment by dotaxis** [comment] 2020-01-26 10:51
Create omnisharp.json in %userprofile%/.omnisharp/ or ~/.omnisharp/ on OSX/Linux

```
{
  "omnisharp.enableRoslynAnalyzers": true,
  "fileOptions": {
    "systemExcludeSearchPatterns": ["**/.history/**"]
  }
}
```

Pretty sure the enableRoslynAnalyzers bit is what fixed it for me.

**Comment by rickvanprim** [comment] 2020-01-26 18:39
It looks like this can be done separately through an `omnisharp.json` file in the root of the workspace: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#file-options

**Comment by mrjohnr** [comment] 2020-01-27 07:18
I have no default omnisharp.json file in VsCode/user data,I've placed one in my project folder but not working :(

**Comment by dotaxis** [comment] 2020-01-28 19:22
> 
> 
> It looks like this can be done separately through an `omnisharp.json` file in the root of the workspace: https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#file-options

That setting doesn't do anything.

**Comment by filipw** [comment] 2020-01-28 19:28
it controls solutions/project file discovery, not individual cs files.

**Comment by dotaxis** [comment] 2020-01-29 01:42
Can we get something that ignores individual `.cs` files then? Or rather, files of any type?

**Comment by filipw** [comment] 2020-01-29 05:50
that is a csproj project file feature
https://stackoverflow.com/a/43219140

OmniSharp is only concerned with finding sln/csproj file to start with, after that MSBuild is responsible for processing everything

**Comment by dotaxis** [comment] 2020-01-29 16:26
Is it out of the question to have an override in OmniSharp that at least ignores errors in specified files/folders?

When I use external libraries I get hundreds of messages about stuff like naming conventions, 'can be readonly', etc. 

If there's already some way to do this I'm all ears.

**Comment by hsnabn** [comment] 2020-06-09 12:27
Leaving a comment in case anyone ends up here from Google (this is the top result when I search 'vscode c# ignore folder':

I managed to get the analyzers to ignore folders/files thru using `.editorconfig` (might need to enable it in vscode c# settings): [](https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#configure-generated-code)

```
[Folder/**.cs]
generated_code = true
```

Telling omnisharp that it's generated code seems to keep it from analyzing.

(Unfortunately in my case the folder I wanna exclude is an outside package which I wanna ignore; unfortunately they have their own `.editoconfig` with `root = true` and mine's getting overridden. That's another problem though.)

**Comment by kinosang** [comment] 2020-07-06 08:53
I have "**/artifacts" in `files.exclude`, and have set `generated_code = true` for `[artifacts/**.cs]` in my `.editorconfig`, but OmniSharp still reports errors from `artifacts/obj/**.cs`.

**Comment by SamMacedo** [comment] 2020-07-31 02:38
I can confirm as well that `.editorconfig` file as suggested doesn't work for me in vscode, errors are still reported.

**Comment by felipesdias** [comment] 2021-02-23 12:19
> I have "**/artifacts" in `files.exclude`, and have set `generated_code = true` for `[artifacts/**.cs]` in my `.editorconfig`, but OmniSharp still reports errors from `artifacts/obj/**.cs`.

I have the same problem

**Comment by kazinad** [comment] 2021-04-30 09:51
I experience the followings:

1. You need to have both a) _omnisharp.json_ b) _.editorconfig_
2. _omnisharp.json_ _fileOptions_ must have _excludeSearchPatterns_ setting only, remove _systemExcludeSearchPatterns_ completely if you have that one.
3. you have to enable _omnisharp.enableEditorConfigSupport_ setting, as mentioned above.

**Comment by fgimian** [comment] 2021-07-11 11:40
I hope everyone is doing well.  I personally have not had any luck with any of the approaches mentioned so far.

This all started when I configured unused using statements to be warnings (as I was missing them in my own code).

Here's what I added to my .editorconfig:

```ini
# Ensure that unused using statements are treated as warnings.
dotnet_diagnostic.CS8019.severity = warning
```

Now, OmniSharp is complaining about unused imports in various *.cs files in the obj\Debug directory of my project.

So I created an omnisharp.json at the root of my project with the following contents:

```json
{
  "fileOptions": {
    "excludeSearchPatterns": ["**/obj/**/*"]
  }
}
```

Just for fun, I also tried the `systemExcludeSearchPatterns` setting with the same pattern.

I also added the following to my .editorconfig:

```ini
[**/obj/**/*.cs]
generated_code = true
```

I also tried this variant:

```ini
[**/obj/**.cs]
generated_code = true
```

But sadly, I continue to see these warnings in my PROBLEMS tab.

Has anyone gotten this working for *.cs files in their obj directory?

Thanks heaps
Fotis

**Comment by DasOhmoff** [comment] 2022-05-16 23:22
I have this same issue. Are there any news on this?

**Comment by JoeRobich** [comment] 2024-11-08 23:30
Trying to summarize this problems that prompted this issue.

1. Folder contains a large number of projects.
  
  The C# extension is concerned with loading Solutions or Projects. 

  If you are opening a solution with a large number of projects and want to open fewer, then this is a good use case for solution filters (.slnf). Read for more info https://devblogs.microsoft.com/visualstudio/load-only-the-projects-you-need-with-solution-filters/
  If you do not have a solution file and the extension is loading every project file for you, then you can enable MSBuild Load Project on Demand
![Image](https://github.com/user-attachments/assets/26993324-3678-4655-9d1a-6d8fc4197b11)

2. Diagnostics reported on generated files in the /obj folder or for folders containing assets.

For that you can use the .editorconfig to mark certains folders as "generated" and those will be ignored during analysis. See this comment for an example https://github.com/dotnet/vscode-csharp/issues/1694#issuecomment-666880312

**Closed by JoeRobich** 2024-11-08 23:30 UTC
Labels: Feature Request, OmniSharp
