### ISSUE TITLE
Intellisense autocomplete/suggestions not working on debug console on C# console projects 

### ISSUE THREAD

**Issue by devmet34** [dotnet/vscode-csharp#4862] opened 2021-10-30 11:41 UTC
Issue Type: <b>Bug</b>

To reproduce problem; open a new folder then create a c# console project entering "dotnet new console" command on terminal window. In the Main method place a breakpoint, debug the app. After progam paused on breakpoint test intellisense on debug console.

Vscode and extensions are up to date. 

Extension version: 1.23.16
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:57:20.575Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30384385
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedc:30364665
pythonvspyt187:30373474
vsqsis200:30386379
vsaa593:30376534
vssld246:30386377

```

</details>

**Comment by navidkhalilian** [comment] 2021-11-08 15:24
"Go to Definition" still gives "No definition found" for everything.

Extension version: 1.23.16
VS Code version: Version: 1.62.0 
OS: Windows_NT x64 10.0.22000

**Comment by stantoxt** [comment] 2022-11-23 09:07
I have the same problem

**Comment by gregg-miskelly** [comment] 2023-09-29 16:35
This is a dupe of https://github.com/dotnet/vscode-csharp/issues/299

**Closed by gregg-miskelly** 2023-09-29 16:35 UTC
Labels: OmniSharp
