### ISSUE TITLE
Autocomplete suggestions for override methods starting with an "_" not working.

### ISSUE THREAD

**Issue by mediad02** [dotnet/vscode-csharp#5892] opened 2023-07-05 00:48 UTC
## Steps to reproduce

1. Make a new project
2. have 2 classes, one that inherits from the other
3. within the base class create a virtual method that starts with  an "_"
4. within the child class override the method and wait till vs code suggest the base method.
5. hit tab to autocomplete suggestion

## Expected  behavior
the base method should be inserted.

## Actual behavior
nothing happens, suggestion is not inserted.

## Additional context
most methods in the Godot engine that need to be overridden within every script start with "_" (eg. "_Draw", "_Process", "_PhysicsProces", etc.), having the autocomplete not working is really annoying .

![image](https://github.com/dotnet/vscode-csharp/assets/20409010/6d166d66-5684-4e24-ae98-401098fe60d8)

**Comment by dibarbet** [comment] 2023-08-11 21:50
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6011

**Closed by dibarbet** 2023-08-11 21:50 UTC
Labels: Bug, Completion
