### ISSUE TITLE
Command 'charp.reportIssue' not found

### ISSUE THREAD

**Issue by RussKie** [dotnet/vscode-csharp#5827] opened 2023-06-19 06:59 UTC
## Environment data

<details>
<summary>dotnet --info</summary>

```
.NET SDK:
 Version:   8.0.100-preview.6.23309.5
 Commit:    c10115c483

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   D:\Development\dotnet-extensions\.dotnet\sdk\8.0.100-preview.6.23309.5\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23316.3
  Architecture: x64
  Commit:       76da696f3f

.NET SDKs installed:
  8.0.100-alpha.1.23061.8 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.1.23115.2 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.2.23115.11 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.3.23127.4 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.4.23171.22 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.4.23212.7 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.5.23254.16 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.5.23259.9 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.5.23261.16 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.6.23309.5 [D:\Development\dotnet-extensions\.dotnet\sdk]
  8.0.100-preview.6.23316.32 [D:\Development\dotnet-extensions\.dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-alpha.1.23058.7 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.1.23112.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.2.23107.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23126.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23171.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23207.6 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23252.26 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.5.23260.10 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23307.4 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23316.5 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23057.5 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-alpha.1.23058.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.1.23110.8 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23107.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.2.23126.3 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23170.14 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23210.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23252.13 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.5.23260.3 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23307.4 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23316.3 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.0-alpha.1.23057.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.1.23112.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.2.23106.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.2.23125.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23169.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.4.23178.3 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23252.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.5.23261.2 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23307.1 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23316.4 [D:\Development\dotnet-extensions\.dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  DOTNET_ROOT       [D:\Development\dotnet-extensions\.dotnet]
```

</details>

VS Code version:
![image](https://github.com/dotnet/vscode-csharp/assets/4403806/4b19a4fe-1169-4141-977b-f4ce1d262b55)

C# Extension version:
![image](https://github.com/dotnet/vscode-csharp/assets/4403806/fba73e3d-c078-4a86-9c7d-0fb65ee426a1)

## Steps to reproduce

1. Open Visual Studio Code
2. Bring up the command palette (press <kbd>F1</kbd>)
3. Type `CSharp: Report an issue`

If the `CSharp: Report an issue` command doesn't appear, make sure that you have C# extension version 1.17.0 or newer installed.

## Expected  behavior

Can report the issue 🤷‍♂️

## Actual behavior

![image](https://github.com/dotnet/vscode-csharp/assets/4403806/e6af7020-1713-4ed0-af06-9f3bf9647e28)

**Comment by dibarbet** [comment] 2023-06-20 19:23
Thanks - duplicate of https://github.com/dotnet/vscode-csharp/issues/5747

**Closed by dibarbet** 2023-06-20 19:23 UTC
Labels: Bug, Resolved-Duplicate, Triaged
