### ISSUE TITLE
How to set to use .NET 8.0 SDK for LSP?

### ISSUE THREAD

**Issue by segln** [dotnet/vscode-csharp#5715] opened 2023-06-07 10:37 UTC
Are there any options like `Omnisharp: Sdk Path` or `Omnisharp: Sdk Version`?

**Comment by iRebbok** [comment] 2023-06-07 21:02
I have a project that targets .NET 8, upon first start the extension downloaded .NET 7.0.2, even though the project has a `global.json` file next to the solution file. It did load, however, the LSP functioned badly, it didn't provide any code navigation for BCL types and false positively marked `using`s as unnecessary. After I set `dotnet.dotnetPath` setting to `C:/Program Files/dotnet/` (is default .NET installation path & contains `dotnet.exe`), it worked fine. I consider a setting to use default .NET installation is a need and only then fallback to the downloaded one with `global.json` in mind.

**Comment by lifengl** [comment] 2023-06-07 21:37
it might be a little bit confusing when you saw the extension downloaded NET 7.0.2, instead of the SDK of your project. Actually, the extension does not install SDK for you. It is in the backlog, but not a part of this preview release. Also even the extension started to support that, it would not cover all different distributions of Linux, and depending on your working environment, you may still need to do it manually.

The NET 7.02 runtime was downloaded for the extension itself. Basically, processes for the extension tooling part and processes to build/compile your project are two separated groups. Tooling processes use a fixed predefined version of runtime, which it downloads, and the project is built with a version of SDK selected by the developer or the project, possibly by using a global.json file.

**Comment by segln** [comment] 2023-06-08 00:01
Are there any plans to change to use pre-installed .NET CLI?

If the option to use pre-installed .NET is not added, I don't think LSP will be available for projects that use preview .NET versions.

**Comment by segln** [comment] 2023-06-08 00:06
Are there any plans to add an option to use pre-installed .NET CLI?

If the option to use pre-installed .NET is not added, I don't think LSP will be available for projects that use preview .NET versions.

Currently extension complains to every files within 8.0 project.

**Comment by dibarbet** [comment] 2023-06-08 18:42
We should be able to support loading preview .NET versions without needing to specify the old SdkPath/Version options as long as you have the right SDK installed.  However, it looks like there are currently issues with loading .NET 8 projects in devkit, see https://github.com/microsoft/vscode-dotnettools/issues/15 which you might be running into.

Going to close this as a duplicate of that issue.

**Closed** 2023-06-08 18:42 UTC
Labels: Needs More Info, Triaged
