### ISSUE TITLE
Intellisence not working in newest version (v 2.0.328)

### ISSUE THREAD

**Issue by ZhouYixxx** [dotnet/vscode-csharp#6056] opened 2023-08-07 02:14 UTC
Long story short, the Intellisence stops working when I updated the C# extension to the newest version(`v 2.0.328`) . I solved this issue by reverting the extension to  `v1.26.0 `.  Hope to find out what happens in the latest release soon. I attached some screenshots below.

 
![image](https://github.com/dotnet/vscode-csharp/assets/30408606/1422a894-511c-496c-98ce-d479f91713e0)

![image](https://github.com/dotnet/vscode-csharp/assets/30408606/3b57336d-cf5f-48d8-98c4-fd910492991c)

**Comment by AdamRussak** [comment] 2023-08-07 07:23
partly solved for me by enabling omni server...

**Comment by anvardjumaev** [comment] 2023-08-07 10:36
I noticed something strange last week when my VS Code started installing a dotnet version but didn't give it too much attention. 

Today I see this in the C# output 

```
Dotnet path: /Users/anvar.djumaev/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
```

This is definitely not the version I was using before, maybe it's related?

**Comment by arkalyanms** [comment] 2023-08-07 16:23
@ZhouYixxx would you share the C# log on v 2.0.328 from when intellisense does not work?

> in the extension output I see its stuck...

@AdamRussak that log message is misleading although the server completely started. It was fixed last week.

**Comment by AdamRussak** [comment] 2023-08-07 16:26
None fhe less I got some intelisense only by rolling back.

**Comment by jtotht** [comment] 2023-08-07 17:53
> @ZhouYixxx would you share the C# log on v 2.0.328 from when intellisense does not work?

I’m also facing this issue. The log output, if I select _C#_ from the dropdown, is exactly what @AdamRussak shared in https://github.com/dotnet/vscode-csharp/issues/6056#issuecomment-1667328094, except that the _Dotnet path_ is different because I’m on Windows. I’ve left it running for like five minutes, tried to use IntelliSense, hover over things I should get a popup description of (methods, variables etc.), but I didn’t get more output (nor did these things work).

**Comment by JustinGrote** [comment] 2023-08-07 21:22
Probably dupe of: https://github.com/dotnet/vscode-csharp/issues/6024

**Comment by ZhouYixxx** [comment] 2023-08-09 07:09
> @ZhouYixxx would you share the C# log on v 2.0.328 from when intellisense does not work?
> 
> > in the extension output I see its stuck...
> 
> @AdamRussak that log message is misleading although the server completely started. It was fixed last week.

OK, on the whole I got the same output just as @AdamRussak put.  **This issue Probably dupe of: https://github.com/dotnet/vscode-csharp/issues/6024** Here is the output of `V1.26.0` in which the intellisence works properly.

> Starting OmniSharp server at 8/9/2023, 2:56:33 PM
>     Target: d:\VS2022_repos\Leetcode-Solutions\VSCode_Practice
> 
> OmniSharp server started with .NET 7.0.100
> .
>     Path: c:\Users\BG-007\.vscode\extensions\ms-dotnettools.csharp-1.26.0-win32-x64\.omnisharp\1.39.7-net6.0\OmniSharp.dll
>     PID: 22184
> 
> [info]: OmniSharp.Stdio.Host
>         Starting OmniSharp on Windows 10.0.19045.0 (x64)
> [info]: OmniSharp.Services.DotNetCliService
>         Checking the 'DOTNET_ROOT' environment variable to find a .NET SDK
> [info]: OmniSharp.Services.DotNetCliService
>         Using the 'dotnet' on the PATH.
> [info]: OmniSharp.Services.DotNetCliService
>         DotNetPath set to dotnet
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Located 1 MSBuild instance(s)
>             1: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
> [info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
>         Registered MSBuild instance: .NET Core SDK 7.0.100 17.4.0 - "C:\Program Files\dotnet\sdk\7.0.100\"
> [info]: OmniSharp.WorkspaceInitializer
>         Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Detecting Cake files in 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice'.
> [info]: OmniSharp.Cake.CakeProjectSystem
>         Did not find any Cake files
> [info]: OmniSharp.MSBuild.ProjectSystem
>         No solution files found in 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Queue project update for 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj'
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Detecting CSX files in 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice'.
> [info]: OmniSharp.Script.ScriptProjectSystem
>         Did not find any CSX files
> [info]: OmniSharp.WorkspaceInitializer
>         Configuration finished.
> [info]: OmniSharp.Stdio.Host
>         Omnisharp server running using Stdio at location 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice' on host 17396.
> [info]: OmniSharp.MSBuild.ProjectManager
>         Loading project: d:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj
> [warn]: OmniSharp.MSBuild.ProjectLoader
>         You are running the 'restore' operation with an 'HTTP' source, 'http://nexus.playco.cn/repository/nuget-hosted/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> [info]: OmniSharp.MSBuild.ProjectManager
>         Successfully loaded project file 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj'.
> d:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj
> d:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj(0,0): Error: You are running the 'restore' operation with an 'HTTP' source, 'http://nexus.playco.cn/repository/nuget-hosted/'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
> 
> [info]: OmniSharp.MSBuild.ProjectManager
>         Adding project 'd:\VS2022_repos\Leetcode-Solutions\VSCode_Practice\VSCode_Practice.csproj'
> [info]: OmniSharp.MSBuild.ProjectManager
>         Update project: VSCode_Practice

Here is the output of `v 2.0.328`, it seems stuck.

> Dotnet path: c:\Users\BG-007\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
> Activating C# + C# Dev Kit + C# IntelliCode...
> info: LanguageServerHost[0]
>       Starting server...

**Comment by ZhouYixxx** [comment] 2023-08-09 07:12
> > @ZhouYixxx would you share the C# log on v 2.0.328 from when intellisense does not work?
> 
> I’m also facing this issue. The log output, if I select _C#_ from the dropdown, is exactly what @AdamRussak shared in [#6056 (comment)](https://github.com/dotnet/vscode-csharp/issues/6056#issuecomment-1667328094), except that the _Dotnet path_ is different because I’m on Windows. I’ve left it running for like five minutes, tried to use IntelliSense, hover over things I should get a popup description of (methods, variables etc.), but I didn’t get more output (nor did these things work).

FYI reverting the extension to v1.26.0 fixed this issue

**Comment by jtotht** [comment] 2023-08-09 11:36
> FYI reverting the extension to v1.26.0 fixed this issue

Thanks, I know, but I wanted to help this bug be fixed as soon as possible, as reverting is not a long-term solution.

**Comment by arkalyanms** [comment] 2023-08-11 23:28
[2.0.357](https://github.com/dotnet/vscode-csharp/releases/tag/v2.0.357) added release version support for opening projects without a solution file and thereby getting intellisense for those projects. 

@ZhouYixxx / @jtotht would you confirm if that solves your issue?

**Comment by dylantf** [comment] 2023-08-12 13:14
My extension just updated to 2.0.357 and I'm not getting any intellisense at all, it's giving me the no .net sdks found error. Not sure what's going on here, `dotnet --version` lists 7.0.100, and my F# intellisense works just fine.

**Comment by arkalyanms** [comment] 2023-08-14 19:24
@dylantf in your case, did it regress in 2.0.357? If yes, would you confirm if the _.NET Install Tool for Extension Authors_ is installed successfully?

**Comment by ZhouYixxx** [comment] 2023-08-15 02:58
> @dylantf in your case, did it regress in 2.0.357? If yes, would you confirm if the _.NET Install Tool for Extension Authors_ is installed successfully?

I updated to `v2.0.357` but the problem still there. I have a solution file (.sln) and project file (.csporj) in my workspace folder.
![image](https://github.com/dotnet/vscode-csharp/assets/30408606/9876fcf5-0871-44f8-9a9b-9aa086d8f95f)

**Comment by ZhouYixxx** [comment] 2023-08-15 06:15
> [2.0.357](https://github.com/dotnet/vscode-csharp/releases/tag/v2.0.357) added release version support for opening projects without a solution file and thereby getting intellisense for those projects.
> 
> @ZhouYixxx / @jtotht would you confirm if that solves your issue?

Well I think I found more info about this issue. When I open the folder which contains the .sln file, the intellisence works well. Instead when I open a folder with higher level, the intellisence broke. For example, suppose I have a folder like this:

![image](https://github.com/dotnet/vscode-csharp/assets/30408606/ef719f67-541a-4f5f-9efa-39a2adc6b459)

**the intellisence works fine when I open  the folder `Project_CSharp` and stops working when I open the higher folder `Projects`**. Hope it helps you troubleshooting.

**Comment by genlu** [comment] 2023-08-15 20:08
> the intellisence works fine when I open the folder Project_CSharp and stops working when I open the higher folder Projects

Thanks for the additional info. Could you please try this command to specify the solution file, and see if it solves your problem?

![Image](https://github.com/dotnet/vscode-csharp/assets/788783/ff22de08-33b7-4d29-afb6-cf00f7ac28da)

**Comment by LuckyKang79** [comment] 2023-08-21 08:49
This issue is also reproduced on the latest version of the C# extension (v2.0.376)

**Comment by ZhouYixxx** [comment] 2023-08-22 06:26
> > the intellisence works fine when I open the folder Project_CSharp and stops working when I open the higher folder Projects
> 
> Thanks for the additional info. Could you please try this command to specify the solution file, and see if it solves your problem?
> 
> ![Image](https://user-images.githubusercontent.com/788783/260826227-ff22de08-33b7-4d29-afb6-cf00f7ac28da.png)
> 
> Also, in your `Projects\.vscode\settings.json` file, is there a "dotnet.defaultSolution" entry?

GREAT news: The issue fixed after executing Command `.Net: Open Solution`. 
and the file `Projects\.vscode\settings.json` not exists but there is a setting file `Projects\Project_CSharp\.vscode\settings.json` and it indeed contains a "dotnet.defaultSolution" entry.

**Closed** 2023-08-22 18:05 UTC
Labels: Editor-IntelliSense, Needs More Info, Needs Confirmation

**Comment by genlu** [comment] 2023-08-22 18:06
@ZhouYixxx Thanks for confirming. Closed as the original issue was resolved by explicitly selecting a solution file
