### ISSUE TITLE
How to see decompiled C# code in VS Code using LSP

### ISSUE THREAD

**Issue by AleksandarDevic** [dotnet/vscode-csharp#6243] opened 2023-08-27 10:26 UTC
# Describe the bug
Hi, 

I want to see decompiled code for example(when I click on OAuth on line 16):

![example](https://github.com/dotnet/vscode-dotnet-runtime/assets/43075620/b040b4bb-63fa-4431-b793-204f626bab41)

I can only see this in VSCode:

![image-VSCode](https://github.com/dotnet/vscode-dotnet-runtime/assets/43075620/66761ea1-670d-4319-8bac-816f62ba0eae)

But on Rider IDE shows implementation for that and I see how OAuth is implemented etc.:

![image-Rider](https://github.com/dotnet/vscode-dotnet-runtime/assets/43075620/902ade2b-d1cf-4116-91c4-751585599d6e)

I also setup VSCode settings to this:
![image](https://github.com/dotnet/vscode-dotnet-runtime/assets/43075620/8844885e-b65b-4e5e-b809-b1837c17d5f0)

I used C# extension only but also install and Dev Kit extension but also with that I can't see decompiled source.

Please can you help me how to enable some settings to see decompiled source in order to see how some part of OAuth is implemented under the hood?

I need to mention **I use LSP** _not OmniSharp_ and set **dotnet.server.trace**.
 

## **Please attach log file(s) here if you have any:**
>❗ Privacy Alert! The contents in our log files may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:28.551][Start]textDocument/hover
[LanguageServerHost][10:15:28.555][End]textDocument/hover
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:30.188][Start]textDocument/definition
[LanguageServerHost][10:15:30.200][End]textDocument/definition
[LanguageServerHost][10:15:30.214][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs
[LanguageServerHost][10:15:30.215][End]textDocument/didOpen
[LanguageServerHost][10:15:30.215][Start]textDocument/didClose
[LanguageServerHost]didClose for file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs
[LanguageServerHost][10:15:30.215][End]textDocument/didClose
[LanguageServerHost]Closing workspace/diagnostics request
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:30.287][End]workspace/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:30.335][Start]textDocument/definition
[LanguageServerHost][10:15:30.345][End]textDocument/definition
[LanguageServerHost][10:15:30.361][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs
[LanguageServerHost][10:15:30.362][End]textDocument/didOpen
[LanguageServerHost][10:15:30.362][Start]textDocument/didClose
[LanguageServerHost]didClose for file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs
[LanguageServerHost][10:15:30.362][End]textDocument/didClose
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:30.688][Start]textDocument/hover
[LanguageServerHost][10:15:30.691][End]textDocument/hover
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:31.265][Start]textDocument/definition
[LanguageServerHost][10:15:31.274][End]textDocument/definition
[LanguageServerHost][10:15:31.308][Start]textDocument/didOpen
[LanguageServerHost]didOpen for file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs
[LanguageServerHost][10:15:31.308][End]textDocument/didOpen
[LanguageServerHost]Could not find 'file:///c:/Users/aleksandar/AppData/Local/Temp/MetadataAsSource/7aef6cfc0a4845e59c0825f3ed0b3993/DecompilationMetadataAsSourceFileProvider/48d72809366e4a7a965378797900516e/OAuthExtensions.cs'.  Searched Host;MiscellaneousFiles
[LanguageServerHost][10:15:31.309][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Found 0 diagnostics for DocumentDiagnosticSource: c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:31.310][End]textDocument/diagnostic
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.316][Start]textDocument/codeAction
[LanguageServerHost][10:15:31.318][End]textDocument/codeAction
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.320][Start]textDocument/documentSymbol
[LanguageServerHost][10:15:31.323][End]textDocument/documentSymbol
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.371][Start]textDocument/inlayHint
[LanguageServerHost][10:15:31.371][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.491][Start]textDocument/semanticTokens/range
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:31.492][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs in Skeleton.Api
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:31.492][End]textDocument/diagnostic
[LanguageServerHost][10:15:31.495][End]textDocument/semanticTokens/range
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.588][Start]textDocument/codeAction
[LanguageServerHost][10:15:31.602][End]textDocument/codeAction
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.613][Start]textDocument/foldingRange
[LanguageServerHost][10:15:31.614][End]textDocument/foldingRange
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:31.697][Start]textDocument/codeLens
[LanguageServerHost][10:15:31.698][End]textDocument/codeLens
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:32.081][Start]codeLens/resolve
[LanguageServerHost][10:15:32.086][End]codeLens/resolve
[LanguageServerHost][10:15:32.297][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]Closing workspace/diagnostics request
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicWorkspacePullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:32.297][End]workspace/diagnostic
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:33.324][Start]textDocument/diagnostic
[LanguageServerHost][10:15:33.324][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:33.325][End]textDocument/diagnostic
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs in Skeleton.Api
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:33.326][End]textDocument/diagnostic
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:33.561][Start]textDocument/hover
[LanguageServerHost][10:15:33.561][End]textDocument/hover
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:33.702][Start]textDocument/codeLens
[LanguageServerHost][10:15:33.702][End]textDocument/codeLens
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:34.081][Start]codeLens/resolve
[LanguageServerHost][10:15:34.082][End]codeLens/resolve
[LanguageServerHost][10:15:34.305][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:34.853][Start]textDocument/inlayHint
[LanguageServerHost][10:15:34.853][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:34.902][Start]textDocument/inlayHint
[LanguageServerHost][10:15:34.902][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:35.218][Start]textDocument/inlayHint
[LanguageServerHost][10:15:35.218][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:35.402][Start]textDocument/inlayHint
[LanguageServerHost][10:15:35.403][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:36.068][Start]textDocument/inlayHint
[LanguageServerHost][10:15:36.068][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:36.182][Start]textDocument/semanticTokens/range
[LanguageServerHost][10:15:36.184][End]textDocument/semanticTokens/range
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:36.409][Start]codeLens/resolve
[LanguageServerHost][10:15:36.411][End]codeLens/resolve
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:39.117][Start]textDocument/inlayHint
[LanguageServerHost][10:15:39.117][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:39.185][Start]textDocument/inlayHint
[LanguageServerHost][10:15:39.185][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:39.310][Start]textDocument/semanticTokens/range
[LanguageServerHost][10:15:39.316][End]textDocument/semanticTokens/range
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:39.632][Start]textDocument/inlayHint
[LanguageServerHost][10:15:39.633][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:40.132][Start]textDocument/inlayHint
[LanguageServerHost][10:15:40.133][End]textDocument/inlayHint
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:40.243][Start]textDocument/semanticTokens/range
[LanguageServerHost][10:15:40.245][End]textDocument/semanticTokens/range
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:40.472][Start]codeLens/resolve
[LanguageServerHost][10:15:40.474][End]codeLens/resolve
[LanguageServerHost]c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs found in workspace Host
[LanguageServerHost][10:15:41.201][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\git\private-repos\Skeleton-Project\Skeleton\src\Skeleton.Api\Configurations\AuthenticationConfiguration.cs in Skeleton.Api
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:41.201][End]textDocument/diagnostic
[LanguageServerHost]c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs found in workspace MiscellaneousFiles
[LanguageServerHost][10:15:41.403][Start]textDocument/diagnostic
[LanguageServerHost]PublicDocumentPullDiagnosticsHandler(category: ) started getting diagnostics
[LanguageServerHost]previousResults.Length=1
[LanguageServerHost]Processing 1 documents
[LanguageServerHost]Diagnostics were unchanged for DocumentDiagnosticSource: c:\Users\aleksandar\AppData\Local\Temp\MetadataAsSource\7aef6cfc0a4845e59c0825f3ed0b3993\DecompilationMetadataAsSourceFileProvider\48d72809366e4a7a965378797900516e\OAuthExtensions.cs in Miscellaneous Files
[LanguageServerHost]Microsoft.CodeAnalysis.LanguageServer.Handler.Diagnostics.Public.PublicDocumentPullDiagnosticsHandler finished getting diagnostics
[LanguageServerHost][10:15:41.403][End]textDocument/diagnostic

If you came here from VS Code, the log file location should be copied to the clipboard.

## Other Info:
Give me info or a workaround,  how to see decompiled code and go through it to see implementations etc. 

**Reproduction Steps**

**Expected behavior**
 To see decompiled code in VSCode.

**Exceptions & Errors (if any)**
I can't see decompiled code in VSCode for example an OAuth implementation.

**Further technical details**
- VSCode Version: 1.81.1

- The version of the extension that's on your machine
 C# extension version: v2.0.413
 C# Dev Kit extension version:  v0.3.21
- Your operating system details
Edition	Windows 11 Pro
Version	22H2
Installed on	‎28-‎Oct-‎22
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

**Comment by dibarbet** [comment] 2023-08-28 21:09
This will be resolved in this weeks release (Wednesday).

Duplicate of https://github.com/dotnet/vscode-csharp/issues/5969

**Closed by dibarbet** 2023-08-28 21:09 UTC
