### ISSUE TITLE
'Extract Method' right click action takes precedence over breakpoint's context menu

### ISSUE THREAD

**Issue by ClaireKang** [dotnet/vscode-csharp#1615] opened 2017-07-03 07:32 UTC
## Environment data
dotnet --info output:
Runtime Environment:
OS Name: Ubuntu16.10
SDK: 1.0.4
VS Code version: 1.13.1
C# Extension version: v1.12.0-beta1

## Steps to reproduce
1. Create a new project in Command with 'dotnet new console' ->'dotnet restore'.
2. Open project with VSCode.
3. Move cursor to line 9
4. Hit F9 to set a breakpoint
5. Right-Click the breakpoint to edit it.
   
## Expected  behavior
![image](https://user-images.githubusercontent.com/20184768/27782206-1946ae36-6004-11e7-9dab-dc77949d14f1.png)
   
## Actual behavior
![image](https://user-images.githubusercontent.com/20184768/27782218-27d907a0-6004-11e7-8264-83f9bd3319f5.png)

## Work around
Move the cursor to another line

**Comment by DustinCampbell** [comment] 2017-07-04 22:56
There's two issues here:

1. Extract Method shouldn't be offered when there isn't a selection in the editor. I'm tracking this with https://github.com/OmniSharp/omnisharp-vscode/issues/1605 and already have a fix in hand for it.
2. VS Code shouldn't hide the light bulb with breakpoints and then offer the light bulb menu instead of the breakpoint menu. That's an issue that will need to be fixed within VS Code. The nearest issue I could find is https://github.com/Microsoft/vscode/issues/25174. @jrieken, does this look like the same problem to you?

**Comment by jrieken** [comment] 2017-07-10 08:54
hm, @isidor might know...

**Comment by isidorn** [comment] 2017-07-17 13:30
Yeah https://github.com/Microsoft/vscode/issues/25174 covers the issue 2. quite well

**Comment by JoeRobich** [comment] 2024-11-08 23:05
Cannot reproduce with current release.

**Closed by JoeRobich** 2024-11-08 23:05 UTC
Labels: OmniSharp
