### ISSUE TITLE
When entering in the Documentation Comment area, pressing the Enter key will result in incorrect results

### ISSUE THREAD

**Issue by Seng-Jik** [dotnet/vscode-csharp#6123] opened 2023-08-12 05:38 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.412 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: 1.81.1
C# Extension version: v2.0.357 
C# DevKit version: v0.3.21
IntelliCode for C# Dev Kit: v0.1.26
Unity extension: v0.9.0
Unity: 2022.3.6f1

## Steps to reproduce
![20230812133626_rec_](https://github.com/dotnet/vscode-csharp/assets/11296891/45923aab-cb0e-46a5-8db9-178f3da09098)

**Comment by dibarbet** [comment] 2023-08-14 17:37
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6123

**Closed by dibarbet** 2023-08-14 17:37 UTC
Labels: Completion

**Comment by jaredpar** [comment] 2023-08-14 17:47
@dibarbet pretty sure you meant another issue cause you just self referenced this one.

**Comment by dibarbet** [comment] 2023-08-14 17:52
Yes sorry - https://github.com/dotnet/vscode-csharp/issues/6039
