### ISSUE TITLE
v2.1.2 can't find .NET in Dev Container

### ISSUE THREAD

**Issue by sliekens** [dotnet/vscode-csharp#6404] opened 2023-09-20 08:23 UTC
Type: <b>Bug</b>

## Issue Description ##
The C# extention as of v2.1.2 fails to find or acquire .NET when running inside a Dev Container.

## Steps to Reproduce ##

Create a Dev Container using the base image `mcr.microsoft.com/devcontainers/dotnet:6.0-bullseye`

I also have a global.json in my repository to pin the SDK version.
``` json
{
  "sdk": {
    "version": "6.0.100",
    "rollForward": "latestFeature"
  }
}
```

## Expected Behavior ##

C# extension acquires .NET 7 and starts.

## Actual Behavior ##

C# extension doesn't start. It worked fine with versions <2.1.2.

### C# log ###
<details>

```
Failed to find dotnet info from path, falling back to acquire runtime via ms-dotnettools.vscode-dotnet-runtime
No compatible .NET runtime found. Minimum required version is 7.0.
Dotnet path: /home/vscode/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/dotnet
Activating C# standalone...
Starting server at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll
Server arguments /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.LanguageServer.dll --logLevel Trace --telemetryLevel off --extensionLogDirectory /home/vscode/.vscode-server/data/logs/20230920T100319/exthost3/ms-dotnettools.csharp
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.AnalyzerUtilities.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Elfie.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Razor.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Remote.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Features.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Workspaces.MSBuild.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.Workspaces.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.CSharp.dll added to workspace.
dbug: LanguageServerWorkspaceFactory[0]
      Solution-level analyzer at /home/vscode/.vscode-server/extensions/ms-dotnettools.csharp-2.1.2-linux-x64/.roslyn/Microsoft.CodeAnalysis.Scripting.dll added to workspace.
[Info  - 10:13:14 AM] [Program]Language server initialized
[LanguageServerHost][08:13:14.706][Start]initialize
[LanguageServerHost][08:13:14.709][Start]Initialize
[LanguageServerHost][08:13:14.791][End]Initialize
[LanguageServerHost][08:13:14.846][End]initialize
[LanguageServerHost][08:13:14.854][Start]initialized
[LanguageServerHost][08:13:14.969][End]initialized
[LanguageServerHost][08:13:14.971][Start]solution/open
A compatible .NET SDK was not found.

Requested SDK version: 6.0.100
global.json file: /workspace/global.json

Installed SDKs:
No .NET SDKs were found.

Install the [6.0.100] .NET SDK or update [/workspace/global.json] to match an installed SDK.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[Error - 10:13:15 AM] [LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 97
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
[LanguageServerHost][08:13:15.006][Start]workspace/diagnostic
[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics
[LanguageServerHost][08:13:15.015][End]solution/open
[LanguageServerHost]previousResults.Length=0
[LanguageServerHost]Processing 0 documents
```

</details>

### C# LSP Trace Logs ###
<details>

```
Extension vscode.configuration-editing does not contribute csharpExtensionLoadPaths
Extension vscode.css-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.debug-auto-launch does not contribute csharpExtensionLoadPaths
Extension vscode.debug-server-ready does not contribute csharpExtensionLoadPaths
Extension vscode.emmet does not contribute csharpExtensionLoadPaths
Extension vscode.extension-editing does not contribute csharpExtensionLoadPaths
Extension vscode.git does not contribute csharpExtensionLoadPaths
Extension vscode.git-base does not contribute csharpExtensionLoadPaths
Extension vscode.github does not contribute csharpExtensionLoadPaths
Extension vscode.grunt does not contribute csharpExtensionLoadPaths
Extension vscode.gulp does not contribute csharpExtensionLoadPaths
Extension vscode.html-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.ipynb does not contribute csharpExtensionLoadPaths
Extension vscode.jake does not contribute csharpExtensionLoadPaths
Extension vscode.json-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.markdown-math does not contribute csharpExtensionLoadPaths
Extension vscode.merge-conflict does not contribute csharpExtensionLoadPaths
Extension ms-vscode.js-debug does not contribute csharpExtensionLoadPaths
Extension ms-vscode.vscode-js-profile-table does not contribute csharpExtensionLoadPaths
Extension vscode.npm does not contribute csharpExtensionLoadPaths
Extension vscode.php-language-features does not contribute csharpExtensionLoadPaths
Extension vscode.references-view does not contribute csharpExtensionLoadPaths
Extension vscode.search-result does not contribute csharpExtensionLoadPaths
Extension vscode.tunnel-forwarding does not contribute csharpExtensionLoadPaths
Extension vscode.typescript-language-features does not contribute csharpExtensionLoadPaths
Extension dbaeumer.vscode-eslint does not contribute csharpExtensionLoadPaths
Extension EditorConfig.EditorConfig does not contribute csharpExtensionLoadPaths
Extension esbenp.prettier-vscode does not contribute csharpExtensionLoadPaths
Extension ms-azure-devops.azure-pipelines does not contribute csharpExtensionLoadPaths
Extension ms-azuretools.vscode-docker does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.csharp does not contribute csharpExtensionLoadPaths
Extension ms-dotnettools.vscode-dotnet-runtime does not contribute csharpExtensionLoadPaths
Extension ms-mssql.data-workspace-vscode does not contribute csharpExtensionLoadPaths
Extension ms-mssql.mssql does not contribute csharpExtensionLoadPaths
Extension ms-mssql.sql-bindings-vscode does not contribute csharpExtensionLoadPaths
Extension ms-mssql.sql-database-projects-vscode does not contribute csharpExtensionLoadPaths
Extension ms-vscode.azure-account does not contribute csharpExtensionLoadPaths
[Trace - 10:13:14 AM] Sending notification 'initialized'.
Params: {}


[Trace - 10:13:14 AM] Sending notification 'solution/open'.
Params: {
    "solution": "file:///workspace/redacted.sln"
}


[Trace - 10:13:14 AM] Sending request 'workspace/diagnostic - (1)'.
Params: {
    "previousResultIds": [],
    "partialResultToken": "499ce16f-f013-467a-8a5c-b208a6cd267f"
}


[Trace - 10:13:14 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:14.846][End]initialize"
}


[Trace - 10:13:14 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:14.854][Start]initialized"
}


[Trace - 10:13:14 AM] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "2fc0c71f-bce9-4df0-b874-a8ed5f818649",
            "method": "workspace/didChangeConfiguration"
        }
    ]
}


[Trace - 10:13:14 AM] Sending response 'client/registerCapability - (2)'. Processing request took 0ms
No result returned.


[Trace - 10:13:14 AM] Received request 'workspace/configuration - (3)'.
Params: {
    "items": [
        {
            "section": "csharp|symbol_search.dotnet_search_reference_assemblies"
        },
        {
            "section": "visual_basic|symbol_search.dotnet_search_reference_assemblies"
        },
        {
            "section": "csharp|implement_type.dotnet_insertion_behavior"
        },
        {
            "section": "visual_basic|implement_type.dotnet_insertion_behavior"
        },
        {
            "section": "csharp|implement_type.dotnet_property_generation_behavior"
        },
        {
            "section": "visual_basic|implement_type.dotnet_property_generation_behavior"
        },
        {
            "section": "csharp|completion.dotnet_show_name_completion_suggestions"
        },
        {
            "section": "visual_basic|completion.dotnet_show_name_completion_suggestions"
        },
        {
            "section": "csharp|completion.dotnet_provide_regex_completions"
        },
        {
            "section": "visual_basic|completion.dotnet_provide_regex_completions"
        },
        {
            "section": "csharp|completion.dotnet_show_completion_items_from_unimported_namespaces"
        },
        {
            "section": "visual_basic|completion.dotnet_show_completion_items_from_unimported_namespaces"
        },
        {
            "section": "csharp|quick_info.dotnet_show_remarks_in_quick_info"
        },
        {
            "section": "visual_basic|quick_info.dotnet_show_remarks_in_quick_info"
        },
        {
            "section": "navigation.dotnet_navigate_to_decompiled_sources"
        },
        {
            "section": "csharp|highlighting.dotnet_highlight_related_json_components"
        },
        {
            "section": "visual_basic|highlighting.dotnet_highlight_related_json_components"
        },
        {
            "section": "csharp|highlighting.dotnet_highlight_related_regex_components"
        },
        {
            "section": "visual_basic|highlighting.dotnet_highlight_related_regex_components"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_literal_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_literal_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_indexer_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_indexer_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_object_creation_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_object_creation_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_enable_inlay_hints_for_other_parameters"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_enable_inlay_hints_for_other_parameters"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_differ_only_by_suffix"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_method_intent"
        },
        {
            "section": "csharp|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name"
        },
        {
            "section": "visual_basic|inlay_hints.dotnet_suppress_inlay_hints_for_parameters_that_match_argument_name"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_implicit_variable_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_implicit_variable_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_lambda_parameter_types"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_lambda_parameter_types"
        },
        {
            "section": "csharp|inlay_hints.csharp_enable_inlay_hints_for_implicit_object_creation"
        },
        {
            "section": "visual_basic|inlay_hints.csharp_enable_inlay_hints_for_implicit_object_creation"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.tab_width"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.tab_width"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.indent_size"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.indent_size"
        },
        {
            "section": "csharp|code_style.formatting.indentation_and_spacing.indent_style"
        },
        {
            "section": "visual_basic|code_style.formatting.indentation_and_spacing.indent_style"
        },
        {
            "section": "csharp|code_style.formatting.new_line.end_of_line"
        },
        {
            "section": "visual_basic|code_style.formatting.new_line.end_of_line"
        },
        {
            "section": "code_style.formatting.new_line.insert_final_newline"
        },
        {
            "section": "csharp|background_analysis.dotnet_analyzer_diagnostics_scope"
        },
        {
            "section": "visual_basic|background_analysis.dotnet_analyzer_diagnostics_scope"
        },
        {
            "section": "csharp|background_analysis.dotnet_compiler_diagnostics_scope"
        },
        {
            "section": "visual_basic|background_analysis.dotnet_compiler_diagnostics_scope"
        },
        {
            "section": "csharp|code_lens.dotnet_enable_references_code_lens"
        },
        {
            "section": "visual_basic|code_lens.dotnet_enable_references_code_lens"
        },
        {
            "section": "csharp|code_lens.dotnet_enable_tests_code_lens"
        },
        {
            "section": "visual_basic|code_lens.dotnet_enable_tests_code_lens"
        },
        {
            "section": "projects.dotnet_binary_log_path"
        }
    ]
}


[Trace - 10:13:14 AM] Sending response 'workspace/configuration - (3)'. Processing request took 2ms
Result: [
    true,
    null,
    "withOtherMembersOfTheSameKind",
    null,
    "preferThrowingProperties",
    null,
    "true",
    null,
    "true",
    null,
    true,
    null,
    "true",
    null,
    "true",
    "true",
    null,
    "true",
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    false,
    null,
    "4",
    null,
    "4",
    null,
    "space",
    null,
    "auto",
    null,
    true,
    "openFiles",
    null,
    "openFiles",
    null,
    true,
    null,
    true,
    null,
    null
]


[Trace - 10:13:14 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:14.969][End]initialized"
}


[Trace - 10:13:14 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:14.971][Start]solution/open"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 1,
    "message": "[LanguageServerHost]System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()\n   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()\n   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()\n   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()\n   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\n   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 159\n   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 97\n   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:15.006][Start]workspace/diagnostic"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]PublicWorkspacePullDiagnosticsHandler(category: , source: ) started getting diagnostics"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost][08:13:15.015][End]solution/open"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]previousResults.Length=0"
}


[Trace - 10:13:15 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[LanguageServerHost]Processing 0 documents"
}
```

</details>

## Environment information ##

**VSCode version**: 1.82.0
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.11 [/home/vscode/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.11/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.5|ms-vscode.azure-account-0.11.5|
|azure-pipelines|ms-azure-devops|1.208.0|ms-azure-devops.azure-pipelines-1.208.0|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-linux-x64|
|data-workspace-vscode|ms-mssql|0.5.0|ms-mssql.data-workspace-vscode-0.5.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|mssql|ms-mssql|1.20.1|ms-mssql.mssql-1.20.1|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|sql-bindings-vscode|ms-mssql|0.4.0|ms-mssql.sql-bindings-vscode-0.4.0|
|sql-database-projects-vscode|ms-mssql|1.2.0|ms-mssql.sql-database-projects-vscode-1.2.0|
|vscode-docker|ms-azuretools|1.26.1|ms-azuretools.vscode-docker-1.26.1|
|vscode-dotnet-runtime|ms-dotnettools|1.7.3|ms-dotnettools.vscode-dotnet-runtime-1.7.3|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|;

</details>

Extension version: 2.2.10
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Redacted|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|Memory (System)|15.54GB (10.16GB free)|
|VM|0%|
</details>

**Comment by dibarbet** [comment] 2023-09-20 22:12
Dupe of https://github.com/dotnet/vscode-csharp/issues/6335

We're hoping to get a release with this fix out this week.

**Closed by dibarbet** 2023-09-20 22:12 UTC
