### ISSUE TITLE
Project system ran into an unexcepted error

### ISSUE THREAD

**Issue by Sella-GH** [dotnet/vscode-csharp#7203] opened 2024-06-06 09:09 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.011fccd5
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: arm64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

VS Code version: 1.90.0
C# Extension version: 2.31.19

## OmniSharp log
```
=====================
6/6/2024 11:04:58 AM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.NominateForRestoreAsync(ProjectRestoreInfo restoreInfo, IReadOnlyCollection`1 versions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.RestoreCoreAsync(PackageRestoreUnconfiguredInput value)
===================
6/6/2024 11:04:58 AM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.NominateForRestoreAsync(ProjectRestoreInfo restoreInfo, IReadOnlyCollection`1 versions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.RestoreCoreAsync(PackageRestoreUnconfiguredInput value)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.RestoreAsync(IProjectVersionedValue`1 e)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformManyBlockSlimAsync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
===================
```

## Steps to reproduce

1. Start VSCode with the C# extension
2. Load a .NET 8 project
3. See error

## Expected  behavior
No error to be seen and everything works smoothly.

## Actual behavior
In the lower right corner an info notification popped up, saying I should report this to the developers.

## Additional context
I have no idea why this happened but everything works (as far as I can see). I only get the notification when I load C# projects that an error happened and the attached exceptions are throwing.

**Comment by dibarbet** [comment] 2024-06-10 21:07
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/567

**Closed by dibarbet** 2024-06-10 21:07 UTC
