### ISSUE TITLE
Prevent Omnisharp Log opening on startup

### ISSUE THREAD

**Issue by MrChriZ** [dotnet/vscode-csharp#2556] opened 2018-09-26 16:07 UTC
## Environment data
`dotnet --info` output:
VS Code version:1.27.2
C# Extension version:1.16.1

Is it possible to prevent Omnisharps log opening up modally when I open visual code?
When opening a nodejs project the last thing I want having just told my node server to start is Omnisharp popping up with it's log.

**Comment by Mitiko** [comment] 2018-09-26 20:00
I was also searching for a way to make it not pop up at startup in the settings of the editor, but found no way. This is quite annoying.

**Comment by rchande** [comment] 2018-09-27 16:09
@MrChriZ The real question is why the C# extension is getting activated in your node project. Do you have C# projects in the same file tree?

**Comment by MrChriZ** [comment] 2018-09-28 06:40
@rchande Interesting...I'm new to Omnisharp. No I don't believe I do.
The project is an EmberJS project to be precise.  Omnisharp doesn't appear to be triggered by other Ember proejcts on my system... however I can't see any thing that looks like a C# file in my project.

Omnisharp outputs the following
        No solution files found in '/home/chris/EmberJS/decorator'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/home/chris/EmberJS/decorator'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files

**Comment by MrChriZ** [comment] 2018-09-28 09:38
My guess is this is because my project uses node-sass which in turn uses node-gyp which in turn has a .cs file in it's lib folder.

**Comment by MrChriZ** [comment] 2018-09-28 09:56
At present I can confirm the project uses node-sass which in turn uses node-gyp
which does have some .cs and a .sln file.
I'm yet to reproduce the issue in a clean project.

**Comment by MrChriZ** [comment] 2018-09-28 10:57
OK I can reproduce the issue.
In Ember projects when building a tmp folder is created in the root of the folder.
Sometimes things from node_modules gets left behind in this tmp folder.
In this particular case it's the .cs and .sln files from node-gyp/node-sass.
This is in turn tricks omnisharp into believing the project is a cs project.
I believe tmp needs to be added to the list of folder exclusions - here by the look of it 
https://github.com/OmniSharp/omnisharp-vscode/blob/9f37c43458eb84ff8c319722fc78dc31d614395e/src/omnisharp/launcher.ts

**Comment by Mitiko** [comment] 2018-09-28 12:50
Is it possible to start omnisharp, without showing the log?

**Comment by chrisming999** [comment] 2018-09-29 03:39
thank you  im new bird

**Comment by NinoFloris** [comment] 2018-09-30 16:35
This seems to happen because of https://github.com/OmniSharp/omnisharp-vscode/pull/2133
It seems the extensions gets a "omnisharp returns an error" event (seems because nothing weird is in the logs and autocomplete works) which gets picked up by https://github.com/OmniSharp/omnisharp-vscode/blob/master/src/observers/OmnisharpChannelObserver.ts#L16 which then opens the output panel.

@akshita31 any ideas?

**Comment by rchande** [comment] 2018-10-01 15:51
@MrChriZ In that case, you can add a settings file for VS Code to ignore this directory: https://stackoverflow.com/questions/33258543/how-can-i-exclude-a-directory-from-visual-studio-code-explore-tab. That should prevent the C# extension from being activated.

@NinoFloris You're probably correct. We fixed that problem in https://github.com/OmniSharp/omnisharp-vscode/pull/2540 -- fix is available in our latest beta.

**Comment by MrChriZ** [comment] 2018-10-01 17:12
Hmm I'm not sure I'd want to exclude the tmp folder from VS Code in it's entirety.  
I find myself looking in that folder surprisingly frequently when things go wrong...

**Comment by akshita31** [comment] 2018-10-08 23:40
@MrChriZ The 1.16.2 version of the C# extension is out which contains the fix for this. Can you try updating and checking if the error still reproduces?

**Comment by MrChriZ** [comment] 2018-10-10 08:52
@akshita31 - That seems to have fixed it - thanks very much!

**Comment by MrChriZ** [comment] 2018-10-10 08:57
At least it seems to have solved the modal error issue.  The Omnisharp server still starts on a project it shouldn't be starting on - which I guess still needs the fix I mentioned in my earlier comment.

**Comment by rchande** [comment] 2018-10-12 17:00
@MrChriZ One can easily imagine using a directory called `tmp` so we're unlikely to blanket exclude it. [You mentioned ](https://github.com/OmniSharp/omnisharp-vscode/issues/2556#issuecomment-425386128) a specific location where .cs/.sln files appear under your node_modules. I recommend that you exclude that directory as I described earlier.

**Comment by rchande** [comment] 2018-10-12 17:06
@MrChriZ You can also add an `omnisharp.json` as described [here](https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#file-options) to exclude those directories from OmniSharp.

**Comment by MrChriZ** [comment] 2018-10-15 11:32
@rchande  - Excluding the specific Node Modules folder would not work - as it's already excluded by the node_modules folder exclusion - but then picked up again in the tmp folder.  When it's copied into tmp folder by Ember it's copied their with a random generated folder name  - so with regard to your original suggestion there's no way to exclude specifically that folder other than excluding the whole tmp folder - which as I pointed out is undesirable.

I can't really imagine a scenario in which a tmp subfolder folder could be created and used to define that a project is a CS sharp project - that would seem to me a very strange way of looking at projects. In the same way a node_modules subfolder is highly unlikely to be  define that a project is a CS project.  A CS project of course can still have a node_modules sub folder - even though it's in that exclusion list I've suggested - as it would have CS project files in it's root which would still trigger the check.
It would also still work if tmp was the root folder - since it wouldn't match the glob **/tmp. (I've just tested this by creating a folder called node_modules and creating cs project files in it - Omisharps server starts up).

I will take a look at the omnisharp.json solution but to me adding tmp subfolder exclusion is a better solution.

**Comment by jjavierdguezas** [comment] 2018-11-22 09:20
Please prevent also opening OUTPUT tab when OmniSharp is getting the latest version ( I need `"omnisharp.path": "latest"` to be setted)
When I start vscode, I usually start typing in the terminal and it is very annoying that another tab is showed in the middle of what I'm writing.
![vscode](https://user-images.githubusercontent.com/13673443/48893078-c2011000-ee3f-11e8-9787-4c0e538dc790.gif)

**Comment by rchande** [comment] 2018-11-26 17:22
@MrChriZ My general opinion is that, instead of trying to build specific exclusions into the C# extension, we should make it easy for users to exclude parts of their repositories. If you're having trouble getting the omnisharp configuration to exclude your directory, I'd like to understand why so that we can make this (general) mechanism work for you, and for everyone else. Thanks for your help!

**Comment by JoeRobich** [comment] 2024-11-11 22:47
A lot has changed with project loading since this issue was opened. If you are still running into problems, please open a new issue.

**Closed by JoeRobich** 2024-11-11 22:47 UTC
Labels: OmniSharp
