### ISSUE TITLE
Cannot go-to-def if one of the definitions is in source-generated code

### ISSUE THREAD

**Issue by agocke** [dotnet/vscode-csharp#6614] opened 2023-10-31 18:46 UTC
Type: <b>Bug</b>

## Issue Description ##

When I hit Go-To-Def and my source generator writes a partial definition into another file, I get `Request textDocument/definition failed` and the exception below.

## Steps to Reproduce ##

No simple reproduction. I can probably make one up if necessary.

        
### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
```
Using dotnet configured on PATH
Dotnet path: /home/andy/.local/share/dnvm/dn/dotnet
Activating C# standalone...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/500db898-4ab4-4c35-963e-65f1d43f0fb2.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 11:38:48 AM] [Program] Language server initialized
[Info  - 11:38:49 AM] [LanguageServerProjectSystem] Loading /home/andy/code/dnvm/dnvm.sln...
[Info  - 11:38:51 AM] [LanguageServerProjectSystem] Successfully completed load of /home/andy/code/dnvm/test/IntegrationTests/IntegrationTests.csproj
[Info  - 11:38:51 AM] [LanguageServerProjectSystem] Successfully completed load of /home/andy/code/dnvm/test/UnitTests/UnitTests.csproj
[Info  - 11:38:51 AM] [LanguageServerProjectSystem] Successfully completed load of /home/andy/code/dnvm/test/Shared/Dnvm.Test.Shared.csproj
[Info  - 11:38:51 AM] [LanguageServerProjectSystem] Successfully completed load of /home/andy/code/dnvm/src/dnvm/dnvm.csproj
[Info  - 11:38:51 AM] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:01.9711307
[Error - 11:38:59 AM] [LanguageServerHost] System.UriFormatException: Failed create URI from 'SerdeGenerator/Serde.SerdeImplRoslynGenerator/Dnvm.InstalledSdk.IDeserialize.cs'; original string: 'SerdeGenerator/Serde.SerdeImplRoslynGenerator/Dnvm.InstalledSdk.IDeserialize.cs'
 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.CreateAbsoluteUri(String absolutePath) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 186
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.CreateAbsoluteUri(String absolutePath) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 186
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.<TextSpanToLocationAsync>g__ConvertTextSpanToLocation|30_0(Document document, TextSpan span, Boolean isStale, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 477
   at Microsoft.CodeAnalysis.LanguageServer.ProtocolConversions.TextSpanToLocationAsync(Document document, TextSpan textSpan, Boolean isStale, Nullable`1 context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Extensions/ProtocolConversions.cs:line 442
   at Microsoft.CodeAnalysis.LanguageServer.Handler.AbstractGoToDefinitionHandler.GetDefinitionAsync(TextDocumentPositionParams request, Boolean typeOnly, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/Definitions/AbstractGoToDefinitionHandler.cs:line 61
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 176
[Error - 11:38:59 AM] Request textDocument/definition failed.
  Message: Failed create URI from 'SerdeGenerator/Serde.SerdeImplRoslynGenerator/Dnvm.InstalledSdk.IDeserialize.cs'; original string: 'SerdeGenerator/Serde.SerdeImplRoslynGenerator/Dnvm.InstalledSdk.IDeserialize.cs'
  Code: -32000 
[object Object]
Using dotnet configured on PATH
```

## Environment information ##

**VSCode version**: 1.83.1
**C# Extension**: 2.8.23
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   8.0.100-rc.2.23502.2
 Commit:    0abacfc2b6

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/andy/.local/share/dnvm/dn/sdk/8.0.100-rc.2.23502.2/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-rc.2.23479.6
  Architecture: x64
  Commit:       0b25e38ad3

.NET SDKs installed:
  6.0.410 [/home/andy/.local/share/dnvm/dn/sdk]
  6.0.411 [/home/andy/.local/share/dnvm/dn/sdk]
  6.0.412 [/home/andy/.local/share/dnvm/dn/sdk]
  6.0.413 [/home/andy/.local/share/dnvm/dn/sdk]
  6.0.415 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.102 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.200 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.201 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.202 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.203 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.302 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.305 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.306 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.400 [/home/andy/.local/share/dnvm/dn/sdk]
  7.0.402 [/home/andy/.local/share/dnvm/dn/sdk]
  8.0.100-rc.2.23502.2 [/home/andy/.local/share/dnvm/dn/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.19 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.23 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.12 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.2.23480.2 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.18 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.19 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.23 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.12 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.2.23479.6 [/home/andy/.local/share/dnvm/dn/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/andy/.local/share/dnvm/preview]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-tools|ms-vscode|1.15.31|ms-vscode.cmake-tools-1.15.31|
|copilot|GitHub|1.132.0|github.copilot-1.132.0|
|copilot-chat|GitHub|0.8.0|github.copilot-chat-0.8.0|
|cpptools|ms-vscode|1.17.5|ms-vscode.cpptools-1.17.5-linux-x64|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|csharp|ms-dotnettools|2.8.23|ms-dotnettools.csharp-2.8.23-linux-x64|
|gitlens|eamodio|14.4.1|eamodio.gitlens-14.4.1|
|rust-analyzer|rust-lang|0.3.1713|rust-lang.rust-analyzer-0.3.1713-linux-x64|
|vscode-dotnet-runtime|ms-dotnettools|1.8.1|ms-dotnettools.vscode-dotnet-runtime-1.8.1|
|vscode-lldb|vadimcn|1.10.0|vadimcn.vscode-lldb-1.10.0|
|vscode-pull-request-github|GitHub|0.74.1|github.vscode-pull-request-github-0.74.1|;

</details>

Extension version: 2.8.23
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.90.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (35.30GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/andy/code/dnvm --remote=wsl+Ubuntu-22.04 --crash-reporter-id 36dc5a2c-789a-433d-b30e-152d71db540c|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.15.90.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|Memory (System)|11.68GB (9.37GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30856252
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by dibarbet** [comment] 2023-11-03 00:59
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6426

**Closed by dibarbet** 2023-11-03 00:59 UTC
