### ISSUE TITLE
Support switching target frameworks 

### ISSUE THREAD

**Issue by mykeels** [dotnet/vscode-csharp#7170] opened 2024-05-27 03:09 UTC
## Is your feature request related to a problem? Please describe.

When I'm working on a library with my multiple target frameworks, I have to switch to Visual Studio to be able to switch contexts to a different framework e.g. from net48 to net6.0.

## Describe the solution you would like
A VS Code command to switch target frameworks for a project.

## Applicable Scenarios
A project has multiple target frameworks

**Comment by dibarbet** [comment] 2024-06-18 01:06
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5788

**Closed by dibarbet** 2024-06-18 01:06 UTC
