### ISSUE TITLE
In v2.0.320 syntax highlighting and cmd-click for C# classes broke

### ISSUE THREAD

**Issue by michaelmarziani** [dotnet/vscode-csharp#6016] opened 2023-08-03 12:03 UTC
## Issue Description ##
In the new version of the C# extension (v2.0.320), C# classes are no longer highlighted like they were before, and you can no longer cmd-click on the class name to go to the definition. Immediately reverted to the previous version and it works again.

## Steps to Reproduce ##
Install the new version.

## Expected Behavior ##
C# classes are highlighted an cmd-clickable.

## Actual Behavior ##
C# classes are not highlighted in green as before, and are not cmd-clickable.

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.80.2
**C# Extension**: 1.26.0

<details><summary>Mono Information</summary>
        There is a problem with running OmniSharp on mono: Error: Unable to find Mono. Ensure that Mono's '/bin' folder is added to your environment's PATH variable.</details>
<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.403/

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: arm64
  Commit:       943474ca16

.NET SDKs installed:
  6.0.403 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.11.5|
|copilot|GitHub|1.100.306|
|copilot-chat|GitHub|0.4.1|
|copilot-labs|GitHub|0.14.884|
|csharp|ms-dotnettools|1.26.0|
|npm-intellisense|christian-kohler|1.4.4|
|path-intellisense|christian-kohler|2.8.4|
|prettier-vscode|esbenp|10.1.0|
|python|ms-python|2023.12.0|
|todo-tree|Gruntfuggly|0.0.226|
|vscode-azureappservice|ms-azuretools|0.25.0|
|vscode-azureresourcegroups|ms-azuretools|0.7.5|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-eslint|dbaeumer|2.4.2|
|vscode-pylance|ms-python|2023.8.10|;

</details>

**Comment by KnorpelSenf** [comment] 2023-08-03 15:10
In addition, Find All References only delivers partial results. I assume this is caused by the same underlying problem.

**Comment by mkorsukov** [comment] 2023-08-03 16:42
Thank you for comments! Faces with same issue(s) today after extensions update. Here is my steps to make VS Code and C# experience great again:

- Remove **C# Dev Kit** extension
- Activate switch: Dotnet > Server: **Use Omnishart**
- Restart VS Code

After switch is enabled the Omnisharp will download its dependencies again:
```
Installing C# dependencies...
Platform: linux, x86_64, name=ubuntu, version=20.04

Downloading package 'OmniSharp for Linux (.NET 6 / x64)' (45281 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Linux (.NET 6 / x64)'

Finished

Installing Razor OmniSharp Version = 7.0.0-preview.23363.1...
Platform: linux, x86_64, name=ubuntu, version=20.04

Downloading package 'Razor Language Server for OmniSharp (Linux / x64)' (73248 KB).................... Done!
Installing package 'Razor Language Server for OmniSharp (Linux / x64)'

Finished
```

**Comment by erick2red** [comment] 2023-08-03 19:19
This was happening to me.
I don't have that **C# Dev Kit** extension installed.
I just needed to change the settings and _reload the window_.

**Comment by dibarbet** [comment] 2023-08-03 20:22
From the symptoms, it sounds like the new Roslyn LSP version of the extension isn't loading the project correctly.  If anyone is hitting this, please set the `dotnet.server.trace` setting to `Trace` and attach the C# output logs here.

Note - if you're project is a legacy .net framework csproj (e.g. you had `omnisharp.useModernNet` set to `false`) you will need to revert back to O# (via the `dotnet.server.useOmnisharp` flag) until this issue is resolved - https://github.com/dotnet/vscode-csharp/issues/5721

**Comment by michaelmarziani** [comment] 2023-08-04 14:54
@dibarbet Hi David, I turned on the setting you talked about, and now I see a ton of logs. I'll attach as a text file.
[csharp_lsp_trace_logs.txt](https://github.com/dotnet/vscode-csharp/files/12261928/csharp_lsp_trace_logs.txt)

**Comment by arkalyanms** [comment] 2023-08-11 23:34
The LSP trace logs dont show any issues. The C# logs might have any project load failures if any. Nevertheless, 2.0.357 added support to open projects without a sln file. @michaelmarziani would you confirm if that was the missing feature impacting you?

**Comment by michaelmarziani** [comment] 2023-08-12 12:41
@arkalyanms Thank you for looking into this.

With the newest update v2.0.357, the cmd click is now working. There's still something going on, as when I leave files open and quit VS Code, then reopen, classes are not highlighted as they were:

<img width="678" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/1920084/08b603e9-662b-4967-afb0-a20d51cfb3a1">

That said, cmd+click and hover now work, whereas before they didn't. And then, if I click to a different file and then back to the one that came up when opening VS Code, it's now correctly highlighted:

<img width="697" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/1920084/f273687e-c554-4d5c-b543-2b2d603d4f19">

Thus, I think the main problem is solved, but I wanted to give you the best report I could.

@dibarbet had mentioned that .csproj .NET projects are considered legacy. Is there a resource you could point me to on how to convert my project into something more up to date?

**Comment by dibarbet** [comment] 2023-08-31 01:47
> That said, cmd+click and hover now work, whereas before they didn't. And then, if I click to a different file and then back to the one that came up when opening VS Code, it's now correctly highlighted:

There's a bug on the vscode side where we trigger a refresh for classifications, but the editor doesn't actually update until *something* happens (e.g. scroll, switching active windows, changes, etc).

> @dibarbet had mentioned that .csproj .NET projects are considered legacy. Is there a resource you could point me to on how to convert my project into something more up to date?

Specifically, there are two kinds of csproj - legacy and SDK style.  If you're on .net core you almost certainly have an SDK style project which is supported.  If you're on .net framework, you may have a legacy style csproj (but might not).  See this section for migrating that - https://learn.microsoft.com/en-us/dotnet/architecture/modernize-desktop/example-migration#migrate


Closing this issue since the main problem is solved.  If there are further issues, please open a new one.

**Closed by dibarbet** 2023-08-31 01:47 UTC
Labels: Bug, Needs More Info, Triaged, Needs Fix Confirmation
