### ISSUE TITLE
Cannot find Microsoft.Build.Tasks.v15.0.dll

### ISSUE THREAD

**Issue by HowardHoffman** [dotnet/vscode-csharp#1738] opened 2017-08-25 14:06 UTC
## Environment data
`dotnet --info` output:
```
.NET Command Line Tools (1.0.0-preview2-003131)

Product Information:
 Version:            1.0.0-preview2-003131
 Commit SHA-1 hash:  635cf40e58

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64VS Code version: 1.5.1
```
C# Extension version: 1.12.1

## Steps to reproduce
Open folder that contains a VS 2015 SLN and several CSPROJ files.

## Expected  behavior
No errors.

## Actual behavior
Tool emits warnings and failures to the output window.

``` 
OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The task factory "CodeTaskFactory" could not be loaded from the assembly "C:\Users\<windows-username>\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Microsoft.Build.Tasks.v15.0.dll". Could not load file or assembly 'file:///C:\Users\<windows-username>\.vscode\extensions\ms-vscode.csharp-1.12.1\.omnisharp\msbuild\Microsoft.Build.Tasks.v15.0.dll' or one of its dependencies. The system cannot find the file specified.
```
I templated the error above to remove the actual Windows Username.
Indeed the `ms-vscode.csharp-1.12.1\.omnisharp\msbuild\` folder has no file named `Microsoft.Build.Tasks.v15.0.dll`

NOTE:  I am running Windows and regular .NET.  I do have `Microsoft.Build.Tasks.v12.0.dll` in my `Program Files (x86)\MSBuild\12.0` folder, as well as `C:\Program Files (x86)\Reference Assemblies\Microsoft\MSBuild\v12.0\` and many other places.

**Comment by DustinCampbell** [comment] 2017-08-25 14:40
Hi! Could you provide a bit more information to help us better determine what's going wrong? 

1. Do you have happen to have a project that you could share that reproduces the issue?
2. Could you provide the full OmniSharp Log?
3. Do you have VS 2015, the VS 2015 Build Tools, VS 2017 or the VS 2017 Build Tools installed?

**Comment by DustinCampbell** [comment] 2017-09-05 16:24
Hi, are you still experiencing this issue? If so, could you provide the information I requested above? If you have any questions, let me know.

**Comment by montgomerybc** [comment] 2017-10-17 14:51
I have the same issue here.  Happens (in this case) in a solution with an Azure WebJob project.  Log (omnisharp-log-1738.txt) and Solution (WebJobApp.zip) attached.

[omnisharp-log-1738.txt](https://github.com/OmniSharp/omnisharp-vscode/files/1391405/omnisharp-log-1738.txt)
[WebJobApp.zip](https://github.com/OmniSharp/omnisharp-vscode/files/1391406/WebJobApp.zip)


VS Code Version 1.17.1
Commit 1e9d36539b0ae51ac09b9d4673ebea4e447e5353
Date 2017-10-10T14:24:50.851Z
Shell 1.7.7
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

OmniSharp Version 1.12.1

**Comment by DustinCampbell** [comment] 2017-10-17 18:08
Hi @montgomerybc: Do you have Visual Studio installed as well? If so, which version(s) do have installed?

**Comment by montgomerybc** [comment] 2017-10-17 21:05
Sorry, I meant to include these in my original post:

Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.7.02046

Since the solution I attached was an Azure WebJob project, here are all installed product that have "Azure" in their name:

Azure App Service Tools v2.9.6   14.0.21111.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.2.4500.0
Azure Data Lake Tools for Visual Studio   2.2.4500.0
Common Azure Tools   1.8
Microsoft Azure Hive Query Language Service   2.2.4500.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Stream Analytics Language Service   2.2.4500.0
Microsoft Azure Tools   2.9

**Comment by DustinCampbell** [comment] 2017-10-17 21:09
Out of curiosity, does it work if you launch VS Code from a VS 2015 Developer Command Prompt?

**Comment by montgomerybc** [comment] 2017-10-17 21:19
No difference.  From the VS 2015 Developer Command Prompt I navigated to the directory with the solution and: "code ."  Identical errors

**Comment by HowardHoffman** [comment] 2017-10-18 17:30
@montgomerybc Oddly, when I start VS Code from the VS Dev Command Prompt, then opened the folder containing my SLN I did have a difference.

**Comment by HowardHoffman** [comment] 2017-10-19 15:08
@montgomerybc Weird - now the issue occurs again.  I must not have gotten it right yesterday.  I'm in a VS 2015 Dev Prompt and I open VS Code via:  `"c:\program files\Microsoft VS Code\Code.exe"`.  When I open my project folder in Code, I get the banner  `Warn Some projects have trouble loading.  Please review the output for more details."`  

The output includes this `[fail]`:  `The task factory "CodeTaskFactory" could not be loaded from the assembly`.  It cannot find Microsoft.Build.Tasks.v15.0.dll.  Indeed that file is not on my machine.

**Comment by bojanrajkovic** [comment] 2017-12-28 02:18
I'm having the same issue running VSCode on Ubuntu.

I've narrowed it down to trying to use a `netcoreapp2.0` project that uses a NuGet package that targets `net461`. The package installs, code compiles and runs, but it breaks Omnisharp because it goes looking for `Microsoft.Build.Tasks.v15.0.dll`:

```
[warn]: OmniSharp.MSBuild.Resolution.PackageDependencyResolver
        Volley.Client: Did not find 'libsodium-net' in lock file.
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Package 'Baseclass.Contrib.Nuget.Output 2.1.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
[warn]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        Package 'libsodium-net 0.10.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
[fail]: OmniSharp.MSBuild.ProjectFile.ProjectFileInfo
        The task factory "CodeTaskFactory" could not be loaded from the assembly "/home/brajkovic/.vscode/extensions/ms-vscode.csharp-1.13.1/.omnisharp/omnisharp/msbuild/15.0/Bin/Microsoft.Build.Tasks.v15.0.dll". 
```

If I remove `libsodium-net`, no issues.

**Comment by JoeRobich** [comment] 2024-11-08 23:45
Closing as a lot has changed with packaging and acquisition of necessary components since this issue was opened. Please reopen with fresh details if this is still a problem.

**Closed by JoeRobich** 2024-11-08 23:45 UTC
Labels: OmniSharp
