### ISSUE TITLE
Please add functions to get information about the open solution

### ISSUE THREAD

**Issue by AndreyMoskalev565** [dotnet/vscode-csharp#6084] opened 2023-08-09 13:57 UTC
Add a command to get the path to the open solution, for example:

`dotnet.getOpenSolutionPath`

Also, commands to get the build platform and build configuration would be very useful:

- `dotnet.getBuildConfiguration`;
- `dotnet.getBuildPlatform`.

I am developing PVS-Studio extension for VSCode that will analyze projects. I want to use an open solution in the "C#" plugin as the analysis target. To start the analysis correctly, I need to get the build platform and build configuration. 

Thank you in advance for your help!

**Comment by dibarbet** [comment] 2023-08-10 01:16
We definitely want to allow other extensions to pull data from the new language server, similar to O#.  However we need to re-design the API because the underlying project representation is not the same.  See https://github.com/dotnet/vscode-csharp/issues/5805

> I am developing PVS-Studio extension for VSCode that will analyze projects. I want to use an open solution in the "C#" plugin as the analysis target.

What kind of analysis do you want to do?  Because Roslyn does support 3rd party analyzers that can analyze source code.  These should already work if they're shipped as a nuget package and added to the project.   See https://learn.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2022

**Comment by jasonmalinowski** [comment] 2023-08-14 23:15
Indeed we do need a bit more information here to better understand this request. There are scenarios where we might have loaded many projects, but we have no _solution_ path because the user has none. @AndreyMoskalev565 can you better describe what sort of analysis you're doing?

**Comment by dibarbet** [comment] 2024-03-27 23:19
Likely duplicate of https://github.com/dotnet/roslyn/issues/68696
We plan to add extensibility points on the server side that will allow you to get information about the Roslyn workspace.

**Closed by dibarbet** 2024-03-27 23:19 UTC
Labels: Feature Request, Needs More Info, Needs Investigation
