### ISSUE TITLE
[BUG] Cannot accept override suggestion

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6246] opened 2023-08-28 22:50 UTC
From vscode-dotnettools created by [NamelessPerson](https://github.com/NamelessPerson): microsoft/vscode-dotnettools#434  

### Describe the Issue

When typing "override" in a class, suggestions for methods to override appear but after accepting them, the code does not appear.

### Steps To Reproduce

On windows with unity project with C# Dev Kit enabled.
Inside class that inherits from another class with an overideable method
Type "override"
Get suggestions for overideable methods
Accept suggestion

### Expected Behavior

Accepted suggested fills in code

### Environment Information

- Windows
- C# Dev Kit v0.4.6
- Behavior does not change whether or not Unity or IntelliCode for C# pacakges are installed

**Comment by Sanerins** [comment] 2023-08-31 22:36
I would also want to add that this problem is not necessary linked to the Unity projects. Here is my gif showing that exact problem with Godot project. I have specifically turned off two Godot extensions I use which are not made by microsoft. Also it's worth noting that putting brackets even after typing out function manually deletes the typed letters back to the point when suggestion was made, as shown on the GIF I made: 
![problem](https://github.com/dotnet/vscode-csharp/assets/36373832/6564bad7-7cde-4c31-93c3-a01e4df9216a)

**Comment by arkalyanms** [comment] 2023-08-31 22:45
@Sanerins thanks for reporting! Would it be possible to get a minimal repro project from you?

**Comment by xwlwx** [comment] 2023-09-04 18:02
I am experiencing the same/similar issue. A little more detail from me:

Fresh vscode install with C# and dotnet  runtime install tool extensions only

Fresh Godot project with a Node2D and CanvasItem2D sprite

Script attached to base Node2D Scene

Code complete works in some method call cases (see gif)

Code suggestion works, but code complete doesn't work with creating a method override no matter using tab, click, enter (see gif)

Code repo: https://github.com/xwlwx/CodeCompletionFailureDemo

https://github.com/dotnet/vscode-csharp/assets/10873956/161aee22-840d-455e-87c0-3083f5568fbf

**Comment by Sanerins** [comment] 2023-09-04 20:51
@arkalyanms Sorry for a long wait, here is the exact project I showed in my gif https://github.com/Sanerins/vscode-bug-showcase
The particular file in question is https://github.com/Sanerins/vscode-bug-showcase/blob/master/scripts/levels/main_menu.cs
Though I do believe xwlwx has a pretty similar situation and our projects will be more or less exact same

**Comment by arkalyanms** [comment] 2023-09-05 00:40
Thank you @Sanerins for the repo. Unfortunately I do not have a repro with either just the C#(v2.0.436) or C# + C# Dev Kit. @genlu in case he can deduce something from the latest comments here. 

![overridecompletion](https://github.com/dotnet/vscode-csharp/assets/60013978/2e806216-ee73-4c37-a5fa-552d41dc4f6b)

**Comment by Sanerins** [comment] 2023-09-05 18:32
@arkalyanms thank you for a video, I reread my previous problem once again and noticed that I said that target file is main_menu.cs, but actually in my gif it was not main_menu.cs, but in fact base_paddle.cs (https://github.com/Sanerins/vscode-bug-showcase/blob/master/scripts/objects/paddles/base_paddle.cs).
I tried to replicate the bug I encountered in main_menu.cs and in fact everything worked normally just like on the gif you provided!
But auto completion in base_paddle.cs file still seems to behave wrongly, just as I've shown in my gif! Most peculiar situation indeed!
@arkalyanms if you are able, can you please check base_paddle.cs file and confirm whether you can recreate bug in it or not?

**Comment by arkalyanms** [comment] 2023-09-05 19:06
Sure, I hit success on the other files as well though.

![oc](https://github.com/dotnet/vscode-csharp/assets/60013978/837e860b-b9e7-40b0-a5d1-bd99521d2add)

![oc2](https://github.com/dotnet/vscode-csharp/assets/60013978/5d891940-3c72-4c6e-b775-976acbec89ea)

**Comment by Sanerins** [comment] 2023-09-05 20:01
@arkalyanms Thanks for a swift answer!

I want to dig to the bottom of it, so I thought for a bit what might be causing all of this like a Sherlok and come to the conclusion that all of the complaints from all of the three people have one thing in common - files were created not in vscode itself, but rather via different program (Godot in @xwlwx and my case, Unity in [NamelessPerson](https://github.com/microsoft/vscode-dotnettools/issues/434) case).

So I started to try to proof or deny my theory, and so far it seems like it might actually be the case. If I create new file, e.g `new_paddle.cs` via VS code - auto correction works just fine. But if I try to create new file using external tool, e.g godot, everything seems to behave just like in the first gif shown by me.

There are also additional abnormality, that even if I delete the cs file created by external program and then create new file with vscode, it still won't work normally

Here is a showcase of this very experience. Now I'm not sure whether it's a c# extention bug, since it's caused by third-party software, but on the other hand I'm not sure why creation of a file with Godot or Unity would result in such behaviour, considering that other ides e.g Rider seem not to have similar problems handling files created that way.

https://github.com/dotnet/vscode-csharp/assets/36373832/ffb1bc11-bc03-4bcc-8d5a-9868cdb7b565

**Comment by genlu** [comment] 2023-09-09 00:17
Might be fixed by https://github.com/dotnet/vscode-csharp/pull/6315
If not, we'd have more info to investigated with additional logging from https://github.com/dotnet/vscode-csharp/pull/6325

**Closed by genlu** 2023-09-09 00:17 UTC
Labels: Bug, Completion
