### ISSUE TITLE
XML documentation (doc comment) creation is no longer working

### ISSUE THREAD

**Issue by simonmattes** [dotnet/vscode-csharp#7217] opened 2024-06-10 10:51 UTC
## Environment data

```
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Users\simonmattes\AppData\Local\dotnet\sdk\8.0.204\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Users\simonmattes\AppData\Local\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\Users\simonmattes\AppData\Local\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Users\simonmattes\AppData\Local\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Users\simonmattes\AppData\Local\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

- VS Code version: `1.89.0 (user setup)`
- C# Extension version: `v2.31.19`

## Steps to reproduce

1. Open/ create a .NET project
2. Navigate to a class without an XML documentation comment
3. Insert a new line before the `class` declaration
4. Move to that empty line
5. Type `///` 

## Expected  behavior

- The C# extension inserts:  
  ```
  /// <summary>
  /// 
  /// </summary>
  ```

## Actual behavior

Nothing happens

## Additional context

I believe this worked just recently; might be an issue with the most-recent .NET update or an update of the extension.

**Comment by dibarbet** [comment] 2024-06-10 20:56
Duplicate of https://github.com/dotnet/vscode-csharp/issues/7184, will be fixed in the next prerelease.

**Closed by dibarbet** 2024-06-10 20:56 UTC
