### ISSUE TITLE
VsCode Crashes with SDL2-CS

### ISSUE THREAD

**Issue by Shadowblitz16** [dotnet/vscode-csharp#6734] opened 2023-12-11 04:49 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.114
 Commit:    b2a71039cd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.114/

Host:
  Version:      7.0.14
  Architecture: x64
  Commit:       808851b07a

.NET SDKs installed:
  6.0.125 [/usr/lib/dotnet/sdk]
  7.0.114 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: 1.84.2
C# Extension version: v2.13.10

## OmniSharp log
Crashes and idk where the log is.

## Steps to reproduce

1. Open project here. https://github.com/Shadowblitz16/AstroWars
2. Run project
3. Press space

## Expected  behavior
VsCode Shouldn't crash

## Actual behavior
VsCode crashes

## Additional context
I reported this problem here too... https://github.com/microsoft/vscode/issues/200513

**Comment by gregg-miskelly** [comment] 2024-01-08 18:12
Hi @Shadowblitz16, can you define what you mean by "VS Code crashes"? I am not able to reproduce a problem when I try your scenario.

**Comment by Shadowblitz16** [comment] 2024-01-08 18:15
> Hi @Shadowblitz16, can you define what you mean by "VS Code crashes"? I am not able to reproduce a problem when I try your scenario.

Hi gregg vscode seems to crash if I don't sleep the thread.
I think maybe sdl2-cs is running too fast for vscode to handle

**Comment by gregg-miskelly** [comment] 2024-09-10 02:35
I am closing this issue since there was never a response. Feel free to ping back if you have the required information.

**Closed by gregg-miskelly** 2024-09-10 02:35 UTC
Labels: Debugger
