### ISSUE TITLE
New language server not working without a .sln

### ISSUE THREAD

**Issue by barruka** [dotnet/vscode-csharp#6010] opened 2023-08-03 09:21 UTC
Without having a .sln file in my project folder, intellisense is not working.

Why am I forced now to have a .sln file in my project ????

Dotnet path: c:\Users\xxxxx\AppData\Roaming\Code\User\globalStorage\ms-dotnettools.vscode-dotnet-runtime\.dotnet\7.0.9\dotnet.exe
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...
[Info  - 11:16:33 AM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.306
[Info  - 11:16:33 AM] [LanguageServerProjectSystem]Loading d:\Repos\Shop\Shop.Marketplace\Shop.Marketplace.sln...
[Error - 11:16:33 AM] [LanguageServerHost]Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Could not find file 'd:\Repos\Shop\Shop.Marketplace\Shop.Marketplace.sln'.  d:\Repos\Shop\Shop.Marketplace\Shop.Marketplace.sln
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, String resourceName, Object[] args)
   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()
   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionCoreAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 89
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 80
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136

**Comment by AdamRussak** [comment] 2023-08-03 09:34
not sure if its SLN issue.
but I also have not sln and the new version is not working
my env:
vs code workspace on wsl (ubuntu) on win10
![image](https://github.com/dotnet/vscode-csharp/assets/31593022/01a21872-e777-4446-89be-b7ce4677c29f)

**Comment by CWolfs** [comment] 2023-08-03 09:35
Same issue here.

**Comment by NguyenN95** [comment] 2023-08-03 09:45
Really piss me off.

**Comment by barruka** [comment] 2023-08-03 10:49
solved setting "dotnet.server.useOmnisharp": true and restarting vscode

View > Command Palette > Preferences: Open User Settings (JSON)

**Comment by NguyenN95** [comment] 2023-08-03 11:08
it works. Thank you

**Comment by mantissa7** [comment] 2023-08-03 12:05
> solved setting "dotnet.server.useOmnisharp": true and restarting vscode
> 
> View > Command Palette > Preferences: Open User Settings (JSON)

This is a workaround, not a solution. I rolled back to the previous version until there's a fix.


As per the extension documentation:
> If you don’t want to take advantage of the great Language Server features, you can revert back to using OmniSharp by going to the Extension settings and setting dotnet.server.useOmnisharp to true. Next, uninstall or disable C# Dev Kit. Finally, restart VS Code for this to take effect.

**Comment by barruka** [comment] 2023-08-03 13:59
That's it, just a workaround... but it solves the problem at this moment... :)

**Comment by mkorsukov** [comment] 2023-08-03 16:47
This works: https://github.com/dotnet/vscode-csharp/issues/6016#issuecomment-1664305893

**Comment by dibarbet** [comment] 2023-08-03 18:29
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5722

I would recommend enabling the `dotnet.server.useOmnisharp` flag as a workaround until that issue is resolved (downgrading the extension is also valid).

**Closed by dibarbet** 2023-08-03 18:29 UTC
Labels: Bug, Resolved-Duplicate, Triaged

**Comment by joserubenh** [comment] 2023-08-16 15:51
too add insult to injury, the sln file must be named exactly like the folder. 
This makes it unusable for me.
