### ISSUE TITLE
Intellisense does not work

### ISSUE THREAD

**Issue by jozefizso** [dotnet/vscode-csharp#7047] opened 2024-04-13 16:46 UTC
Type: <b>Bug</b>

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.88.1
**C# Extension**: 2.24.17
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.4
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.204/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: arm64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|better-comments|aaron-bond|3.0.2|aaron-bond.better-comments-3.0.2|
|better-cpp-syntax|jeff-hykin|1.17.2|jeff-hykin.better-cpp-syntax-1.17.2|
|binary-plist|dnicolson|0.11.3|dnicolson.binary-plist-0.11.3|
|cmake|twxs|0.0.17|twxs.cmake-0.0.17|
|cmake-format|cheshirekow|0.6.11|cheshirekow.cmake-format-0.6.11|
|cmake-language-support-vscode|josetr|0.0.9|josetr.cmake-language-support-vscode-0.0.9|
|cmake-tools|ms-vscode|1.17.17|ms-vscode.cmake-tools-1.17.17|
|code-spell-checker|streetsidesoftware|3.0.1|streetsidesoftware.code-spell-checker-3.0.1|
|codesnap|adpyke|1.3.4|adpyke.codesnap-1.3.4|
|codespaces|GitHub|1.16.19|github.codespaces-1.16.19|
|composer-php-vscode|DEVSENSE|1.45.15272|devsense.composer-php-vscode-1.45.15272|
|copilot|GitHub|1.180.0|github.copilot-1.180.0|
|copilot-chat|GitHub|0.14.1|github.copilot-chat-0.14.1|
|cpptools-extension-pack|ms-vscode|1.3.0|ms-vscode.cpptools-extension-pack-1.3.0|
|cpptools-themes|ms-vscode|2.0.0|ms-vscode.cpptools-themes-2.0.0|
|csdevkit|ms-dotnettools|1.5.12|ms-dotnettools.csdevkit-1.5.12-darwin-arm64|
|csharp|ms-dotnettools|2.24.17|ms-dotnettools.csharp-2.24.17-darwin-arm64|
|docker-linter|henriiik|0.5.0|henriiik.docker-linter-0.5.0|
|dotenv|mikestead|1.0.1|mikestead.dotenv-1.0.1|
|doxdocgen|cschlosser|1.4.0|cschlosser.doxdocgen-1.4.0|
|Doxygen|bbenoist|1.0.0|bbenoist.doxygen-1.0.0|
|ecdc|mitchdenny|1.8.0|mitchdenny.ecdc-1.8.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|endwise|kaiwood|1.5.1|kaiwood.endwise-1.5.1|
|github-markdown-preview|bierner|0.3.0|bierner.github-markdown-preview-0.3.0|
|github-vscode-theme|GitHub|6.3.4|github.github-vscode-theme-6.3.4|
|gitlens|eamodio|14.9.0|eamodio.gitlens-14.9.0|
|intelli-php-vscode|DEVSENSE|0.12.15062|devsense.intelli-php-vscode-0.12.15062-darwin-arm64|
|intellicode-api-usage-examples|VisualStudioExptTeam|0.2.8|visualstudioexptteam.intellicode-api-usage-examples-0.2.8|
|jwt-decoder|jflbr|1.2.0|jflbr.jwt-decoder-1.2.0|
|language-x86-64-assembly|13xforever|3.1.4|13xforever.language-x86-64-assembly-3.1.4|
|laravel-blade|onecentlin|1.36.0|onecentlin.laravel-blade-1.36.0|
|latte|Kasik96|0.18.0|kasik96.latte-0.18.0|
|loginspector|LogInspector|1.6.4|loginspector.loginspector-1.6.4|
|makefile-tools|ms-vscode|0.9.10|ms-vscode.makefile-tools-0.9.10|
|markdown-checkbox|bierner|0.4.0|bierner.markdown-checkbox-0.4.0|
|markdown-emoji|bierner|0.3.0|bierner.markdown-emoji-0.3.0|
|markdown-footnotes|bierner|0.1.1|bierner.markdown-footnotes-0.1.1|
|markdown-mermaid|bierner|1.22.0|bierner.markdown-mermaid-1.22.0|
|markdown-preview-github-styles|bierner|2.0.4|bierner.markdown-preview-github-styles-2.0.4|
|markdown-yaml-preamble|bierner|0.1.0|bierner.markdown-yaml-preamble-0.1.0|
|msbuild-project-tools|tintoy|0.6.3|tintoy.msbuild-project-tools-0.6.3|
|ng-template|Angular|17.3.1|angular.ng-template-17.3.1|
|npm-intellisense|christian-kohler|1.4.5|christian-kohler.npm-intellisense-1.4.5|
|openxml-explorer|sergey-tihon|0.1.1|sergey-tihon.openxml-explorer-0.1.1|
|path-intellisense|christian-kohler|2.8.5|christian-kohler.path-intellisense-2.8.5|
|phptools-vscode|DEVSENSE|1.45.15272|devsense.phptools-vscode-1.45.15272-darwin-arm64|
|powershell|ms-vscode|2024.2.0|ms-vscode.powershell-2024.2.0|
|prettier-vscode|esbenp|10.4.0|esbenp.prettier-vscode-10.4.0|
|randomeverything|helixquar|0.0.3|helixquar.randomeverything-0.0.3|
|remote-containers|ms-vscode-remote|0.354.0|ms-vscode-remote.remote-containers-0.354.0|
|remote-explorer|ms-vscode|0.4.3|ms-vscode.remote-explorer-0.4.3|
|remote-server|ms-vscode|1.5.1|ms-vscode.remote-server-1.5.1|
|remote-ssh|ms-vscode-remote|0.110.1|ms-vscode-remote.remote-ssh-0.110.1|
|remote-ssh-edit|ms-vscode-remote|0.86.0|ms-vscode-remote.remote-ssh-edit-0.86.0|
|remote-wsl|ms-vscode-remote|0.88.0|ms-vscode-remote.remote-wsl-0.88.0|
|rest-client|humao|0.25.1|humao.rest-client-0.25.1|
|ruby-rubocop|misogi|0.8.6|misogi.ruby-rubocop-0.8.6|
|sass-indented|syler|1.8.29|syler.sass-indented-1.8.29|
|scala|scala-lang|0.5.7|scala-lang.scala-0.5.7|
|shell-format|foxundermoon|7.2.5|foxundermoon.shell-format-7.2.5|
|shellcheck|timonwong|0.37.1|timonwong.shellcheck-0.37.1-darwin-arm64|
|stately-vscode|statelyai|2.1.0|statelyai.stately-vscode-2.1.0|
|swift-lang|sswg|1.8.1|sswg.swift-lang-1.8.1|
|syntax-project-pbxproj|mariomatheu|0.1.3|mariomatheu.syntax-project-pbxproj-0.1.3|
|terraform|hashicorp|2.30.0|hashicorp.terraform-2.30.0-darwin-arm64|
|test-adapter-converter|ms-vscode|0.1.9|ms-vscode.test-adapter-converter-0.1.9|
|text-power-tools|qcz|1.47.1|qcz.text-power-tools-1.47.1|
|theme-monokai-pro-vscode|monokai|1.2.2|monokai.theme-monokai-pro-vscode-1.2.2|
|tmlanguage|pedro-w|1.0.0|pedro-w.tmlanguage-1.0.0|
|volar|Vue|2.0.10|vue.volar-2.0.10|
|vscode-angular-html|ghaschel|2.10.2|ghaschel.vscode-angular-html-2.10.2|
|vscode-antlr4|mike-lischke|2.4.6|mike-lischke.vscode-antlr4-2.4.6|
|vscode-apache|mrmlnc|1.2.0|mrmlnc.vscode-apache-1.2.0|
|vscode-azurefunctions|ms-azuretools|1.14.1|ms-azuretools.vscode-azurefunctions-1.14.1|
|vscode-azureresourcegroups|ms-azuretools|0.8.4|ms-azuretools.vscode-azureresourcegroups-0.8.4|
|vscode-azureterraform|ms-azuretools|0.3.2|ms-azuretools.vscode-azureterraform-0.3.2|
|vscode-bazel|BazelBuild|0.9.0|bazelbuild.vscode-bazel-0.9.0|
|vscode-c-cpp-dev-extension-pack|franneck94|0.10.0|franneck94.vscode-c-cpp-dev-extension-pack-0.10.0|
|vscode-codeowners|jasonnutter|1.1.1|jasonnutter.vscode-codeowners-1.1.1|
|vscode-commitizen|KnisterPeter|1.1.0|knisterpeter.vscode-commitizen-1.1.0|
|vscode-docker|ms-azuretools|1.29.0|ms-azuretools.vscode-docker-1.29.0|
|vscode-dotnet-runtime|ms-dotnettools|2.0.3|ms-dotnettools.vscode-dotnet-runtime-2.0.3|
|vscode-edge-devtools|ms-edgedevtools|2.1.5|ms-edgedevtools.vscode-edge-devtools-2.1.5|
|vscode-eslint|dbaeumer|2.4.4|dbaeumer.vscode-eslint-2.4.4|
|vscode-github-actions|github|0.26.2|github.vscode-github-actions-0.26.2|
|vscode-guid|heaths|1.9.0|heaths.vscode-guid-1.9.0|
|vscode-hexpat|calcoph|0.1.2|calcoph.vscode-hexpat-0.1.2|
|vscode-icons|vscode-icons-team|12.7.0|vscode-icons-team.vscode-icons-12.7.0|
|vscode-java-debug|vscjava|0.57.0|vscjava.vscode-java-debug-0.57.0|
|vscode-java-dependency|vscjava|0.23.6|vscjava.vscode-java-dependency-0.23.6|
|vscode-java-pack|vscjava|0.26.0|vscjava.vscode-java-pack-0.26.0|
|vscode-jest|Orta|6.2.4|orta.vscode-jest-6.2.4|
|vscode-lldb|vadimcn|1.10.0|vadimcn.vscode-lldb-1.10.0|
|vscode-markdownlint|DavidAnson|0.54.0|davidanson.vscode-markdownlint-0.54.0|
|vscode-maven|vscjava|0.44.0|vscjava.vscode-maven-0.44.0|
|vscode-nginx|william-voyek|0.7.2|william-voyek.vscode-nginx-0.7.2|
|vscode-npm-script|eg2|0.3.29|eg2.vscode-npm-script-0.3.29|
|vscode-presentation-mode|CS50|1.0.4|cs50.vscode-presentation-mode-1.0.4|
|vscode-proto3|zxh404|0.5.5|zxh404.vscode-proto3-0.5.5|
|vscode-pull-request-github|GitHub|0.86.1|github.vscode-pull-request-github-0.86.1|
|vscode-remote-extensionpack|ms-vscode-remote|0.25.0|ms-vscode-remote.vscode-remote-extensionpack-0.25.0|
|vscode-scss|mrmlnc|0.10.0|mrmlnc.vscode-scss-0.10.0|
|vscode-stylelint|stylelint|1.4.0|stylelint.vscode-stylelint-1.4.0|
|vscode-tailwindcss|bradlc|0.10.5|bradlc.vscode-tailwindcss-0.10.5|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscodeintellicode|VisualStudioExptTeam|1.3.1|visualstudioexptteam.vscodeintellicode-1.3.1|
|vscodeintellicode-csharp|ms-dotnettools|2.0.25|ms-dotnettools.vscodeintellicode-csharp-2.0.25-darwin-arm64|
|vsliveshare|ms-vsliveshare|1.0.5918|ms-vsliveshare.vsliveshare-1.0.5918|
|xml|DotJoshJohnson|2.5.1|dotjoshjohnson.xml-2.5.1|;

</details>

Extension version: 2.24.17
VS Code version: Code 1.88.1 (e170252f762678dec6ca2cc69aba1570769a5d39, 2024-04-10T17:43:08.196Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id b832e0d3-7ca0-4a0e-b69e-171b9e510aac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
dsvsc021:30996838
gd77d436:30999572
g316j359:31013175

```

</details>

**Comment by dibarbet** [comment] 2024-04-16 19:02
@jozefizso would you mind describing exactly what you're expecting, and what you're actually seeing (screenshots are always helpful).  Additionally the C# output window logs (and Projects output window logs) would be useful here.

**Comment by jozefizso** [comment] 2024-04-16 20:30
As I am paying for Visual Studio Subscription, I would expect the same functionality as in Visual Studio. Instead, the C# Dev Kit just stops functioning after few minutes.

**Comment by spajus** [comment] 2024-04-24 15:59
I can confirm something similar is happening. Intellisense works for a while and then stops, reloading the window fixes it for a few more minutes. The issue is so bad that it makes VSCode barely usable. I'll try to collect some logs and post an update here later.

**Comment by martinhenrysson** [comment] 2024-09-02 13:07
Any updates here? Same issue still on a Mac M1.

**Comment by martinhenrysson** [comment] 2024-09-02 13:52
https://github.com/dotnet/roslyn/issues/72811#issuecomment-2250313469 Setting `<EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>` in the .csproj file seems to have improved the situation.

**Comment by dibarbet** [comment] 2024-09-05 00:26
Issues with code actions + `EnforceCodeStyleInBuild` set to true are tracked by https://github.com/dotnet/roslyn/issues/72811

Unfortunately for the original issue as filed, we're not able to action it without logs.  Closing this one.  If you're still having problems, please file a *new* issue and include a description of what feature exactly is not working as expected and the C# logs.  Thanks!

**Closed by dibarbet** 2024-09-05 00:26 UTC
Labels: Needs More Info
