### ISSUE TITLE
Go to Definition will go to decompiled code instead of the actual code in different project

### ISSUE THREAD

**Issue by tverboon** [dotnet/vscode-csharp#5711] opened 2023-06-07 05:27 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.202/

Host:
  Version:      7.0.4
  Architecture: arm64
  Commit:       0a396acafe

.NET SDKs installed:
  6.0.300 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: `1.78.2`
C# Extension version: `2.0.206 Pre-Release`

## Steps to reproduce
Press F12 (Go to definition) on code defined in a different project within the same solution.

## Expected  behavior
Go to the code in the solution.

## Actual behavior
Pressing F12 will go to decompiled code from the assembly in the obj directory. Go to definition within the same project works as it should.

---

I suppose I should have reported this in the vscode-dotnettools repo:
https://github.com/microsoft/vscode-dotnettools/issues/40

**Comment by dibarbet** [comment] 2023-06-07 17:56
Thanks - looks like a dupe of https://github.com/dotnet/roslyn/issues/68472

**Closed by dibarbet** 2023-06-07 17:56 UTC
