### ISSUE TITLE
[BUG] VSCode can no longer organize C# using statements

### ISSUE THREAD

**Issue by arkalyanms** [dotnet/vscode-csharp#6797] opened 2024-01-09 17:33 UTC
From vscode-dotnettools created by [mikey-t](https://github.com/mikey-t): microsoft/vscode-dotnettools#834  

### Describe the Issue

VSCode no longer appears to support organizing using statements in C# files. Prevoiusly the setting `"omnisharp.organizeImportsOnFormat"` accomplished this, but it appears to do nothing now.

I found some semi-related issues, but they aren't quite the same:

"Remove unused imports on save"
https://github.com/dotnet/roslyn/issues/68556
This is asking for something new rather than (or in addition to) pointing out that the previously working functionality is broken.

"Add a command or function - Remove and Sort Usings"
https://github.com/dotnet/vscode-csharp/issues/5320
This is from mid-2022 and someone suggested using the omnisharp setting which appears to no longer work.

### Steps To Reproduce

1. In a fresh clean copy of vscode, install the C# Dev Kit
2. Ensure setting: `"omnisharp.organizeImportsOnFormat": true`
3. Open a C# project and navigate to any C# file with using statements
4. Add some using statements that aren't used
5. Change the order of the using statements
6. Format the document
7. Try adding an `.editorconfig` file with `dotnet_sort_system_directives_first = true` in the C# section
8. Try formatting document again

### Expected Behavior

Unused using statements should be removed and the remaining  using statements should be sorted, but nothing happens at all (no sort, no removal - no errors in extension output).

### Environment Information

Windows 10 - doesn't work for vscode or vscode-insiders:

VSCode
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

VSCode Insiders
Version: 1.86.0-insider (user setup)
Commit: 9621add46007f7a1ab37d1fce9bcdcecca62aeb0
Date: 2023-12-20T05:36:57.756Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by arkalyanms** [comment] 2024-01-09 17:34
Looks a dup of https://github.com/dotnet/vscode-csharp/issues/5320

**Comment by dibarbet** [comment] 2024-01-09 20:49
@arkalyanms I think this would be resolved with https://github.com/dotnet/roslyn/pull/70538 (cc @sharwell )
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6148

**Closed by dibarbet** 2024-01-09 20:49 UTC
Labels: Bug, OmniSharp
