### ISSUE TITLE
Can no longer target a directory containing subdirectories with csproj files

### ISSUE THREAD

**Issue by wuzzeb** [dotnet/vscode-csharp#4691] opened 2021-07-29 20:15 UTC
In this commit on line 181, the ability to open a directory in which many subdirectories contained csproj files was removed.

https://github.com/OmniSharp/omnisharp-vscode/commit/369a904da6b7cbf4379f64bdc5496032548b4056#diff-c297262b72ad1ea22e80c49f21777b21eeab88e2c535f0286a387c392f85c91cL181

The logic was `if ((hasCsProjFiles && !hasSlnFile) || (hasProjectJson && !hasProjectJsonAtRoot))`  but now it is gone completely.  This is exactly the condition in my project: no sln file anywhere, no project.json anywhere, and the root directory opened in vscode has a bunch of subdirectories, each of which contain csproj files.

What was the reason to remove the (hasCsProjFiles && !hasSlnFile) check to add a directory target?

I re-added the check in https://github.com/wuzzeb/omnisharp-vscode/commit/00894e1c3148eb70aa10b5679b6569caa0adc404 and it works perfectly for me.

Should I submit a pull-request?  I am somewhat hesitant to submit a pull request because the check was deliberately deleted.  Was there a reason to remove this development mode?

**Comment by JoeRobich** [comment] 2021-07-29 21:24
@wuzzeb Sorry if we broke your scenario. We were trying to make working with projects easier by adding them to the Project Select (command "OmniSharp: Select Project"). Please open a PR and we will review and get it in.

Also, are you using the "Load projects on demand" feature?

**Comment by lonix1** [comment] 2021-07-30 16:33
Will this only be fixed in the next vscode update a month from now?

It "broke" vscode for us. Don't know what to do other than roll back and that always leads to problems with mono.

Any advice appreciated

**Comment by lonix1** [comment] 2021-07-31 04:14
@wuzzeb Did you find a workaround or setting or something, or are you just living with this bug? :)

**Comment by lonix1** [comment] 2021-08-03 14:05
Hi again @JoeRobich is this bug on the roadmap? It landed just a few days ago, that's why I'm pushing - whereas a while from now it'll just be another issue on the backlog.

So my question is, is this on the todo list for the next update / hotfix?

Hate to sound like a broken record but it's a nasty one. Working on big projects is insanely difficult right now.

**Comment by JoeRobich** [comment] 2021-08-03 16:16
Please try this prerelease https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.15-beta1

**Comment by alexrp** [comment] 2021-08-04 02:40
I can confirm that the above pre-release fixes the issue for me.

**Comment by Sour-Codes** [comment] 2021-08-04 23:18
Also confirming the pre-release is exactly what I needed.  After six days of wondering why my projects weren't loading, I gave up and searched for this.  I support this thread.  Please make this an option.  I think the lack of a *.sln should imply that I want everything loaded.

**Comment by lonix1** [comment] 2021-08-05 02:28
> I think the lack of a *.sln should imply that I want everything loaded.

Agreed. The original behavior should be restored to alleviate our suffering.

---
Side note, to consider **after** this issue is fixed:

Since being forced to use that little dropdown to switch between projects, I noticed something *unexpectedly positive*. The IDE is snappier because not everything is loaded. It would be nice to have a new option where we can tick multiple projects (instead of just one) in that dropdown, to load just those projects we need. Then I wouldn't load those projects that I rarely touch - instant perf improvement.

**Comment by Sour-Codes** [comment] 2021-08-05 19:50
Not sure how much alteration one can do to the explorer window as I never tried building for an IDE; however, adding onto what @lonix1 is suggesting, a tick box next to the paths that it detects with project files is a better approach to "...make working with projects easier."

Using below as an example.  This path has over 40 projects with a dependency to one.  I might decide now to work on one sensor...get bored...work on another...get bored...see a delivery arrived with more sensors...work on that...get bored, go back to the first.... Intellisense worked perfectly until .... well, we all already know what happened...

![image](https://user-images.githubusercontent.com/62261400/128411169-2ece9696-8001-4138-b525-e23a18cd2fe9.png)

(Also, don't forget a select/deselect all if going with this approach otherwise we're all back in another thread wishing things were as simple as the old ways...)

Until a few days ago, this was a mindless process for years.  Having to select which project I want to work on makes me think "well, why not just install bloated Visual Studio that forces a *.sln file anyway and work with that as in the very least, it'll automatically add new projects into the *.sln file without me having to pick..."

Not knocking ya -- I 🖤 Omnisharp and it was the sole reason I got rid of Visual Studio years ago for its simplicity that you don't get using VS.  I'm just a bit triggered with this *.sln dependency approach.

**Comment by lonix1** [comment] 2021-08-06 02:30
As I recall Visual Studio has support for specifying which projects to load, so it's not all or nothing. However it's not an easy process, there's dialog boxes, and dependency checks, and whatnot.

So the same idea in VSCode - *some day after this fix is released, let's not lose sight of the main goal* - would be very much appreciated. (@JoeRobich would you like for me to open a new feature request issue?)

The two ideas are: multiple ticks in the project selector dropdown (my preference), and ticks next to projects in the explorer pane (@Sour-Codes' preference).

**Comment by lonix1** [comment] 2021-08-20 03:33
@JoeRobich Any guess as to when the fix will be released?

**Comment by Banyc** [comment] 2021-09-03 07:26
> @wuzzeb Sorry we broke your scenario. We were trying to make working with projects easier by adding them to the Project Select (command "OmniSharp: Select Project"). Please open a PR and we will review and get it in.
> 
> Also, are you using the "Load projects on demand" feature?

@wuzzeb I was obstructed by the same issue until I found this issue. I wish for an explicit instruction on this mechanism. Otherwise, new comers might consider it as a bug and feel frustrated. But once people have learned it in advance, this mechanism will be a good way to enhance their experience! Thanks for your hard work as usual!

**Comment by carlin-q-scott** [comment] 2023-08-17 20:22
Why is this issue open? It looks like it was supposed to be fixed two years ago, but I'm seeing the issue with the latest release of the extension and VS Code. My workspace has two sln files in the root, and a dozen csproj files in subdirectories. The extension documentation seems to say that it only supports a sln in the workspace root if there's also a csproj in the root. Am I understanding that correctly?

**Closed** 2024-11-13 08:06 UTC
Labels: OmniSharp
