### ISSUE TITLE
C# Dev Kit - solution filters

### ISSUE THREAD

**Issue by serj1980** [dotnet/vscode-csharp#6956] opened 2024-03-07 15:21 UTC
## Is your feature request related to a problem? Please describe.
When I use solution filter (.slnf) file it apply package restore step for full solution. It produce error because solution contains unsupported tfms for current OS.

## Describe the solution you would like
VS unload  project not present in list and skip (or ignore) unloaded project. It give me ability to use .slnf compatible with current OS.

## Applicable Scenarios
.sln have net8.0-windows and net8.0-macos projects. I have .slnf separate for net8.0-windows and  net8.0-macos projects and try to use it on Windows and MacOS versions of VS Code.

## Additional context
if I use "dotnet build" with .csproj - all works fine. Possible .slnf should use project level "dotnet restore" as solution.

**Comment by dibarbet** [comment] 2024-03-19 18:09
duplicate of https://github.com/microsoft/vscode-dotnettools/issues/103

**Closed by dibarbet** 2024-03-19 18:09 UTC
