### ISSUE TITLE
useGlobalMono="auto" has invalid documentation

### ISSUE THREAD

**Issue by isonil** [dotnet/vscode-csharp#4727] opened 2021-08-30 06:08 UTC
C# extension version: 1.23.14

There's a very common problem in VS Code on Mac.

The problem starts with this error:
```Error: This project targets .NET version that requires reference assemblies that do not ship with OmniSharp out of the box (e.g. .NET Framework)```

My "mono --version" gives "6.12.0.140" which is the latest version as of today.

This error can be solved by changing useGlobalMono from auto to always.

useGlobalMono states that:
"Launch OmniSharp with the globally-installed Mono. If set to "always", "mono" version 6.4.0 or greater must be available on the PATH. If set to "auto", OmniSharp will be launched with "mono" if version 6.4.0 or greater is available on the PATH."

But it's not true on Mac. The >=6.4.0 detection doesn't work.

This bug is also confirmed here by someone else:
https://github.com/OmniSharp/omnisharp-vscode/issues/4347
"For lost travelllers you need to set "omnisharp.useGlobalMono": "always" in VSCode settings otherwise it doesn't work in Mac... seems like kind of an important thing but it's tucked away in a Changelog"

**Comment by filipw** [comment] 2021-08-30 06:17
This is not a bug, it was intentionally changed - the behavior of `auto` to resolve to `never` instead of `always` was changed in 1.23.5 in November 2020 due to issues between Mono and MSBuild required to run .NET 5 and higher projects.

It is stated on top of the changed as the current known limitation
https://github.com/OmniSharp/omnisharp-vscode/blob/master/CHANGELOG.md#known-issues-in-12315

**Comment by isonil** [comment] 2021-08-30 06:20
> This is not a bug, it was intentionally changed - the behavior of `auto` to resolve to `never` instead of `always` was changed in 1.23.5 in November 2020 due to issues between Mono and MSBuild required to run .NET 5 and higher projects.
> 
> It is stated on top of the changelog as the current known limitation
> https://github.com/OmniSharp/omnisharp-vscode/blob/master/CHANGELOG.md#known-issues-in-12315

Thanks for looking into this. However, the text I've copy-pasted is from the VS code, so I think the bug is still there, no? Either the description is wrong or the behavior is wrong.

**Comment by filipw** [comment] 2021-08-30 06:25
The change is intended to be temporary, that is why we added a limitation note into the changelog, rather than change the property description.

**Comment by JoeRobich** [comment] 2024-11-13 07:59
Closing as answered.

**Closed by JoeRobich** 2024-11-13 07:59 UTC
Labels: OmniSharp, Triaged, Documentation
