### ISSUE TITLE
F12 The function cannot navigate

### ISSUE THREAD

**Issue by enjoycx** [dotnet/vscode-csharp#6764] opened 2023-12-19 03:34 UTC
![image](https://github.com/dotnet/vscode-csharp/assets/56945691/bcdf5c58-866a-40f6-b074-865106e4ff7e)
When using macro definitions, jumping to the places where the function is called from outside is possible. However, when inside the current function, using F12 to navigate fails to go outside.

**Comment by enjoycx** [comment] 2023-12-19 03:35
The function name below allows normal navigation, only the function name above does not work

**Comment by dibarbet** [comment] 2024-01-03 01:09
This is intentional - we only show the current active configuration based on what preprocessor directives are defined when we load the project.  However there appears to be a bug here - the code inside the disabled configuration should also be grayed out
![image](https://github.com/dotnet/vscode-csharp/assets/5749229/ce57ee7c-97a9-418b-93d6-c938c5d14605)

**Comment by dibarbet** [comment] 2024-05-22 23:06
The colorization issue is likely due to semantic highlighting being disabled.  Closing as by design since we only provide intellisense for the active configuration.

If you're having issues with the colorization not showing as greyed out with semantic highlighting enabled, please file a *new* issue.

**Closed by dibarbet** 2024-05-22 23:06 UTC
Labels: Bug
