### ISSUE TITLE
dotnet.exe infinite opening and closing

### ISSUE THREAD

**Issue by debugzxcv** [dotnet/vscode-csharp#7316] opened 2024-07-08 23:01 UTC
## Environment data
<details>
<summary><code>dotnet --info</code> output:</summary>

```
.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   X:\dotnet\sdk\8.0.302\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.302 [X:\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [X:\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [X:\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 8.0.6 [X:\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [X:\dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
</details>

<details><summary>VS Code <code>Version: 1.90.2</code></summary>

```
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045
```
</details>

C# Extension version: `v2.37.26`

<details>
<summary><h2>OmniSharp log</h2></summary> 

```
Using dotnet configured on PATH
Dotnet path: X:\dotnet\dotnet.exe
Activating C# standalone...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\4bea9565"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 06:25:51] [Program] Language server initialized
[Info  - 06:25:52] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:52] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:01.0552277
[Info  - 06:25:53] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:53] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.8122253
[Info  - 06:25:55] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:55] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.8204122
[Info  - 06:25:56] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:56] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7455021
[Info  - 06:25:57] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:57] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7589554
[Info  - 06:25:58] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:25:58] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7406095
[Info  - 06:26:00] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:00] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7422825
[Info  - 06:26:01] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:01] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7520075
[Info  - 06:26:02] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:02] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7437284
[Info  - 06:26:03] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:03] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7504434
[Info  - 06:26:05] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:05] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7496107
[Info  - 06:26:06] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:06] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7548870
[Info  - 06:26:07] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:07] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7559818
[Info  - 06:26:08] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:08] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7428444
[Info  - 06:26:09] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:09] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7518373
[Info  - 06:26:11] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:11] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7554753
[Info  - 06:26:12] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:12] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7440630
[Info  - 06:26:13] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:13] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7435091
[Info  - 06:26:14] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:14] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7411913
[Info  - 06:26:16] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:16] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7406187
[Info  - 06:26:17] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:17] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7508301
[Info  - 06:26:18] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:18] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7532772
[Info  - 06:26:19] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:19] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7908290
[Info  - 06:26:21] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:21] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7795811
[Info  - 06:26:22] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:22] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7546584
[Info  - 06:26:23] [LanguageServerProjectSystem] Successfully completed load of y:\src\test\test.csproj
[Info  - 06:26:23] [LanguageServerProjectSystem] Completed (re)load of all projects in 00:00:00.7581609
```
</details>

## Steps to reproduce

1. Download `test.zip` attachment 
2. Unzip `test.zip`
3. Open `test` folder in vscode

## Expected  behavior
Don't open and close dotnet.exe indefinitely.

## Actual behavior
See video

## Additional context
[test.zip](https://github.com/user-attachments/files/16135108/test.zip)

https://github.com/dotnet/vscode-csharp/assets/5125392/1edcb63f-a122-485f-a5c2-2792f9c582c8

**Comment by dibarbet** [comment] 2024-07-10 00:15
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6985

For a workaround, see https://github.com/dotnet/vscode-csharp/issues/6985#issuecomment-2010928435

**Closed by dibarbet** 2024-07-10 00:15 UTC
