### ISSUE TITLE
newest C# extension does not works (v2.0.328)

### ISSUE THREAD

**Issue by demetrebadzaradze** [dotnet/vscode-csharp#6052] opened 2023-08-06 08:41 UTC
## Environment data
`dotnet --info` output:
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

VS Code version:
Version: 1.81.0 (user setup)
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

C# Extension version:
v2.0.328

## Steps to reproduce

1. install C# extension v2.0.328 it newest  
2. update .net
3. and make C# hello world application

## Expected  behavior
vs code should behave like visual studio with this extension for example type "console." should be that little window that shows suggestions specific for C# 
## Actual behavior
and there is none of that also if error has made it wont be highlighted 
## Additional context
it might be my mistake but i don't think so please check it out and fix it
thanks

**Comment by Akronae** [comment] 2023-08-06 20:07
Same Issue with me, looking at the log, there is something wrong happening

I have the same issue using the VSCode C# extension

```
Dotnet path: /Users/alex/.vscode-server/data/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.9/dotnet
Activating C# standalone...
info: LanguageServerHost[0]
      Starting server...
No .NET SDKs were found.

Download a .NET SDK:
https://aka.ms/dotnet/download

Learn about SDK resolution:
https://aka.ms/dotnet/sdk-not-found
[Error - 9:46:18 PM] [LanguageServerHost]System.InvalidOperationException: Failed to find an appropriate version of .NET Core MSBuild. Call to hostfxr_resolve_sdk2 failed. There may be more details in stderr.
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
   at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.TryEnsureMSBuildLoadedAsync(String workingDirectory) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 119
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.OpenSolutionAsync(String solutionFilePath) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 79
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

dotnet --info:
```
.NET SDK:
 Version:   7.0.305
 Commit:    98e1b6c381

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.1
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.305/

Host:
  Version:      7.0.8
  Architecture: arm64
  Commit:       4b0550942d

.NET SDKs installed:
  6.0.411 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.305 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]
    registered at [/etc/dotnet/install_location_x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

echo $PATH | grep dotnet
```
/usr/local/share/dotnet/sdk/7.0.305
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet/dotnet
/usr/local/share/dotnet
~/.dotnet/tools
/Users/alex/.dotnet/tools
/Users/alex/.dotnet/tools
```

**Comment by peabnuts123** [comment] 2023-08-06 22:27
I am seeing the same on v2.x on MacOS. Extension is basically braindead and cannot do anything. Unlike others I am not seeing `No .NET SDKs were found.` it is just hanging on `Starting server...`. I am running a Unity project so it should be using mono anyway. Can't see any `Omnisharp: ` commands in command palette, C# syntax is not even highlighted properly. It's basically as if the extension is not even installed. Downgrading to 1.26.0 is working for me. Happy to provide whatever output from commands if-needed.

**Comment by JustinGrote** [comment] 2023-08-07 21:23
Probably dupe of https://github.com/dotnet/vscode-csharp/issues/6024

**Comment by dibarbet** [comment] 2023-08-07 22:08
Currently the 2.x version C# extension alone isn't able to load unity projects.   We're working on it (see https://github.com/dotnet/vscode-csharp/issues/5721), but in the meantime there are a few different workarounds you can use.
1.  If you're able to use C# devkit, we recommend using the unity extension as described here - https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/#getting-started-with-the-unity-extension
2.  Get the old O# behavior back via `dotnet.server.UseOmnisharp`
3.  Downgrade to a 1.x version of the extension.

**Comment by jasonmalinowski** [comment] 2023-08-08 00:36
@Akronae I've created #6063 for your issue; as best I can tell that's not being reported elsewhere and I don't want to lose that in the conversation. The other reports here are sounding more like this is a dupe of #5923.

**Comment by jasonmalinowski** [comment] 2023-08-08 19:05
I'm going to close this as a duplicate of #5923; @demetrebadzaradze an update should be going out later this week, if you're still seeing issues then feel free to reactivate this and include the C# output window logs and we can take a look further.

**Closed by jasonmalinowski** 2023-08-08 19:05 UTC
Labels: Project System
