### ISSUE TITLE
DefineConstants in csproj just ignored

### ISSUE THREAD

**Issue by rlanhellas** [dotnet/vscode-csharp#3749] opened 2020-04-28 12:50 UTC
## Environment data
.NET Core SDK (reflecting any global.json):
 Version:   2.1.607
 Commit:    cad4fbe2d5

Runtime Environment:
 OS Name:     fedora
 OS Version:  31
 OS Platform: Linux
 RID:         fedora.31-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.607/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.607 [/usr/share/dotnet/sdk]
  3.1.201 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

## Steps to reproduce
Add <DefineConstants>ENABLE_FIDDLER</DefineConstants> in ".csproj" file of IntegrationTests. This is my csproj:

```
<PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <IsPackable>false</IsPackable>
    <DefineConstants>ENABLE_FIDDLER</DefineConstants>
  </PropertyGroup>
```

And my peace of code:

```
#if ENABLE_FIDDLER
        var httpClient = _httpClientFactory.CreateClient("ProxiedClient");
#else
        var httpClient = _httpClientFactory.CreateClient();
#endif
```

## Expected  behavior
 ENABLE_FIDDLER constant should be set to enter in IF condition. 

## Actual behavior
ENABLE_FIDDLER constant isn't set and always my peace of code is ignored.

**Comment by JoeRobich** [comment] 2020-04-28 18:35
@rlanhellas Sorry this is causing issues. Looks like this might be fixed with https://github.com/OmniSharp/omnisharp-roslyn/pull/1774

**Comment by rlanhellas** [comment] 2020-04-28 21:27
Thanks, I will watch this PR.

**Comment by filipw** [comment] 2020-04-30 12:21
I am not sure what the bug here is. https://github.com/OmniSharp/omnisharp-roslyn/pull/1774 doesn't have anything to do with this becuase it deals with compilation options and these here are parse options which are already respected and updated on every csproj change

Have a look at this. Imagine I have `<DefineConstants>FOO</DefineConstants>` in my csproj.

<img width="373" alt="Screen Shot 2020-04-30 at 14 18 20" src="https://user-images.githubusercontent.com/1710369/80709536-b9f5d700-8aed-11ea-849b-480f665cf409.png">

notice how `Foo()` shows 1 reference?

As soon as I remove `<DefineConstants>FOO</DefineConstants>`:

<img width="391" alt="Screen Shot 2020-04-30 at 14 20 02" src="https://user-images.githubusercontent.com/1710369/80709637-e578c180-8aed-11ea-8921-4d9177c737b4.png">

notice how `Foo()` is now unreachable? (no code lens).
The only thing not supported at the moment is "fading out" like VS.

**Comment by SirIntruder** [comment] 2020-04-30 15:25
Filip is right, I can also confirm changes to DefineConstants are correctly applied already. Turns out they were part of `ParseOptions`, not `CompilationOptions`. 

One thing that confused me while I was testing, changes to baseline `<DefineConstants>` are ignored if you, by any chance, have separate `<DefineConstants>` defined in Release/Debug configurations in .csproj file. That's just normal VS/MSBuild behaviour, not a bug.

**Comment by JoeRobich** [comment] 2024-11-12 07:42
Closing due to lack of activity.

**Closed by JoeRobich** 2024-11-12 07:42 UTC
Labels: Bug, OmniSharp, Triaged, Project System
