### ISSUE TITLE
Unexpected "Library" directory in home directory

### ISSUE THREAD

**Issue by ManickaP** [dotnet/vscode-csharp#5781] opened 2023-06-11 14:08 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   8.0.100-preview.6.23305.3
 Commit:    d092ea07f8

Runtime Environment:
 OS Name:     arch
 OS Version:
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.100-preview.6.23305.3/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.6.23304.2
  Architecture: x64
  Commit:       2bf8f1aa83

.NET SDKs installed:
  6.0.403 [/usr/share/dotnet/sdk]
  7.0.100 [/usr/share/dotnet/sdk]
  8.0.100-preview.4.23260.5 [/usr/share/dotnet/sdk]
  8.0.100-preview.6.23305.3 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.4.23260.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23302.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.4.23259.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23304.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version:
```
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.3.3-arch1-1
Sandboxed: No
```
C# Extension version:
```
C#
v2.0.206
Pre-Release
```

## OmniSharp log
N/A

## Steps to reproduce

When I switched to the new C# extension, "Library" directory with `Library/Application Support/Microsoft Visual Studio/prpbg.dat` appears in my home directory. When deleted, it reappears every time a project is opened. This doesn't happen with OmniSharp.

## Expected  behavior
This extension should not make a mess in home directory, there is an XDG standard for configs, caches, local storages etc., see https://wiki.archlinux.org/title/XDG_Base_Directory.

## Actual behavior
Follow the Linux standard and do not store those data in home in a non-hidden directory.

## Additional context
OS: Arch Linux x86_64
Kernel: 6.3.3-arch1-1

**Comment by Igorgro** [comment] 2023-06-11 15:52
I have the same OS and extension version, but newer vscode and cannot reproduce this problem

**Comment by dibarbet** [comment] 2023-06-12 18:11
Are you using C# devkit as well?

**Comment by dibarbet** [comment] 2023-06-12 18:49
I can repro this using C# devkit.  When devkit is enabled, it appears to create a `prpbg.dat` and `prpbg.dat.bak` in the folder you mention.  If I have devkit disabled, the files are not created.

Closing this issue, track it on the devkit side here - https://github.com/microsoft/vscode-dotnettools/issues/118

**Comment by ManickaP** [comment] 2023-06-13 07:44
> Are you using C# devkit as well?

Yep, I do.

> I can repro this using C# devkit. When devkit is enabled, it appears to create a `prpbg.dat` and `prpbg.dat.bak` in the folder you mention. If I have devkit disabled, the files are not created.
> 
> Closing this issue, track it on the devkit side here - [microsoft/vscode-dotnettools#118](https://github.com/microsoft/vscode-dotnettools/issues/118)

I'll be watching that issue then. Thanks.

**Comment by dibarbet** [comment] 2023-06-16 00:07
Apparently I didn't actually hit the close button the first time.  Actually closing it this time in favor of https://github.com/microsoft/vscode-dotnettools/issues/118

**Closed by dibarbet** 2023-06-16 00:07 UTC
Labels: Bug, Triaged, Needs Investigation
