### ISSUE TITLE
OmniSharp never loads in a remote SSH window

### ISSUE THREAD

**Issue by winstliu** [dotnet/vscode-csharp#5155] opened 2022-04-05 18:39 UTC
## Issue Description ##
I'm trying to work on a C# solution using Remote SSH. Unfortunately, OmniSharp never seems to load.

## Steps to Reproduce ##
Use VS Code's Remote SSH capabilities to SSH into a Windows machine. useModernNet is true.

## Expected Behavior ##
OmniSharp to load.

## Actual Behavior ##
No logs. Nothing! :(
`OmniSharp: Restart OmniSharp` doesn't seem to have any effect.
I see the OmniSharp `1.38.2-net6.0` server downloaded at `~\.vscode-server\extensions\ms-dotnettools.csharp-1.24.3\.omnisharp`.

### OmniSharp log ###
Literally blank.
<img width="867" alt="No OmniSharp log" src="https://user-images.githubusercontent.com/2766036/161826323-0f74f16b-56b9-402b-9d34-78e26defe83c.png">

### C# log ###
Also completely blank.
<img width="867" alt="No C# log" src="https://user-images.githubusercontent.com/2766036/161826433-a7ca1a4e-d732-4b3c-b2c4-0ef948cdcf00.png">

## Environment information ##

**VSCode version**: 1.66.0
**C# Extension**: 1.24.3

<details><summary>Dotnet Information</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|azure-account|ms-vscode|0.10.1|
|azure-pipelines|ms-azure-devops|1.202.0|
|csharp|ms-dotnettools|1.24.3|
|powershell|ms-vscode|2021.12.0|
|vscode-bicep|ms-azuretools|0.4.1318|
|vscode-dotnet-runtime|ms-dotnettools|1.5.0|;

</details>

**Comment by JoeRobich** [comment] 2022-04-05 21:45
@50Wliu Are you opening an individual C# file or a folder containing a .csproj or .sln?

**Comment by 50Wliu** [comment] 2022-04-05 22:11
Git repository containing a C# .sln at the root level.

**Comment by JoeRobich** [comment] 2022-04-08 20:57
@50Wliu In the `Log (Extension Host)` log in the VS Code Output Pane, is there any errors or mention of `csharp`?

**Comment by 50Wliu** [comment] 2022-04-12 21:13
Nothing in `Log (Extension Host)`.

But in `Log (Remote Extension Host)`, I have:
```
[2022-04-12 21:10:57.391] [exthost] [info] ExtensionService#_doActivateExtension ms-dotnettools.csharp, startup: false, activationEvent: 'onLanguage:csharp'
```

Most OmniSharp/.NET commands error with "OmniSharp server is not running".

**Comment by 50Wliu** [comment] 2022-04-13 21:59
Today I see this in the C# log (still nothing in OmniSharp):
```
Installing C# dependencies...
Platform: win32, x86_64

Downloading package 'OmniSharp for Windows (.NET 6 / x64)' (39624 KB).................... Done!
Validating download...
Integrity Check succeeded.
Installing package 'OmniSharp for Windows (.NET 6 / x64)'

Finished
```
Lemme try RDPing to the machine and seeing if it'll start up if I run VS Code visually on the remote.

**Comment by 50Wliu** [comment] 2022-06-06 21:29
Remoting in worked fine.

Now I see this in the extension host log:
```
[2022-06-03 12:47:06.340] [exthost] [info] Not activating extension 'ms-dotnettools.csharp': Timed out while searching for 'workspaceContains' pattern **/*.{csproj,sln,slnf,csx,cake}
```

**Comment by Thaina** [comment] 2022-09-30 09:10
I have made it work with intellisense. But it seem it not report error in ssh windows

**Comment by devel0** [comment] 2023-01-28 00:57
I got the same problem, solved by opening FULL PATH of the project folder ( ie. cd somepath, then use `pwd` to show full path ).

In my case following happens using C-K-O ( open folder ):

- omnisharp intellisense not working
`/cloud/personal/projects/sample`
( having that `/cloud` is a **symlink** to `/nas/cloud` )

- omnisharp intellisense working
`/nas/cloud/personal/projects/sample`

**Comment by JoeRobich** [comment] 2024-11-13 08:48
> Now I see this in the extension host log:
> 
> ```
> [2022-06-03 12:47:06.340] [exthost] [info] Not activating extension 'ms-dotnettools.csharp': Timed out while searching for 'workspaceContains' pattern **/*.{csproj,sln,slnf,csx,cake}
> ```

Closing as duplicate of https://github.com/dotnet/vscode-csharp/issues/4959

**Closed by JoeRobich** 2024-11-13 08:48 UTC
Labels: OmniSharp
