### ISSUE TITLE
Why does intellisense autocompletion delete the remaining string!?!

### ISSUE THREAD

**Issue by khteh** [dotnet/vscode-csharp#5817] opened 2023-06-16 03:17 UTC
## Environment data
`dotnet --info` output:
```
.NET SDK:
 Version:   7.0.107
 Commit:    bf72c06963

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  23.04
 OS Platform: Linux
 RID:         ubuntu.23.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.107/

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.107 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
VS Code version: 1.79.2
C# Extension version: 1.25.9

## Steps to reproduce

Just type anything at the beginning of a string. Autocompletion will delete remaining string which rolls your eyeballs trying to recollect what was there previously before the autocompletion. This is awefully wrong.

## Expected  behavior
Insert a space instead of remove the remaining string.

## Additional context
https://github.com/dotnet/vscode-csharp/issues/3296

**Comment by Igorgro** [comment] 2023-06-16 13:39
Duplicate of #5777

**Closed** 2023-06-16 17:44 UTC
Labels: Bug, Resolved-Duplicate, Editor-IntelliSense

**Comment by genlu** [comment] 2023-06-16 17:47
This is the issue with OmniSharp, not the new C# Roslyn Server. Duplicate of https://github.com/dotnet/vscode-csharp/issues/5804
