### ISSUE TITLE
Symbol Search should show metadata symbols in addition to source symbols

### ISSUE THREAD

**Issue by hubluesky** [dotnet/vscode-csharp#1956] opened 2018-01-10 10:30 UTC
## Environment data
`dotnet --info` output:
VS Code version: 1.19.1
C# Extension version: 1.13.0

## Steps to reproduce
Open a script from dll
Cannot match symbols

## Actual behavior

![image](https://user-images.githubusercontent.com/6335104/34767705-be652184-f633-11e7-9d1b-f22de987f487.png)

**Comment by rchande** [comment] 2018-01-17 16:27
@hubluesky Where did you get that .cs file? Is it part of a c# project (csproj), or sitting alone in a file?

**Comment by DustinCampbell** [comment] 2018-01-23 18:50
This looks like metadata-as-source created from a symbol.

@hubluesky : Could you provide more information on how to reproduce this issue? If you could provide a project the reproduces the problem, that would be very helpful.

**Comment by hubluesky** [comment] 2018-01-24 09:44
1、use unity create a project (my unity version is 5.6.2f1)
2、Create a C# script and open it by vscode (must setting unity externalTool/external script editor is vscode)
3、typing script like this
     UnityEngine.UI.Image i;
4、Open link Image class (F12)
5、The Image class no symbols matching
sorry my pool english!

**Comment by DustinCampbell** [comment] 2018-01-24 20:29
I'm not sure I understand what you are expecting to happen in step 5, but I _think_ that what you are seeing is by design. It feels to me like there's a missing step between steps 4 and 5 where you invoke the "Go to symbol in workspace..." feature (Ctrl+T). Is that right?

F12 (the "go to definition" feature) will generate a special "metadata-as-source" file when invoked on a symbol that comes from metadata. However, this file is not part of your project. And, symbols contained within the metadata references of your project (such as Image from UnityEngine.UI.dll) are not included in the "Go to symbol in workspace..." (Ctrl+T) feature.

**Comment by hubluesky** [comment] 2018-01-25 03:39
Yes, In step 5, I invoke the "gotoSymbol" action (ctrl+shift+o), And it's like this
![default](https://user-images.githubusercontent.com/6335104/35369370-8844d2f0-017f-11e8-8820-6b0adfb9b728.png)
And, In step 2,I Create C# script, invoke the "gotoSymbol" (ctrl+shift+o), It's like this
![2](https://user-images.githubusercontent.com/6335104/35369695-2e3d20f8-0181-11e8-8c57-d1f622a6e78b.png)
 I can see the class symbols, But the Image class can not see any symbols.

**Comment by DustinCampbell** [comment] 2018-01-25 16:16
Thanks for clarifying @hubluesky. Yes, this is currently expected. Only symbols from your project's source code are shown. Symbols from your project's referenced metadata are not.

I'll go ahead and update the title and convert this to a feature request to show metadata symbols. I'm not sure when we might get around to implementing this (contributions are welcome!) but it'll be on our backlog.

**Comment by TheRealPiotrP** [comment] 2018-04-24 18:25
@rchande

**Comment by JoeRobich** [comment] 2024-11-09 00:26
Closing as there has not been a lot of demand for this enhancement.

**Closed by JoeRobich** 2024-11-09 00:26 UTC
Labels: Feature Request, Backlog, OmniSharp, Editor-Symbol Search
