### ISSUE TITLE
Go to Definition (F12) doesn't work in decompiled source/assembly metadata 

### ISSUE THREAD

**Issue by cfbao** [dotnet/vscode-csharp#7408] opened 2024-07-30 21:06 UTC
## Environment data

* `dotnet --info` output:
  ```
  .NET SDK:
   Version:           9.0.100-preview.6.24328.19
   Commit:            ef4c241666
   Workload version:  9.0.100-manifests.e32572b3
   MSBuild version:   17.11.0-preview-24318-05+4a45d5633
  
  Runtime Environment:
   OS Name:     Windows
   OS Version:  10.0.19045
   OS Platform: Windows
   RID:         win-x64
   Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.6.24328.19\
  
  .NET workloads installed:
  Configured to use loose manifests when installing new manifests.
   [aspire]
     Installation Source: VS 17.10.35027.167
     Manifest Version:    8.0.1/8.0.100
     Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.0.1\WorkloadManifest.json
     Install Type:        FileBased
  
  
  Host:
    Version:      9.0.0-preview.6.24327.7
    Architecture: x64
    Commit:       static
  
  .NET SDKs installed:
    8.0.303 [C:\Program Files\dotnet\sdk]
    9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]
  
  .NET runtimes installed:
    Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  Other architectures found:
    x86   [C:\Program Files (x86)\dotnet]
      registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
  
  Environment variables:
    Not set
  
  global.json file:
    Not found
  
  Learn more:
    https://aka.ms/dotnet/info
  
  Download .NET:
    https://aka.ms/dotnet/download
  ```

* VS Code version:
  ```
  Version: 1.91.1 (user setup)
  Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
  Date: 2024-07-09T22:06:49.809Z
  Electron: 29.4.0
  ElectronBuildId: 9728852
  Chromium: 122.0.6261.156
  Node.js: 20.9.0
  V8: 12.2.281.27-electron.0
  OS: Windows_NT x64 10.0.19045
  ```

* C# Extension version: v2.39.29

## Steps to reproduce

1. Create basic console project with `dotnet new console`
2. Open it with VS Code `code .`
3. Update `Program.cs`'s content to
   ```csharp
   await Task.Delay(TimeSpan.FromSeconds(1));
   ```
4. Move the text cursor to `Delay`, press F12, and get navigated to decompiled source/assembly metadata that reads
   ```csharp
   public static Task Delay(TimeSpan delay);
   ```
5. Move the text cursor to `TimeSpan`, press F12, and nothing happens

## Expected  behavior

I'm navigated to the definition of `System.TimeSpan`.

"Go to Definition (F12)" should work in decompiled source / assembly metadata to allow deep navigation into libraries.
This always worked in OmniSharp, but never worked with the new language server in my experience.

## Actual behavior

A small box shows up that says:

> No definition found for 'TimeSpan'

**Comment by dibarbet** [comment] 2024-07-31 18:17
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5787

Should be fixed in the next prerelease version (will be available on the marketplace shortly).

**Closed by dibarbet** 2024-07-31 18:17 UTC
