### ISSUE TITLE
Solution Explorer should support moving files

### ISSUE THREAD

**Issue by kenbrittain** [dotnet/vscode-csharp#7169] opened 2024-05-27 00:18 UTC
## Is your feature request related to a problem? Please describe.
The Solution Explorer view does not allow files to be moved. To accomplish you need to drop into the associated Folder view, or the native OS, and then move the file.

Once the file is moved it properly reflected in the Solution Explorer view.

## Describe the solution you would like
Support the standard operations for moving file in the Solution Explorer view.

- Cut/Copy+Paste
- Drag & Drop

 This functionality is supported in the Folder view.

## Applicable Scenarios
Files that are added to the Solution Explorer to the incorrect folder need to fixed by using the Folder view.

## Describe alternatives you've considered
My current alternative is to use the Folder view to move the file. The Solution Explorer view updates accordingly.

You can also use the Open Containing Folder menu item and move the file using the native OS file manager. This alternative is more jarring than staying in VSCode and accomplishing the same functionality in the Folder view.

## Additional context
When developing using the C# DevKit the Solution Explorer it is the main project view. This should be the location for managing the project. Part of managing the project involves moving files around during refactoring, migration, and general cleanup.

**Comment by dibarbet** [comment] 2024-06-18 01:05
Solution explorer is managed by C# Dev Kit, duplicate of this issue on their side.
https://github.com/microsoft/vscode-dotnettools/issues/182

**Closed by dibarbet** 2024-06-18 01:05 UTC
