### ISSUE TITLE
Intellisense replaces right of cursor instead of inserts

### ISSUE THREAD

**Issue by steveoh** [dotnet/vscode-csharp#5804] opened 2023-06-14 18:27 UTC
## Issue Description ##

My settings for suggestions are set to `insert`. When using this plugin, text is replaced.

`"editor.suggest.insertMode": "insert",`

## Steps to Reproduce ##

Place your cursor before the `await` and try to add a variable declaration e.g. `var result = await ...`

```csharp
await decorated.Handle(request, cancellationToken);
```

## Expected Behavior ##

I expect to be able to place my cursor before the `a` and type `va`+`tab` without the `await` being replaced.

## Actual Behavior ##

The `await` is repaced giving me an unexpected result

```csharp
var decorated.Handle(request, cancellationToken);
```

### OmniSharp log ###
<details>Post the output from Output-->OmniSharp log here</details>

### C# log ###
<details>Post the output from Output-->C# here</details>

## Environment information ##

**VSCode version**: 1.79.1
**C# Extension**: 1.25.9

<details><summary>Mono Information</summary>
        OmniSharp using mono: 6.12.0</details>
<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /Users/steveoh/.dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  2.1.816 [/Users/steveoh/.dotnet/sdk]
  3.1.409 [/Users/steveoh/.dotnet/sdk]
  3.1.410 [/Users/steveoh/.dotnet/sdk]
  3.1.411 [/Users/steveoh/.dotnet/sdk]
  5.0.205 [/Users/steveoh/.dotnet/sdk]
  5.0.207 [/Users/steveoh/.dotnet/sdk]
  5.0.208 [/Users/steveoh/.dotnet/sdk]
  5.0.300 [/Users/steveoh/.dotnet/sdk]
  5.0.301 [/Users/steveoh/.dotnet/sdk]
  5.0.400 [/Users/steveoh/.dotnet/sdk]
  6.0.100-rc.2.21505.57 [/Users/steveoh/.dotnet/sdk]
  6.0.100 [/Users/steveoh/.dotnet/sdk]
  6.0.101 [/Users/steveoh/.dotnet/sdk]
  6.0.102 [/Users/steveoh/.dotnet/sdk]
  7.0.102 [/Users/steveoh/.dotnet/sdk]
  7.0.202 [/Users/steveoh/.dotnet/sdk]
  7.0.302 [/Users/steveoh/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/Users/steveoh/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/Users/steveoh/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/Users/steveoh/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|
|---|---|---|
|amvim|auiworks|1.36.0|
|better-comments|aaron-bond|3.0.2|
|code-spell-checker|streetsidesoftware|2.20.5|
|colonize|vmsynkov|2.2.2|
|copilot-chat|GitHub|0.2.1|
|copilot-nightly|GitHub|1.89.159|
|csharp|ms-dotnettools|1.25.9|
|dotenv|mikestead|1.0.1|
|ecdc|mitchdenny|1.8.0|
|EditorConfig|EditorConfig|0.16.4|
|github-markdown-preview|bierner|0.3.0|
|live-server|ms-vscode|0.4.8|
|markdown-checkbox|bierner|0.4.0|
|markdown-emoji|bierner|0.3.0|
|markdown-footnotes|bierner|0.1.1|
|markdown-mermaid|bierner|1.18.1|
|markdown-preview-github-styles|bierner|2.0.2|
|markdown-yaml-preamble|bierner|0.1.0|
|material-icon-theme|PKief|4.28.0|
|night-owl|sdras|2.0.1|
|pdf|tomoki1207|1.2.2|
|pop-n-lock-theme-vscode|Luxcium|3.32.188|
|roslynator|josefpihrt-vscode|4.3.0|
|toggle-excluded-files|amodio|2.0.0|
|tokyo-night|enkia|0.9.9|
|vscode-coverage-gutters|ryanluker|2.11.0|
|vscode-dotnet-runtime|ms-dotnettools|1.6.0|
|vscode-fileutils|sleistner|3.10.1|
|vscode-icons|vscode-icons-team|12.4.0|
|vscode-json|andyyaldoo|1.5.2|
|vscode-markdownlint|DavidAnson|0.51.0|
|vscode-sort-json|richie5um2|1.20.0|
|vscode-sql-formatter|adpyke|1.4.4|
|vscode-yaml|redhat|1.13.0|
|vsliveshare|ms-vsliveshare|1.0.5873|;

</details>

**Comment by Spycemyster** [comment] 2023-06-14 23:29
Are there any workarounds we can use for this other than just turning off intellisense completely? This bug makes autocompletion very annoying

**Comment by dibarbet** [comment] 2023-06-15 18:57
No workaround that I know of unfortunately - however we expect this to be fixed in the next release (most likely next week).  I can also share a dev build in the next day or so with the fix if you'd like.

Closing as a duplicate of https://github.com/dotnet/vscode-csharp/issues/5777

**Closed** 2023-06-15 19:07 UTC
