### ISSUE TITLE
Parameter documentation (info) not showing

### ISSUE THREAD

**Issue by ghost** [dotnet/vscode-csharp#1739] opened 2017-08-27 13:07 UTC
## Environment data
`dotnet --info` output:

```
Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

VS Code version: 1.15.1
C# Extension version: 1.12.1

## Steps to reproduce

1. `String.Format(`
2. `throw new Exception(`

There's no parameter documentation (info) showing when calling this method (ór pressing Ctrl+Shift+Space) (1). The same happens when throwing a new Exception (2).

## Expected  behavior

Show parameter documentation.

## Actual behavior

Not showing parameter documentation.

**Comment by DustinCampbell** [comment] 2017-08-28 13:29
Hi! Just to clarify what you are reporting, are you unable to get the signature help popup to display (with the possible signature overloads). Or, is the signature help popup displaying, but without any documentation text?

**Comment by pjdv2** [comment] 2017-08-28 14:52
Hi Dustin,


Its the latter.



Kind Regards,


Pieter


________________________________
Van: Dustin Campbell <notifications@github.com>
Verzonden: maandag 28 augustus 2017 15:29
Aan: OmniSharp/omnisharp-vscode
CC: pjdv2; Author
Onderwerp: Re: [OmniSharp/omnisharp-vscode] Parameter documentation (info) not showing (#1739)


Hi! Just to clarify what you are reporting, are you unable to get the signature help popup to display (with the possible signature overloads). Or, is the signature help popup displaying, but without any documentation text?

**Comment by DustinCampbell** [comment] 2017-08-28 16:59
Thanks for clarifying. I can definitely repro that. FWIW, I see documentation text a bit inconsistently. For example, I don't see it on `String.Format(...)` or `new Exception(...)`, but I do see it for `Console.WriteLine(...)`. I'm betting this is related to https://github.com/OmniSharp/omnisharp-vscode/issues/1551.

**Comment by pjdv2** [comment] 2017-08-28 19:19
It seems related. The comment:

> @terrajobst, @richlander: Poking around a bit, _it appears that the NETStandard.Library packages don't appear to contain XML documentation like, say, the ASP.NET packages do_, which means that users don't get documentation on hover or completion in VS Code for core types and members. Is there are plan to start including documentation so that users get a good experience? 
 
Seems to apply, but I have no knowledge of the current state of the application to see what has changed in the mean time.

**Comment by DustinCampbell** [comment] 2017-08-28 19:21
I'd like to look at this separately. It seems like it might be the same, but I'd rather keep this around.

**Comment by pjdv2** [comment] 2017-08-28 19:42
If you want you can reopen it, but I feel to close it.

**Comment by DustinCampbell** [comment] 2017-08-28 19:54
Again, I'd really like to keep this issue open so we can track it separately. Thanks!

**Comment by csanthoshi** [comment] 2018-03-02 05:30
Hi @DustinCampbell 

I am seeing the same issue as @pjdv2 mentioned. The Description would be

Environment:

vscode-ruby version: 0.16.0
VS Code version: 1.16.1
Ruby-Solargraph: 0.12.0
Description:
My Ruby Project Structure contains Page Object files in which I will be writing function Definitions inside Modules. So for each function definitions I will be writing the Function Description in Yaardoc format. The issue here is, previously when I tried to use the definitions in my test case I used to get the Description/quick info of the methods when I type the definition name and also all the definitions inside module as suggestions when I type the module name.

But, since December I am not getting any function suggestions or the description of the functions. I explored if there are any issues filed and the reasons for it but unfortunately I could not figure it out.

Can someone please help me out the reason for this.

Sample Function: ProjectName/PageObjects/Hello.rb

```
module ModuleName

      # funName: Description of the Function

      # @param [String] param1

      # @param [String] param2

         def funName(param1,param2)

             begin

                  # My function definition here

             end

         end 

  end
```
FYI:
I tried to create a .solargraph.yml file and it contains

```
include:
  - ./**/*.rb
exclude:
  - spec/**/*
  - test/**/*
```
Can someone help me out the reason for this issue.

Thanks! in advance.

**Comment by gregg-miskelly** [comment] 2018-03-02 15:35
@csanthoshi This is the C# extension repo, so your problem is not related to this issue. You want to ask on the GitHub for the Ruby VS Code extension. I would also generally suggest against commenting on closed issues unless you are pretty sure the issues are related.

**Comment by JoeRobich** [comment] 2024-11-08 23:47
not able to reproduce this issue with the current release.

**Closed by JoeRobich** 2024-11-08 23:47 UTC
Labels: Bug, OmniSharp, Editor-Signature Help
