### ISSUE TITLE
Net 6/7 Debugger Fails To Attach to Process for Test Project 

### ISSUE THREAD

**Issue by gabe-calabro** [dotnet/vscode-csharp#6166] opened 2023-08-18 02:26 UTC
## Environment data

- MacOS Ventura 13.5
- VS Code 1.18.1
- .NET Core SDK 7.0.400 x64
- .NET Core Runtime 7.0.10 x64
- C# Extension v2.0.376

## Steps to reproduce

1. dotnet new sln -n foo
2. dotnet new webapi -n web
3. dotnet new mstest - n test
4. dotnet sln ./foo.sln add ./web.csproj
5. dotnet sln ./foo.sln add ./test.csproj
6. code .
7. set a break point on the sample test operation
8. click debug test
9. fails, with unable to start debugging: failed to attach to process

## Expected  behavior
Ability to debug tests

## Actual behavior

Unable to start debugging. Failed to attach to process:

## Additional context

I have no test extensions installed what-so-ever, vanilla install of VS Code. This was working for years and then just stopped.

I have rolled back to the previous .NET Core SDK and runtimes. I have rolled back to the previous VS Code as well. All with the same results. I have tried a fresh install nuking everything top to bottom for VS Code, NET Core SDK and Runtimes. I have tried this on a second Mac machine.

Everything restores and builds successfully. I can run tests, just can't debug tests. Randomely, it will work but if I try it again it fails again. Then it doesnt work until a random attempt, but only once.

I should also note that I CAN debug tests in Visual Studio for Mac.

So ultimately the problem seems to be specifically with VS Code attaching to a process for test projects.

Everything works when I roll back the extension to v1.26.0

**Comment by dibarbet** [comment] 2023-08-19 02:29
> click debug test
fails, with unable to start debugging: failed to attach to process

I haven't been able to reproduce this myself - can you set `dotnet.server.trace` to `Trace`, then attach both the C# logs and .net test logs?  Is there any info in the debug console or extension host logs?

**Comment by gabe-calabro** [comment] 2023-08-22 00:03
> 

Attached are the logs. Let me know if I missed anything.
[logs.zip](https://github.com/dotnet/vscode-csharp/files/12403479/logs.zip)

**Comment by gabe-calabro** [comment] 2023-08-22 00:07
I also noticed if I switch to us OmniSharp, everything works again on the latest version. It seems the entire issue revolves around Rosyln on the Mac.
<img width="299" alt="Screenshot 2023-08-21 at 7 06 41 PM" src="https://github.com/dotnet/vscode-csharp/assets/101517882/8fef9325-575a-44c0-aaf1-8b6d9327bb43">

**Comment by dibarbet** [comment] 2023-08-28 18:01
> @dibarbet could there be something configuration I am missing? I'd love to use rosyln if I could!

Apologies - have had some other issues that have been taking up a bunch of time.  Will look closer at this this week.  The VSTest logs you attached do look ok, but I am missing the info from the C#/.net test log output

1.  The output of the .NET test log output window
2.  The output of the C# output window
3.  The output of the extension host output window

You can find it either from the actual vscode output window, or attach a zip containing everything inside this folder
<img width="482" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/5749229/fc5d5f6f-cf29-4c56-9ca8-715feaeeeee8">

**Comment by gabe-calabro** [comment] 2023-08-29 01:14
[logs.zip](https://github.com/dotnet/vscode-csharp/files/12459257/logs.zip)
@dibarbet  here are the contents of the logs folder. Thank you!

**Comment by gabe-calabro** [comment] 2023-09-04 19:09
@dibarbet Did that give you everything you need?

**Comment by gabe-calabro** [comment] 2023-09-06 02:16
@dibarbet So I turned Omni back off, started getting the error again. Then I install the C# Dev Kit Extension and everything works. Is there an expectation to have the C# Dev Kit or should it work with just the C# extension alone?

**Comment by dibarbet** [comment] 2023-09-08 18:03
@gabe-calabro apologies for the late reply.  C# devkit uses a different method of running and debugging tests that is frankly more robust than the base C# extensions support.  I would recommend using it if you can.  

This scenario should work as well, but there is a bug here.  From the test logs it looks like we successfully request the attach, but I think the test finishes before the attach can complete
```
Starting test run
Attaching debugger to process 5254
[Passed] TestMethod1
==== Summary ====
Passed!  - Failed:    0, Passed:    1, Skipped:    0, Total:    1, Duration: 405ms
```

@gregg-miskelly I believe this is the issue you mentioned originally - where the attach doesn't actually occur when we call [vscode.startDebugging](https://github.com/dotnet/vscode-csharp/blob/main/src/lsptoolshost/roslynLanguageServer.ts#L570).  Is that API you mentioned creating available?

**Comment by gregg-miskelly** [comment] 2023-09-08 18:37
@dibarbet I implemented the API, and I have a branch of this repo where I added code to consume it, but we haven't yet inserted a debugger with my changes. Sounds like a dupe of https://github.com/dotnet/vscode-csharp/issues/5968. I put a work around in the bug.

**Comment by dibarbet** [comment] 2023-09-08 18:54
Sounds good - will resolve this in favor of https://github.com/dotnet/vscode-csharp/issues/5968

**Closed by dibarbet** 2023-09-08 18:54 UTC
Labels: Debugger
