### ISSUE TITLE
C# LSP failing suddenly on diagnostics

### ISSUE THREAD

**Issue by timheuer** [dotnet/vscode-csharp#7290] opened 2024-06-28 15:50 UTC
REPO: https://github.com/timheuer/xunitplay
Document open is TestProject2/UnitTest1.cs

When I open this workspace I'm met with a log of error notifications:

![Image](https://github.com/user-attachments/assets/c19862e6-1a02-4519-8414-fa18f5ec8677)

Log:

[csharpoutputlog.txt](https://github.com/user-attachments/files/16032997/csharpoutputlog.txt)

VS Code Extensions
  ms-dotnettools.csdevkit: 1.8.10
  ms-dotnettools.csharp: 2.36.19
  ms-dotnettools.dotnet-maui: 1.1.14

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.300 [C:\Program Files\dotnet\sdk]
  8.0.400-preview.0.24312.1 [C:\Program Files\dotnet\sdk]

**Comment by arkalyanms** [comment] 2024-06-28 16:45
No local repro on mac. Looking at the logs, there seems to be a off by one parsing error. I see a double quote and a close brace that dont belong.

[Error - 8:45:20 AM] Request textDocument/documentSymbol failed.
  Message: Unsupported extension '.cs%22,%22ref%22:%22~%22%7D' and LSP language id ''
  Code: -32000 
[object Object]

[Error - 8:45:20 AM] Request textDocument/semanticTokens/range failed.
  Message: Unsupported extension '.cs%22,%22ref%22:%22~%22%7D' and LSP language id ''
  Code: -32000

**Comment by dibarbet** [comment] 2024-06-28 17:10
There is a known issue here with temp files and git diff files (potentially other areas) where there is a race determining the language from the document.  I'm hoping to have a fix for that this week, which should also fix this issue.

However I wouldn't have expected it to occur for a regular .cs file.  @timheuer did you by chance have a diff window open, or something similar?

**Comment by timheuer** [comment] 2024-06-28 18:06
> did you by chance have a diff window open

Indeed the document was in a diff view at the time.

**Comment by dibarbet** [comment] 2024-06-28 23:04
Good to know.  Duplicate of https://github.com/dotnet/vscode-csharp/issues/7290 and I'm hoping to get the fix in next week.

**Closed by dibarbet** 2024-06-28 23:04 UTC
Labels: Bug
